"""The turn: what the model is told, what it is allowed to do, what it did, and what that cost.

## The activity feed

What the agent is doing, as a person would describe it. The summaries are written per
tool rather than rendered from `name(args)`, because a generic render is unreadable at a
glance -- and a glance is the only way this list is ever read.

An `Act` is one call from the moment it starts. It exists *before* the result does, which
is the point: a frontend can show `⏳ Web fetch: …` while the fetch is happening.

`Activity` is the stream, and the hook a frontend hangs a redraw on. `on_change` fires
twice per call -- once at the start and once at the end -- which is the entire difference
between a UI that looks alive and one that looks stuck.

## Approvals

A write is put in front of a person before it happens. Everything here exists to make that
exchange honest: what the call would actually do, one request at a time, and a refusal that
carries the reason back to the model rather than the word "denied".

An `Ask` is one request and the person's answer to it. It is truthy exactly when approved,
so an `Ask` *is* the decision -- both backends' `if not approve(tc)` keeps working, and the
reason travels with it.

`Approvals` is the queue of one and the thread handshake behind it. One at a time on
purpose: a model that wants to edit four files should be answered four times, because "yes
to all of that" is exactly the answer people give when they have not read any of it.

`gate` is the `approve(tool_call)` both backends call, and `policy` builds one from per-tool
modes -- written out here rather than imported from rishi, because the harness needs one
approval shape across both backends and must not stop working because the local engine is
not installed.

## The fastllm approval shim

Hosted models reach approvals through rishi's own remote path now, so this module is three
functions reporting that there is nothing left to patch. It stays because callers ask.

## Routing a turn before the model sees it

A small deterministic step in front of every turn. Deliberately not another model call:
routing "what default model does leela use?" to the web is exactly the mistake this
prevents, and tool choice should be predictable enough to read in the history.

The frontend composes a message around the question -- the open notebook, the screen -- so
`request_text` recovers the part the person actually typed. Everything that inspects intent
looks at that, not at the envelope.

A prompt may name a tool or a skill outright. Only names already exposed to the agent
count, so a URL or a path is left alone.

## The briefing

The system prompt: what the agent is, where it is, how to work, and what it knows. The
skill index is names and descriptions only -- bodies are a `read_skill` away -- because a
dozen full skill texts would crowd out the code the model is meant to be looking at.

## The session plan

A durable checklist for stop/start and for work a sub-agent can take a bite of. The plan
lives on `Agent`, not on the host: CLI, MCP and leela all see the same object, and a
cancelled turn does not throw the list away.

Statuses are `pending`, `active`, `done` and `cancelled`. At most one todo is `active`.
On resume, continue from the active item rather than restarting the title.

## The agent

One `Agent` owns one continuous model context, and everything else hangs off it: routing,
tools, skills, extensions, approvals, compaction, the activity feed and the durable history.
Availability is reported rather than raised -- the model is a multi-gigabyte download on one
side and an API key on the other, and an editor that will not open without either is a worse
editor.

## Inline completion

Inline completion is the argument for routing in one feature: four lines of code, fired
constantly, has to feel instant, worth approximately nothing per call. It runs on the local
model in a throwaway conversation, and never automatically -- the kernel's own completions
are instant and correct, while this costs a forward pass.

Docs: https://vedicreader.github.io/ramabana/agent.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_agent.ipynb.

# %% auto #0
__all__ = ['MAX_DETAIL', 'MAX_ACTS', 'MAX_CHECKPOINTS', 'POLL_EVERY', 'SHELL_SNAPSHOT', 'ICONS', 'DENIED', 'DFLT_TIMEOUT',
           'MAX_PREVIEW', 'INLINE_SKILLS', 'MAX_CONTEXT_FILE', 'CONTEXT_FILES', 'RULES', 'OUTPUT_CONTRACT',
           'CLAUDE_NOTES', 'TODO_STATUSES', 'TODO_MARK', 'COMPLETE_SP', 'MAX_COMPLETION_LINES', 'COMPLETION_TOKENS',
           'CTX_BEFORE', 'CTX_AFTER', 'summarise', 'Act', 'Activity', 'preview_for', 'Ask', 'ask_md', 'answer_md',
           'Approvals', 'always', 'never', 'policy', 'applied', 'apply', 'note', 'tool_plan', 'request_text',
           'prompt_directives', 'project_context', 'work_rules', 'system_prompt', 'Todo', 'Plan', 'parse_plan_items',
           'plan_tools', 'Agent', 'Completer']

# %% ../nbs/03_agent.ipynb #ace94f1a
import datetime, functools, json, re, threading, time, uuid
from dataclasses import dataclass, field
from pathlib import Path
from fastcore.basics import patch
from .core import agent_err, available_models, budget_for, JOBS, Routing, model_note, tool_channel
from .runtime import Usage, make_backend, Compactor, compact_notebook_context, notices_block
from .tools import (mime_for, MAX_TOOL_CHARS, WRITE_TOOLS, Registry, clip, discover, err, failed,
                            find, load, skill_index, subagent_tools, tools_for)

# %% ../nbs/03_agent.ipynb #2df0c05f
MAX_DETAIL = 4000     # chars of a tool result kept for the fold
MAX_ACTS = 500        # a very long turn should not grow without bound
MAX_CHECKPOINTS = 20  # turn boundaries kept for `fork`; each one is a whole conversation
POLL_EVERY = 900      # seconds between automatic `Host.poll` ticks; a turn is what triggers one

#: Characters of the open folders `changes()` will hold in order to watch a shell command.
#: A command names no files, so the only way to know what it moved is to have read them
#: first; past this much text that costs more than the answer is worth.
SHELL_SNAPSHOT = 32_000_000

ICONS = {'search': '🔍', 'view': '📄', 'edit': '✏️', 'web': '🌐', 'run': '▶️',
         'skill': '📚', 'delegate': '🤝', 'memory': '🧠', 'watch': '⏰', 'cart': '🛒',
         'tool': '🔧'}

_KIND = {
    'search_code': 'search', 'similar_code': 'search', 'outline': 'search', 'list_files': 'search',
    'grep': 'search', 'ls': 'search',
    'view_file': 'view', 'notebook_cells': 'view', 'view_cell': 'view', 'read_terminal': 'view',
    'edit_file': 'edit', 'replace_text': 'edit', 'create_file': 'edit', 'edit_cell': 'edit',
    'add_cell': 'edit',
    'web_search': 'web', 'read_url': 'web', 'research': 'web',
    'run_python': 'run', 'list_vars': 'run', 'run_shell': 'run',
    'read_skill': 'skill', 'create_skill': 'skill',
    'delegate_search': 'delegate', 'delegate_parallel': 'delegate',
    'inspect_python': 'run',
    'memory_search': 'memory', 'memory_tree': 'memory', 'memory_read': 'memory',
    'memory_topics': 'memory', 'memory_forget': 'memory', 'remember': 'memory',
    'set_reminder': 'watch', 'watch_url': 'watch', 'list_watches': 'watch',
    'cancel_watch': 'watch', 'poll_watches': 'watch',
    'cart_stores': 'cart', 'cart_open': 'cart', 'cart_find': 'cart',
    'cart_add': 'cart', 'cart_show': 'cart', 'cart_remove': 'cart',
}

#: Tools whose useful summary is the same words every time: they take nothing worth showing.
_LABEL = {'list_vars': 'List variables', 'read_terminal': 'Read terminal',
          'list_watches': 'List watches', 'poll_watches': 'Poll watches',
          'memory_topics': 'Map remembered topics', 'cart_stores': 'List stores',
          'cart_show': 'Read the trolley'}

def _s(v, n=90):
    "One line of a value, short enough to sit in a list."
    t = ' '.join(str(v or '').split())
    return t if len(t) <= n else t[:n - 1] + '…'

# %% ../nbs/03_agent.ipynb #3f508bca
def summarise(tool, args):
    "The imperative one-liner for a call: what a person would say they just did."
    a = args if isinstance(args, dict) else {}
    p, q = a.get('path', ''), a.get('query', '')
    if tool in _LABEL:           return _LABEL[tool]
    if tool == 'search_code':    return f'Search {_s(q)}'
    if tool == 'similar_code':   return f'Similar to {p}:{a.get("line", 1)}'
    if tool == 'outline':        return f'Outline {p}'
    if tool == 'list_files':     return f'List files {_s(a.get("pattern", "")) or "(all)"}'
    if tool == 'grep':
        where = f' in {a["path_filter"]}' if a.get('path_filter') else ''
        return f'Grep {_s(a.get("pattern", ""))}{where}'
    if tool == 'ls':             return f'List {p or "(open folders)"}'
    if tool == 'view_file':
        rng = f':{a["start"]}-{a["end"]}' if a.get('start') or a.get('end') else ''
        return f'View {p}{rng}'
    if tool == 'edit_file':      return f'Edit {p}'
    if tool == 'replace_text':   return f'Edit {p}'
    if tool == 'create_file':    return f'Create {p}'
    if tool == 'notebook_cells': return f'Cells of {p}'
    if tool == 'view_cell':      return f'View {p} cell {a.get("cell_id", "?")}'
    if tool == 'edit_cell':      return f'Edit {p} cell {a.get("cell_id", "?")}'
    if tool == 'add_cell':       return f'Add {a.get("cell_type", "code")} cell to {p}'
    if tool == 'web_search':     return f'Web search: {_s(q)}'
    if tool == 'read_url':       return f'Web fetch: {_s(a.get("url", ""), 120)}'
    if tool == 'research':       return f'Research: {_s(q)}'
    if tool == 'run_python':     return f'Run python: {_s((a.get("code", "") or "").strip().splitlines()[0] if a.get("code") else "")}'
    if tool == 'inspect_python':
        sc = a.get('scope') or 'isolated'
        body = _s((a.get('code', '') or '').strip().splitlines()[0] if a.get('code') else '')
        return f'Inspect: {body}' + ('' if sc == 'isolated' else f'  [{sc}]')
    if tool == 'run_shell':      return f'Run {_s(a.get("command", ""), 110)}'
    if tool == 'read_skill':     return f'Read skill {a.get("name", "?")}'
    if tool == 'create_skill':   return f'Create skill {a.get("name", "?")}'
    if tool == 'memory_search':  return f'Memory search: {_s(q)}'
    if tool == 'memory_tree':    return f'Memory tree {_s(a.get("document", "")) or "(everything)"}'
    if tool == 'memory_read':    return f'Memory read {a.get("node_id", "?")}'
    if tool == 'memory_forget':  return f'Forget {a.get("doc_id", "?")}'
    if tool == 'remember':       return f'Remember {_s(a.get("title") or a.get("text", ""))}'
    if tool == 'set_reminder':   return f'Remind every {a.get("every", "1w")}: {_s(a.get("text", ""))}'
    if tool == 'watch_url':      return f'Watch {_s(a.get("url", ""), 100)} every {a.get("every", "1d")}'
    if tool == 'cancel_watch':   return f'Cancel watch {a.get("watch_id", "?")}'
    if tool == 'cart_open':      return f'Shop at {_s(a.get("url", ""), 100)}'
    if tool == 'cart_find':      return f'Shop search: {_s(q)}'
    if tool == 'cart_add':       return f'Add to trolley: {a.get("qty", 1)} x {_s(a.get("item", ""))}'
    if tool == 'cart_remove':    return f'Remove from trolley: {_s(a.get("line", ""))}'
    if tool == 'set_plan':       return f'Set plan: {_s(a.get("title", ""))}'
    if tool == 'add_todo':       return f'Add todo: {_s(a.get("text", ""))}'
    if tool == 'update_todo':    return f'Todo {a.get("id", "?")} → {a.get("status") or "update"}'
    if tool == 'list_plan':      return 'List plan'
    if tool == 'delegate_search': return f'Delegate: {_s(a.get("question", ""), 120)}'
    if tool == 'delegate_parallel':
        try:
            import json as _j
            qs = _j.loads(a.get('questions') or '[]')
            return f'Delegate {len(qs)} questions in parallel: ' + _s('; '.join(qs), 110)
        except Exception: return f'Delegate in parallel: {_s(a.get("questions", ""), 110)}'
    inner = ', '.join(f'{k}={_s(v, 30)!r}' for k, v in a.items())
    return f'{tool}({inner})'


# %% ../nbs/03_agent.ipynb #9ab2cd3c
@dataclass
class Act:
    "One tool call, from the moment it starts to whatever it returned."
    tool: str
    args: dict = field(default_factory=dict)
    summary: str = ''
    detail: str = ''
    ok: bool = True
    done: bool = False
    secs: float = 0.0
    started: float = field(default_factory=time.time)
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    turn_id: str = ''
    revision: int = 0
    branch_id: str = 'main'
    parent_action_id: str = ''
    state: str = 'running'

    @property
    def kind(self): return _KIND.get(self.tool, 'tool')

    @property
    def icon(self): return ICONS.get(self.kind, ICONS['tool'])

    def finish(self, out, ok=True):
        self.detail = _clip(out)
        self.ok, self.done, self.state = ok, True, ('complete' if ok else 'failed')
        self.secs = round(time.time() - self.started, 2)
        return self

    def line(self):
        "The single line: icon, what it did, and how long -- or an hourglass while it runs."
        if not self.done: return f'⏳ {self.summary}'
        tail = f'  ({self.secs:.1f}s)' if self.secs >= 0.5 else ''
        return f'{"" if self.ok else "⚠️ "}{self.icon} {self.summary}{tail}'

    def md(self, fold=True):
        "This call as markdown: the line, with the result folded under it when there is one."
        if not (self.detail and fold): return f'- {self.line()}'
        body = self.detail.replace('```', '`​``')     # a fence in a result must not end ours
        return (f'- {self.line()}\n\n'
                f'  <details><summary>result</summary>\n\n  ```\n{_indent(body)}\n  ```\n\n  </details>')

    def dict(self):
        return {'id': self.id, 'action_id': self.id, 'turn_id': self.turn_id,
                'revision': self.revision, 'branch_id': self.branch_id,
                'parent_action_id': self.parent_action_id, 'state': self.state,
                'tool': self.tool, 'kind': self.kind, 'icon': self.icon,
                'summary': self.summary, 'line': self.line(), 'detail': self.detail,
                'ok': self.ok, 'done': self.done, 'secs': self.secs,
                'args': {k: _s(v, 300) for k, v in (self.args or {}).items()}}


def _clip(out, n=MAX_DETAIL):
    s = '' if out is None else str(out)
    return s if len(s) <= n else s[:n] + f'\n…[{len(s)-n} more chars]'


def _indent(s, pad='  '):
    return '\n'.join(pad + l for l in s.splitlines())

# %% ../nbs/03_agent.ipynb #bb3e51e3
class Activity:
    "The stream of calls for a session, and the hook a frontend hangs a redraw on."

    def __init__(self, on_change=None, max_acts=MAX_ACTS):
        self.acts, self.on_change, self.max_acts = [], on_change, max_acts
        self._lock = threading.Lock()
        self._mark = 0
        self.turn_id = ''

    def __len__(self): return len(self.acts)

    def start(self, tool, args, action_id='', turn_id='', revision=0, branch_id='main', parent_action_id=''):
        a = Act(tool=tool, args=dict(args or {}), summary=summarise(tool, args),
                id=action_id or uuid.uuid4().hex[:12], turn_id=turn_id or self.turn_id,
                revision=int(revision or 0), branch_id=branch_id or 'main',
                parent_action_id=parent_action_id or '')
        with self._lock:
            self.acts.append(a)
            if len(self.acts) > self.max_acts: del self.acts[:-self.max_acts]
        self._changed(a)
        return a

    def finish(self, act, out, ok=True):
        act.finish(out, ok)
        self._changed(act)
        return act

    def _changed(self, act):
        if not self.on_change: return
        try: self.on_change(act)
        except Exception: pass

    # -- reading it ----------------------------------------------------------
    def mark(self, turn_id=''):
        "Remember where the stream is now and bind new actions to one durable turn id."
        self._mark = len(self.acts)
        if turn_id: self.turn_id = str(turn_id)
        return self._mark

    def since(self, mark=None):
        return self.acts[(self._mark if mark is None else mark):]

    def rows(self, n=None, mark=None):
        "The stream as dicts, for a frontend. `mark` limits it to one turn."
        acts = self.since(mark) if mark is not None else self.acts
        return [a.dict() for a in (acts[-n:] if n else acts)]

    def md(self, mark=None, fold=True, title='what I did'):
        "The stream as markdown, for saving into a notebook cell."
        acts = self.since(mark) if mark is not None else self.acts
        if not acts: return ''
        body = '\n'.join(a.md(fold) for a in acts)
        return f'<details><summary>{title} ({len(acts)} steps)</summary>\n\n{body}\n\n</details>'

    def lines(self, mark=None):
        "Just the summary lines, for a status pane with no room for folds."
        return [a.line() for a in (self.since(mark) if mark is not None else self.acts)]

# %% ../nbs/03_agent.ipynb #fb06a049
DENIED = 'Denied by human operator'

DFLT_TIMEOUT = 300      # seconds to wait for a person before giving up on one request
MAX_PREVIEW = 2000      # chars of "what would change"; a person will not read more


def _args(args):
    "A tool call's arguments as a dict, whether the model sent a dict or a JSON string."
    if isinstance(args, str):
        try: args = json.loads(args)
        except Exception: return {}
    return args if isinstance(args, dict) else {}


def _tc(tool_call):
    "`(name, args)` from a tool call in either backend's shape."
    if hasattr(tool_call, 'name'): return tool_call.name, _args(getattr(tool_call, 'arguments', {}))
    fn = (tool_call or {}).get('function', {}) if isinstance(tool_call, dict) else {}
    return fn.get('name', '?'), _args(fn.get('arguments', {}))

# %% ../nbs/03_agent.ipynb #f0c058fe
def _fmt_cmds(commands):
    "exhash commands as one readable block, rather than as a JSON blob nobody reads."
    try:
        cmds = json.loads(commands) if isinstance(commands, str) else commands
        if not isinstance(cmds, list): raise ValueError
    except Exception:
        return str(commands)[:MAX_PREVIEW]
    out = []
    for c in cmds:
        if not isinstance(c, (list, tuple)) or not c: out.append(str(c)); continue
        addr, op, rest = c[0], (c[1] if len(c) > 1 else ''), list(c[2:])
        body = '\n'.join('    ' + str(r).replace('\n', '\n    ') for r in rest)
        out.append(f'{addr} {op}' + (f'\n{body}' if body else ''))
    return '\n'.join(out)


def preview_for(name, args, host=None):
    "What this call would actually do, as text a person can read in a couple of seconds."
    p = args.get('path', '')
    if name == 'edit_file':   return f'{p}\n\n{_fmt_cmds(args.get("commands", ""))}'[:MAX_PREVIEW]
    if name == 'edit_cell':   return f'{p} cell {args.get("cell_id","?")}\n\n{_fmt_cmds(args.get("commands",""))}'[:MAX_PREVIEW]
    if name == 'create_file':
        text, exists = args.get('text', ''), False
        try: exists = bool(host and host.check(p).exists())
        except Exception: pass
        head = f'{p}  ({"OVERWRITES an existing file" if exists else "new file"}, {len(text)} chars)\n\n'
        return (head + text)[:MAX_PREVIEW]
    if name == 'add_cell':
        return f'{p}  (new {args.get("cell_type","code")} cell at {args.get("index",-1)})\n\n{args.get("source","")}'[:MAX_PREVIEW]
    if name == 'run_python':  return str(args.get('code', ''))[:MAX_PREVIEW]
    return json.dumps(args, indent=2, default=str)[:MAX_PREVIEW]


def _summary(name, args):
    "The one-line version, for a status bar or a footer."
    if p := args.get('path'): return f'{name} → {p}'
    return f'{name}({", ".join(sorted(args))})'

# %% ../nbs/03_agent.ipynb #cad351c6
@dataclass
class Ask:
    "One request, and the person's answer to it; `answer` is None while it is pending."
    tool: str
    args: dict = field(default_factory=dict)
    summary: str = ''
    preview: str = ''
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    answer: bool = None
    note: str = ''
    asked: float = field(default_factory=time.time)
    _done: threading.Event = field(default_factory=threading.Event, repr=False, compare=False)

    @property
    def pending(self): return self.answer is None

    def __bool__(self):
        "Truthy exactly when approved, so an `Ask` *is* the approval decision."
        return self.answer is True

    def dict(self):
        return {'id': self.id, 'tool': self.tool, 'summary': self.summary, 'preview': self.preview,
                'answer': self.answer, 'note': self.note, 'pending': self.pending}

    def resolve(self, ok, note=''):
        self.answer, self.note = bool(ok), note or ''
        self._done.set()
        return self

    def wait(self, timeout):
        "Block until answered or `timeout` seconds pass. Returns whether it was answered."
        return self._done.wait(timeout)

    def reply(self):
        "What the model is told: a refusal with its reason, an approval with its note."
        if self.answer: return f'Approved by the user. Note from the user: {self.note}' if self.note else None
        return f'{DENIED}. Reason given: {self.note}' if self.note else DENIED

# %% ../nbs/03_agent.ipynb #53d05cb9
def ask_md(ask):
    "An approval request as markdown -- what a person reads, and what is saved in the notebook."
    body = ask.preview.strip()
    fence = '```\n' + body + '\n```\n\n' if body else ''
    return (f'**🔐 approval needed -- `{ask.tool}`**\n\n{ask.summary}\n\n{fence}'
            'Approve, or refuse with a reason -- the reason goes back to the model.')

def answer_md(ask):
    "The person's half of the exchange, in the same voice."
    head = '**✅ approved**' if ask.answer else '**⛔ refused**'
    return f'{head} -- `{ask.tool}`' + (f'\n\n{ask.note}' if ask.note else '')

# %% ../nbs/03_agent.ipynb #ca1437e3
class Approvals:
    "The queue of one, and the thread handshake behind it. One request at a time."

    def __init__(self,
                 tools=(),                  # tool names that need approval; everything else runs
                 mode='ask',                # 'ask' | 'auto' (approve everything) | 'off' (refuse everything)
                 timeout=DFLT_TIMEOUT,
                 host=None,                 # for previews that need to look at disk
                 on_ask=None,               # called with the `Ask` when one is raised
                 on_answer=None):           # called with the `Ask` when it is answered
        self.tools, self.mode, self.timeout, self.host = frozenset(tools), mode, timeout, host
        # the application's recorder; frontends register through `listen` instead, so neither unhooks the other
        self.on_ask, self.on_answer = on_ask, on_answer
        self.current = None                 # the `Ask` in flight, or None
        self.history = []                   # every `Ask` this session, answered or not
        self._watchers = []                 # (on_ask, on_answer) per registered frontend
        self._lock = threading.Lock()

    # -- the frontend side ---------------------------------------------------
    @property
    def listeners(self): return len(self._watchers)

    def listen(self, on_ask=None, on_answer=None):
        "Register a frontend, and how to reach it. Returns a callable that unregisters it."
        w = (on_ask, on_answer)
        with self._lock: self._watchers.append(w)
        done = [False]
        def stop():
            if done[0]: return
            done[0] = True
            with self._lock:
                if w in self._watchers: self._watchers.remove(w)
        return stop

    def _notify(self, which, a):
        "Call the recorder and every watcher, swallowing failures so one bad frontend cannot block a turn."
        fns = [getattr(self, f'on_{which}')] + [w[0 if which == 'ask' else 1] for w in list(self._watchers)]
        for f in fns:
            if not f: continue
            try: f(a)
            except Exception: pass

    @property
    def pending(self):
        "The request waiting for an answer, or None. What both frontends poll."
        a = self.current
        return a if (a is not None and a.pending) else None

    def answer(self, id, ok, note='', session=False):
        "Answer the pending request; optionally approve all later writes this session."
        a = self.current
        if a is None or a.id != id or not a.pending: return None
        if ok and session: self.mode = 'auto'   # only an approval may turn the policy off
        # record and notify before waking the model thread, so a recorder finishes first
        a.answer, a.note = bool(ok), note or ''
        if ok and session and not a.note: a.note = 'approved for the rest of this session'
        self._notify('answer', a)
        a._done.set()
        return a

    def _decided(self, a, ok, note):
        "Resolve without asking anybody, and still tell the recorder."
        a.resolve(ok, note)
        self._notify('answer', a)
        return a

    def cancel_all(self, note='the turn was cancelled'):
        "Refuse anything in flight, so a stopped turn does not leave a worker thread parked."
        a = self.pending
        if a is not None: self.answer(a.id, False, note)

    # -- the model side ------------------------------------------------------
    def gate(self, tool_call):
        "The `approve(tool_call)` both backends call. Blocks the model's thread."
        return self.request(*_tc(tool_call))

    def request(self, name, args, force=False, timeout=None):
        "Raise one request and wait for it. Returns the resolved `Ask`, whose `reply()` carries the reason."
        a = Ask(tool=name, args=args, summary=_summary(name, args), preview=preview_for(name, args, self.host))
        self.history.append(a)
        if not force and name not in self.tools: return a.resolve(True)   # `force` asks anyway
        if self.mode == 'auto': return a.resolve(True)
        if self.mode == 'off': return self._decided(a, False, 'approval is switched off for this session')
        if self.listeners < 1:
            return self._decided(a, False, 'nothing is listening for approvals, so this could not be asked')
        self.current = a
        self._notify('ask', a)
        wait_for = self.timeout if timeout is None else timeout
        if not a.wait(wait_for):
            a.resolve(False, f'no answer after {wait_for}s')
            self._notify('answer', a)
        return a

# %% ../nbs/03_agent.ipynb #584448e4
def always(tool_call): return True
def never(tool_call): return False

def policy(modes, ask):
    "`approve(tool_call)` from per-tool modes: 'approved' | 'check' | 'dont_run'."
    def approve(tc):
        name, _ = _tc(tc)
        mode = (modes or {}).get(name, 'check')
        return True if mode == 'approved' else False if mode == 'dont_run' else ask(tc)
    return approve

# %% ../nbs/03_agent.ipynb #3287bcb5
def applied(): return True
def apply(): return True
def note(): return 'provided by rishi.remote'

# %% ../nbs/03_agent.ipynb #6b808b15
INLINE_SKILLS = ('exhash', 'coding_patterns')


def tool_plan(prompt):
    "A small deterministic routing step before the model sees a turn; never another model call."
    p = str(prompt or '').lower()
    repo = ('this repo', 'repository', 'codebase', 'implementation', 'implemented',
            'default model', 'config', 'source code', 'where is', 'which file', ' method',
            ' function', ' class')
    current = ('latest', 'current docs', 'documentation says', 'release notes', 'on the web',
               'today', 'recent version')
    action = ('create', 'make', 'scale', 'run', 'execute', 'fix', 'change', 'add ', 'remove', 'rename')
    if any(x in p for x in repo):
        return ('repo', 'Use search_code first. Read the matching source if needed. '
                        'Do not web-search a question about the open repository.')
    if any(x in p for x in current):
        return ('web', 'Use web_search, then read_url for the authoritative result.')
    if p.strip().startswith(action) or ' as df_' in p:
        return ('act', 'Use the execution/editing tool that produces the requested result, then verify it.')
    return ('direct', 'Answer directly; use a tool only if the available context is insufficient.')

# %% ../nbs/03_agent.ipynb #23d3d109
def request_text(prompt):
    """The person's request, excluding notebook/screen context composed around it."""
    text = prompt[-1] if isinstance(prompt, (list, tuple)) and prompt else prompt
    text = str(text or '')
    match = re.search(r'<user-request>\n?(.*?)\n?</user-request>\s*$', text, re.S)
    return match.group(1) if match else text

# %% ../nbs/03_agent.ipynb #fdd81169
def prompt_directives(prompt, tools=(), skills=()):
    "Explicit `/tool` and `/skill-name` mentions in an ordinary prompt; known names only."
    text = str(prompt or '')
    tool_names = {getattr(t, '__name__', ''): t for t in tools}
    skill_names = {s.name.lower(): s for s in skills}
    matches = list(re.finditer(r'(?<!\S)/([A-Za-z_][\w-]*)', text))
    requested, loaded = [], []
    for i, match in enumerate(matches):
        name = match.group(1)
        if name in tool_names:
            end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
            requested.append((name, text[match.end():end].strip()))   # the text after it is the suggested query
        elif name.lower() in skill_names:
            loaded.append(skill_names[name.lower()])
    return requested, loaded

# %% ../nbs/03_agent.ipynb #4d102b68
MAX_CONTEXT_FILE = 8000     # chars of one AGENTS.md; past this it is documentation, not instructions
CONTEXT_FILES = ('AGENTS.md', '.agents/AGENTS.md', '.leela/AGENTS.md')

def project_context(host, mx=MAX_CONTEXT_FILE):
    "The project's own instructions to an agent, from `AGENTS.md` in each open folder."
    from pathlib import Path
    out, seen = [], set()
    for r in host.roots or ():
        for rel in CONTEXT_FILES:
            try: p = host.check(Path(r)/rel)
            except Exception: continue
            if str(p) in seen: continue
            seen.add(str(p))
            try: text = host.read(str(p))
            except Exception: text = None
            if not text or not text.strip(): continue
            body = text.strip()
            if len(body) > mx: body = body[:mx] + f'\n…[truncated; read {p} in full if you need the rest]'
            out.append(f'<project_instructions path="{p}">\n{body}\n</project_instructions>')
    if not out: return ''
    return ('\n\n<project_context>\nInstructions this project gives to any agent working in it. They\n'
            'override the general guidance above where they disagree.\n\n' + '\n\n'.join(out) +
            '\n</project_context>')


# The briefing's working rules, tagged with the tool each is about; `None` always applies.
RULES = (
    (None, 'Act on the user’s verb. “Create”, “run”, “fix”, “add” and “as NAME” request a\n'
           '  result, not a plan: use the tool that produces it, verify it, then report what exists.\n'
           '  Never stop at “I will…”.'),
    (None, 'Start every user-facing response with what you plan to do or the next action. Keep the user\n'
           '  informed during ongoing work, and end the response with the result, conclusion, or what is needed.'),
    (None, 'Never claim a file changed, a command passed, or a test went green unless a tool\n'
           '  result in this conversation says so. If you did not run it, say you did not run it.'),
    (None, 'A tool result starting with ERROR: is a failure. Read it, fix the cause, and try a\n'
           '  different approach. Calling the same tool again unchanged is never the fix.'),
    ('search_code', 'Use `search_code` for project behaviour, unfamiliar APIs, or uncertainty about an\n'
                    '  installed library -- the index covers this repo *and* every installed package. Do not\n'
                    '  search for routine Python you already know.'),
    ('grep', 'Use `grep` when you know the exact string: a symbol you are renaming, an error\n'
             '  message, an import. `search_code` finds what is *like* the query; `grep` finds every\n'
             '  place it literally occurs, which is what a rename or an audit needs.'),
    ('view_file', 'Prefer `view_file` over guessing. Copy paths exactly from the workspace, notebook\n'
                  '  context, or search results; never shorten, repair, or reconstruct a path.'),
    ('replace_text', 'To change a file: read it, then `replace_text` with `oldText` copied exactly from\n'
                     '  what you read. Send every change to one file as one call.'),
    ('edit_file', '`edit_file` is the other editor: it addresses lines by the hashes `view_file`\n'
                  '  returns, so a stale read fails instead of damaging the wrong line. Use it when that\n'
                  '  matters, and read the `exhash` skill before your first one.'),
    ('notebook_cells', 'Never use `view_file` or `edit_file` on an `.ipynb` file. Call `notebook_cells` on\n'
                       '  its exact path, choose the returned cell id, then `view_cell` and `edit_cell`.'),
    (None, 'A `<notebook path="…">` block is the open notebook and its exact path. Its cells are\n'
           '  already visible; use that path with the notebook tools and never reconstruct it.'),
    ('run_shell', 'Check your work with `run_shell`: after an edit run the project’s tests, after a\n'
                  '  signature change run its linter or type checker. Use the commands the project itself\n'
                  '  documents (README, pyproject, Makefile). Never start a server, watcher or REPL --\n'
                  '  only commands that exit on their own.'),
    ('run_python', 'Code cells inside `<notebook>` have already executed. Their printed `<output>` is not\n'
                   '  Python and must never be copied into `run_python`. For a request about `df`, call\n'
                   '  `list_vars` first, then run only the transformation the user asked for.'),
    ('run_python', '`run_python` shares the user’s kernel namespace. Read anything; bind results to NEW\n'
                   '  names. You cannot rebind or delete the user’s variables, so do not try.'),
    ('web_search', 'Use `web_search`/`read_url` only when the answer depends on current external\n'
                   '  documentation -- not for questions about this repository.'),
    ('memory_search', 'Before acting on a request, search Vishalakshi durable memory with `memory_search` when\n'
                      '  that tool is available; use stored preferences and relevant prior context.'),
    ('delegate_parallel', 'When two or more questions are independent and each would take several tool calls,\n'
                          '  send them together with `delegate_parallel` rather than working through them yourself.'),
    (None, 'Make the change the user asked for and no other. Do not reformat, reorganise, or\n'
           '  “improve” code you were not asked to touch, and never discard their edits.'),
    (None, 'Writes may be put to the user for approval. A refusal comes back with their reason --\n'
           '  read it and change the approach, do not retry the same call.'),
    (None, 'Write, edit and run only inside the folders above. Anything else is refused.'),
    (None, 'Be concise. Report what you did and what it cost, not what you intend to do.'),
    (None, 'Answer in plain sentences. Headings, bullet lists and bold belong in a document the\n'
           '  user asked for, not in a reply, and a code fence holds code rather than prose.\n'
           '  Formatting a two-line answer as a report is the most common way this briefing is ignored.'),
)


#: Re-asserted after the tag block on the tags channel. Rishi appends the tool protocol *after*
#: the briefing there, so the last thing those models read is tool punctuation rather than the
#: rules. Riding out with the turn is the only way the rules get to be last instead.
OUTPUT_CONTRACT = ('\n\n<output-contract>Reply in plain sentences: no headings, no bullet list, no '
                   'bold, no code fence around prose. Lead with the answer and stop. This outranks any '
                   'formatting habit carried in from another harness.</output-contract>')


def work_rules(names=()):
    "The briefing's rules, keeping those whose tool is on the table; empty `names` filters nothing."
    names = set(names or ())
    return '\n'.join(f'- {text}' for tool, text in RULES if not names or tool is None or tool in names)


def system_prompt(host, skills=(), inline=INLINE_SKILLS, extra='', tools=()):
    "The agent's briefing: what it is, where it is, how to work, and what it knows."
    names = {getattr(t, '__name__', '') for t in tools or ()}
    roots = '\n'.join(f'  {r}' for r in host.roots) or '  (no folder open)'
    if getattr(host, 'read_outside', False):   # only when the host says so
        roots += ('\n  Reads may name any path on this machine. Writing, running commands and\n'
                  '  listing files stay inside the folders above.')
    conc = (   # claimed only where it is true'\n  Your kernel runs each inspection in its own subshell, so this works while one '
            "of the user's cells is still running." if getattr(host, 'concurrent', False) else '')
    live = ('' if 'inspect_python' not in names and names else
            '\n- To *look at* live state, prefer `inspect_python`: neither of its scopes can change\n'
            '  what the user made, so it needs no approval. Start with the default sandbox and pass\n'
            f"  `scope='overlay'` when it refuses a library call you need.{conc}")
    sp = f"""You are Ramabana, a coding agent. Follow the user's latest explicit request and the project instructions below. You are working in these folders:
{roots}

You can search the code index (this repo *and* every installed package), read and edit
files, run commands in the project, run Python in the user's live kernel namespace, read
the web, and read skills that describe the tools already installed here.

How to work:
{work_rules(names)}{live}"""
    idx = skill_index(skills)
    if idx: sp += idx
    for name in inline or ():
        if (s := find(skills, name)): sp += f'\n\n## {s.name}\n\n{s.text()}'
    sp += project_context(host)
    return sp + (f'\n\n{extra}' if extra else '')

# %% ../nbs/03_agent.ipynb #8eff0a57
CLAUDE_NOTES = """## Working as Claude

These apply on top of the rules above, and outrank them where they disagree.

- The environment and the repository history are the user's. Do not install packages, change environment configuration, or run any git command -- read-only ones included -- unless the user approved that exact command in this conversation. Where git would answer something, name the command and ask.
- Approval does not travel. Confirm before an action that is hard to reverse or that is visible outside this machine, and look at the target before you delete or overwrite it. If what you find contradicts how it was described, say that instead of proceeding.
- There is no momentum. Never extend agreed work into new decisions, and when in doubt whether something was agreed, it was not. Approval for a downstream change does not cover an upstream one.
- A question outranks the work in flight. Answer it in prose and end the turn. A question is never approval to continue and never an occasion to change code.
- Correct the record. When an earlier claim of yours turns out to be wrong, say so plainly rather than moving quietly past it.
- Before finalizing a turn, reflect on mistakes made during it. For each concrete mistake with a reusable correction, record the mistake and its fix in Vishalakshi with `remember`, so later work can avoid it.

- Everything the user needs is in the final text of the turn, with no tool call after it. Text between tool calls may never reach them, so restate anything important that appeared only mid-run.
- Lead with the outcome when the turn concludes: the first sentence says what happened or what you found. Keep the plan-first opener for a turn that will carry on working.
- No metadiscourse. Do not advertise the content ("the key point is", "what's interesting is"), and never end on a caveat or a note. A risk that could change the decision belongs in the body, beside the reasoning it affects.
- Never hard-wrap prose: one paragraph is one line, and the display wraps it. To show markdown the user can copy, use a four-space indented block rather than a fence.
"""

# %% ../nbs/03_agent.ipynb #8f32832a
TODO_STATUSES = ('pending', 'active', 'done', 'cancelled')
TODO_MARK = {'pending': '[ ]', 'active': '[▸]', 'done': '[x]', 'cancelled': '[-]'}

@dataclass
class Todo:
    "One step on a session plan."
    id: str
    text: str
    status: str = 'pending'   # pending | active | done | cancelled
    note: str = ''
    owner: str = ''           # '' = main agent; a label when a sub-agent owns it

    def __post_init__(self):
        if self.status not in TODO_STATUSES:
            raise ValueError(f'status must be one of {TODO_STATUSES}')

    def dict(self):
        return dict(id=self.id, text=self.text, status=self.status, note=self.note, owner=self.owner)

    @classmethod
    def from_dict(cls, d):
        if isinstance(d, Todo): return d
        if not isinstance(d, dict): return cls(id=uuid.uuid4().hex[:8], text=str(d))
        return cls(id=str(d.get('id') or uuid.uuid4().hex[:8]),
                   text=str(d.get('text') or ''),
                   status=str(d.get('status') or 'pending'),
                   note=str(d.get('note') or ''),
                   owner=str(d.get('owner') or ''))


class Plan:
    "The session's working list: what to do, what's done, what to resume after a stop."
    def __init__(self, title='', todos=None, updated=0.):
        self.title = str(title or '')
        self.todos, self.updated = [], float(updated or time.time())
        for it in todos or ():
            if isinstance(it, Todo): self.todos.append(it)
            elif isinstance(it, dict): self.todos.append(Todo.from_dict(it))
            else:
                text = str(it).strip()
                if text: self.todos.append(Todo(id=uuid.uuid4().hex[:8], text=text))

    def __bool__(self): return bool(self.title) or bool(self.todos)
    def __len__(self): return len(self.todos)

    def dict(self):
        return dict(title=self.title, updated=self.updated, todos=[t.dict() for t in self.todos])

    @classmethod
    def from_dict(cls, d):
        d = dict(d or {})
        return cls(title=d.get('title') or '', todos=d.get('todos') or [], updated=d.get('updated') or 0.)

    def progress(self):
        " `(done, total)` counting cancelled out of the total."
        alive = [t for t in self.todos if t.status != 'cancelled']
        return sum(t.status == 'done' for t in alive), len(alive)

    def active(self):
        return next((t for t in self.todos if t.status == 'active'), None)

    def pending(self):
        return [t for t in self.todos if t.status == 'pending']

    def find(self, key):
        "Exact id, or a unique prefix / unique text substring."
        key = str(key or '').strip()
        if not key: return None
        for t in self.todos:
            if t.id == key: return t
        pref = [t for t in self.todos if t.id.startswith(key)]
        if len(pref) == 1: return pref[0]
        text = [t for t in self.todos if key.lower() in t.text.lower()]
        return text[0] if len(text) == 1 else None

    def _touch(self): self.updated = time.time(); return self

    def clear(self):
        self.title, self.todos = '', []
        return self._touch()

    def set(self, title, items=()):
        "Replace the plan. `items` are todo texts (str) or dicts/`Todo`s."
        self.title = str(title or '').strip()
        out = []
        for it in items or ():
            if isinstance(it, Todo): out.append(it)
            elif isinstance(it, dict): out.append(Todo.from_dict(it))
            else:
                text = str(it).strip()
                if text: out.append(Todo(id=uuid.uuid4().hex[:8], text=text))
        self.todos = out
        return self._touch()

    def add(self, text, status='pending', owner='', id=None):
        t = Todo(id=id or uuid.uuid4().hex[:8], text=str(text).strip(), status=status, owner=owner)
        if not t.text: raise ValueError('todo text is empty')
        self.todos.append(t)
        return self._touch() and t

    def update(self, key, status=None, note=None, text=None, owner=None):
        t = self.find(key)
        if t is None: raise KeyError(f'no todo matches {key!r}')
        if status is not None:
            if status not in TODO_STATUSES: raise ValueError(f'status must be one of {TODO_STATUSES}')
            if status == 'active':
                for o in self.todos:
                    if o is not t and o.status == 'active': o.status = 'pending'
            t.status = status
        if note is not None: t.note = str(note)
        if text is not None: t.text = str(text).strip() or t.text
        if owner is not None: t.owner = str(owner)
        self._touch()
        return t

    def md(self):
        "Checklist for a briefing, a status block, or a `/plan` reply."
        if not self: return '(no plan)'
        done, total = self.progress()
        head = self.title or 'Plan'
        lines = [f'**{head}**  ·  {done}/{total} done']
        for t in self.todos:
            mark = TODO_MARK.get(t.status, '[ ]')
            own = f'  @{t.owner}' if t.owner else ''
            note = f'  -- {t.note}' if t.note else ''
            lines.append(f'{mark} `{t.id}` {t.text}{own}{note}')
        return '\n'.join(lines)

    def line(self):
        "One status-bar fragment, or '' when empty."
        if not self: return ''
        done, total = self.progress()
        cur = self.active()
        bit = f'{done}/{total}'
        if cur: bit += f' ▸ {cur.text[:40]}'
        elif self.pending(): bit += f' · next: {self.pending()[0].text[:36]}'
        return bit


def parse_plan_items(items):
    "Newline text, a JSON list, or a Python list -> todo texts."
    if items is None or items == '': return []
    if isinstance(items, (list, tuple)): return [str(x).strip() for x in items if str(x).strip()]
    s = str(items).strip()
    if s.startswith('['):
        try:
            data = json.loads(s)
            if isinstance(data, list): return [str(x).strip() for x in data if str(x).strip()]
        except Exception: pass
    return [ln.strip().lstrip('-* ').strip() for ln in s.splitlines() if ln.strip()]


def plan_tools(get_plan, save=None):
    """Model-facing plan tools. Closures over the agent's `Plan` so Host stays free of them."""
    def _save():
        if save:
            try: save()
            except Exception: pass

    def set_plan(title: str, items: str = '') -> str:
        "Replace the session plan. `items` is a newline list or a JSON list of step texts."
        todos = parse_plan_items(items)
        if not str(title or '').strip() and not todos:
            get_plan().clear(); _save(); return 'plan cleared'
        get_plan().set(title, todos); _save()
        return get_plan().md()

    def add_todo(text: str, status: str = 'pending') -> str:
        "Append one step to the session plan."
        try: t = get_plan().add(text, status=status or 'pending')
        except Exception as e: return err('could not add todo', e)
        _save()
        return f'added `{t.id}` ({t.status}): {t.text}\n\n{get_plan().md()}'

    def update_todo(id: str, status: str = '', note: str = '', text: str = '') -> str:
        """Update a todo by id or unique prefix. Status: pending, active, done, cancelled.

        Mark the step you are working on `active`, and `done` when it is finished. After a
        stop, resume from the active step rather than rewriting the plan.
        """
        kw = {}
        if status: kw['status'] = status
        if note != '': kw['note'] = note
        if text: kw['text'] = text
        if not kw: return err('nothing to update; pass status, note or text')
        try: t = get_plan().update(id, **kw)
        except Exception as e: return err('could not update todo', e)
        _save()
        return f'`{t.id}` → {t.status}: {t.text}' + (f' -- {t.note}' if t.note else '') + f'\n\n{get_plan().md()}'

    def list_plan() -> str:
        "The current session plan as a checklist."
        return get_plan().md()

    return [set_plan, add_todo, update_todo, list_plan]


# %% ../nbs/03_agent.ipynb #083961a6
class Agent:
    "The IDE's agent: a routed chat whose tools are the host's own capabilities."

    def __init__(self,
                 host,
                 model=None,                # the turn model; None takes the routing default
                 routing=None,
                 sp=None,                   # override the whole briefing
                 approvals=None,            # an `Approvals`; None means nothing is gated
                 cfg=None,                  # config dir, for skills and extensions
                 compact=True,              # compact automatically at the threshold
                 compact_strategy='summary', # 'summary' model checkpoint | 'surgical' deterministic DSL
                 kernel_alive=True,         # what the post-compaction note may promise
                 extensions=True,
                 project_extensions=False,  # project extensions execute repo code: opt in
                 ext_paths=(),
                 inline_skills=INLINE_SKILLS,
                 subagents=True,
                 local_multimodal=False,       # load LiteRT vision/audio encoders for local models
                 tool_max_len=MAX_TOOL_CHARS,
                 on_compact=None,
                 on_activity=None,
                 history_name='agent',      # separate durable conversations can share one config dir
                 poll_every=POLL_EVERY,     # seconds between automatic watch polls; 0 never polls
                 instruction_style='ramabana'): # 'ramabana' | 'aai' compatibility profile
        self.host, self.cfg, self.inline_skills = host, cfg, inline_skills
        if instruction_style not in ('ramabana', 'aai'): raise ValueError('instruction_style must be ramabana or aai')
        self.instruction_style = instruction_style
        self.history_name = history_name
        # one Agent owns one continuous model context, persisted so history can group turns
        self.session_id = f'agent_{datetime.datetime.now().strftime("%Y%m%d-%H%M%S")}'
        self.turn_seq, self.current_turn_id = 0, ''
        self.current_branch_id, self.checkpoints = 'main', {}
        self.routing = routing or Routing(turn=model)
        if model: self.routing.set(model)
        self.approvals, self.tool_max_len, self.subagents = approvals, tool_max_len, subagents
        self.local_multimodal = bool(local_multimodal)
        self.extensions, self.project_extensions, self.ext_paths = extensions, project_extensions, ext_paths
        self._sp = sp
        self.compactor = Compactor(auto=compact, strategy=compact_strategy, kernel_alive=kernel_alive, on_compact=on_compact)
        self.activity = Activity(on_change=on_activity)   # the live account of what it is doing
        self.plan = Plan()       # durable checklist for stop/start and sub-agent bites
        self.on_plan = None      # frontend hook: callable(plan) after every mutation
        self.calls = []          # (tool, args) per call this session -- what the UI shows as activity
        self.history = []        # inspectable user/assistant turns, including the chosen tool plan
        self._load_history()
        self._load_plan()
        self.before = {}         # path -> its text just before a write tool touched it, this turn
        self._walked = False     # whether the whole tree was snapshotted for a shell command
        self._tool_calls_turn = 0 # backend-independent guard for local/native tool loops
        self.max_tool_calls = 80
        self.use = Usage()       # this session's total, across every model it routed to
        self.turn_use = Usage()  # the completed foreground turn only; persisted with history
        self._usage_seen = {}    # backend cumulative counters already folded into `use`
        self.note = 'not started'
        self._backends, self._skills, self._reg, self._tools = {}, None, None, None
        self._subtools = None    # built only when sub-agents run on a smaller model than the turn
        self._plain = []         # the unwrapped tools, which is what the briefing is written from
        self.poll_every, self._polled, self._poll_thread = float(poll_every or 0), 0.0, None
        self.lock = threading.Lock()

    # -- what it knows -------------------------------------------------------
    @property
    def skills(self):
        "Every discovered skill, found once. Includes anything an extension registered."
        if self._skills is None:
            try:
                self._skills = discover(self.host.roots, self.cfg, extra=self.registry.skills)
            except Exception as e:
                self._skills = []
                self.note = f'skills unavailable ({agent_err(e)})'
        return self._skills

    @property
    def registry(self):
        "The extension registry, loaded once. Empty when extensions are switched off."
        if self._reg is None:
            self._reg = Registry(host=self.host, agent=self)
            if self.extensions:
                try: load(self._reg, self.host.roots, self.cfg, self.project_extensions, self.ext_paths)
                except Exception as e: self._reg.notes.append(f'extension loading failed: {agent_err(e)}')
        return self._reg

    @property
    def subagent_budget(self):
        "What the sub-agent model can afford; usually not the turn model's."
        spec = self.spec_or_none('subagent')
        if spec is None: return self.budget
        return budget_for(spec, self.tool_max_len, tool_channel(spec))

    def _sub_plain(self):
        "The tool list a sub-agent gets, sized to the model sub-agents run on."
        b = self.subagent_budget
        if b == self.budget: return self._plain
        if self._subtools is None:
            self._subtools = tools_for(self.host, lambda: self.skills, list(self.registry.tools),
                                       mx=b.tool_max, drop=b.drop)
        return self._subtools

    def spec_or_none(self, job='turn'):
        "`job`'s model spec, or `None` when its name does not resolve to one."
        try: return self.routing.spec(job)
        except Exception: return None

    @property
    def budget(self):
        "What the turn model can afford to be told -- see `core.budget_for`."
        spec = self.spec_or_none()        # an unresolved name costs no tools and no channel
        return budget_for(spec, self.tool_max_len, tool_channel(spec))

    @property
    def tools(self):
        "Every tool the turn model can afford, built once and recorded. Rebuilt by `reload`."
        if self._tools is None:
            extra = list(self.registry.tools)
            if self.subagents:
                extra += subagent_tools(lambda: self._be_or_none('subagent'), self._sub_plain,
                                        lambda: self.skills, self._cloud_backend_or_none)
            extra += plan_tools(lambda: self.plan, save=self._save_plan)
            b = self.budget
            plain = tools_for(self.host, lambda: self.skills, extra, mx=b.tool_max, drop=b.drop,
                              get_spec=self.spec_or_none, on_media=self._drew)
            self._plain = plain
            self._tools = [self._record(t) for t in plain]
        return self._tools

    def reload(self):
        "Re-discover skills, extensions and tools. What a `/reload` command calls after editing them."
        self._skills = self._reg = self._tools = self._subtools = None
        for b in self._backends.values(): b.close()
        self._backends.clear()
        return self

    def refresh(self):
        "Re-discover skills, extensions and tools, and re-brief a running turn backend in place."
        self._skills = self._reg = self._tools = self._subtools = None
        spec = self.routing.spec('turn')
        b = self._backends.get((spec.backend, spec.model_id))
        if b is not None: b.refresh(self.system_prompt(), self.tools)
        return self

    def system_prompt(self):
        if self._sp: return self._sp
        if self._tools is None: self.tools
        # a skill body is 3k tokens of a 12k budget, and `read_skill` still reaches it
        inline = self.inline_skills if self.budget.inline else ()
        extra = ''
        if self.plan:
            extra = ('## Current plan\n\n' + self.plan.md() +
                     '\n\nWork the active todo; mark it done when finished; after a stop, '
                     'resume from the active item rather than rewriting the plan.')
        return system_prompt(self.host, self.skills, inline, tools=self._plain, extra=extra)

    # -- recording -----------------------------------------------------------
    def _record(self, f):
        "Wrap one tool so its call is logged and its damage is measurable."
        name = getattr(f, '__name__', '?')

        @functools.wraps(f)   # both backends build the tool schema from the real signature
        def wrapper(*a, **kw):
            args = _named(f, a, kw)
            self._tool_calls_turn += 1
            if self._tool_calls_turn > self.max_tool_calls:
                return ('Tool-call budget exhausted for this turn. Stop calling tools and '
                        'summarise the evidence and unfinished work now.')
            self.calls.append((name, args))
            meta = self._action_meta(name, args)
            act = self.activity.start(name, args, **meta)
            self.registry.fire('before_tool', self, name, args)
            if name in WRITE_TOOLS:   # first touch only: later edits are part of one change
                if (p := args.get('path')):
                    if p not in self.before: self.before[p] = self.host.text_at(p) or ''
                elif name == 'run_shell': self.snapshot_tree()
            try: out = f(*a, **kw)
            except NotImplementedError as e:   # a raise ends the turn; a readable failure does not
                self.activity.finish(act, agent_err(e), ok=False)
                return err(f'{name} is not available here', e)
            except Exception as e:
                self.activity.finish(act, agent_err(e), ok=False)
                raise
            self.activity.finish(act, out, ok=not failed(out))   # one spelling of failure, in one place
            self.registry.fire('after_tool', self, name, out)
            return out
        return wrapper

    def _action_meta(self, name, args):
        "Frontend-independent identity metadata for a call; applications may override."
        return {'turn_id': self.current_turn_id, 'branch_id': self.current_branch_id}

    def snapshot_tree(self):
        "Read the open folders once per turn, so `changes()` can tell what a shell command moved."
        if self._walked: return True
        try: paths = [str(p) for p in self.host.walk()]
        except Exception as e:
            self.host.note(f'cannot watch what commands change: {agent_err(e)}')
            return False
        tree, n = {}, 0
        for p in paths:
            if (text := self.host.text_at(p)) is None: continue
            n += len(text)
            if n > SHELL_SNAPSHOT:
                self.host.note(f'not watching what commands change: the open folders hold over '
                               f'{SHELL_SNAPSHOT // 1_000_000}MB of text')
                return False
            tree[p] = text
        for p, text in tree.items(): self.before.setdefault(p, text)
        self._walked = True
        return True

    def changes(self):
        "`{path: (before, after)}` for every file this turn's write tools actually moved."
        out = {}
        for p, was in self.before.items():
            now = self.host.text_at(p)
            if now is not None and now != was: out[p] = (was, now)
        if self._walked:
            # a command can also make files, which no earlier snapshot can hold
            try: paths = [str(p) for p in self.host.walk()]
            except Exception: paths = []
            for p in paths:
                if p in self.before: continue
                if (now := self.host.text_at(p)): out[p] = ('', now)
        return out

    # -- backends ------------------------------------------------------------
    def _be(self, job='turn'):
        "The backend for `job`, built on first use and shared by every job on the same model."
        spec = self.routing.spec(job)
        key = (spec.backend, spec.model_id)
        if key not in self._backends:
            is_turn = key == (lambda s: (s.backend, s.model_id))(self.routing.spec('turn'))
            # rishi defaults multimodal on, which builds encoders even for text-only bundles
            kw = {'multimodal': self.local_multimodal} if spec.runtime == 'litert' else {}
            if is_turn:
                kw.update(sp=self.system_prompt(), tools=self.tools, tool_max_len=self.tool_max_len,
                          approve=(self.approvals.gate if self.approvals is not None else None))
            self._backends[key] = make_backend(spec, **kw)
        return self._backends[key]

    def _be_or_none(self, job='turn'):
        "The backend for `job` if it can start, else None. What a tool asks, since a tool cannot raise usefully."
        try:
            b = self._be(job)
            return b if b.start() is not None else None
        except Exception: return None

    @property
    def backend(self): return self._be('turn')

    @property
    def chat(self):
        "The live chat object, or None. Kept for the frontends, which use it to cancel."
        return self._be('turn').chat

    @property
    def ready(self):
        "Whether the turn model is up. Asked of the backend rather than looked up in the cache."
        return self._be('turn').ready

    @property
    def busy(self): return self.lock.locked()

    @property
    def model(self): return self.routing.spec('turn')

    def start(self):
        "Build the turn backend, once. Returns it, or None with `note` explaining why not."
        b = self._be('turn')
        if b.start() is None:
            self.note = b.note
            return None
        # from the backend that is running, not from the routing table
        self.note = f'{model_note(b.spec)} · {len(self.tools)} tools'
        return b

    def retry(self):
        "Forget a previous failure, so a model that has since downloaded or been keyed is picked up."
        b = self._be('turn')
        b.retry()
        return self.start()

    def set_model(self, name, job='turn'):
        "Point `job` at `name`; a turn-model change carries the live conversation with it."
        if self.busy: raise RuntimeError('cannot change model while the assistant is working')
        previous = self.routing.spec(job)
        old = (previous.backend, previous.model_id)
        history = self._backends[old].snapshot_hist() if job == 'turn' and old in self._backends else []
        before = self.budget
        spec = self.routing.set(name, job)
        # tools and briefing are sized to the turn model, so rebuild before `_be` briefs one
        if job == 'turn' and self.budget != before: self._tools = None
        if job == 'subagent': self._subtools = None
        new = (spec.backend, spec.model_id)
        if job == 'turn' and new != old:
            self._be('turn').resume_hist(history)
        still_used = {(self.routing.spec(j).backend, self.routing.spec(j).model_id) for j in JOBS}
        if old not in still_used and old in self._backends:
            self._backends.pop(old).close()
        self.note = f'{job} → {model_note(spec)}'
        return spec

    def set_local_multimodal(self, enabled):
        "Choose whether newly loaded LiteRT engines include media encoders."
        enabled = bool(enabled)
        if enabled == self.local_multimodal: return enabled
        if self.busy: raise RuntimeError('cannot change local multimodal while the assistant is working')
        self.local_multimodal = enabled
        for key in [k for k in self._backends if k[0] == 'litert']:
            self._backends.pop(key).close()
        self.note = f'local multimodal {"on" if enabled else "off"}'
        return enabled

    def lend_model(self):
        "Lend this session's engine to a host that builds its own chats, as a factory."
        if getattr(self.host, 'mk_chat', 'none of its business') is not None: return False

        def mk(model=None, **kw):
            from rishi import Chat
            spec = self._spec_for(model)   # honour the name: a local-only ask must not go to the cloud
            if spec is None: return Chat(model, **kw)
            b = self._backends.get((spec.backend, spec.model_id))
            engine = getattr(getattr(b, 'chat', None), 'engine', None)
            shared = {'engine': engine} if spec.local and engine is not None else {}
            return Chat(spec.model_id, runtime=spec.runtime, ctx_limit=spec.ctx, **shared, **kw)
        self.host.mk_chat = mk
        return True

    def _spec_for(self, model=None):
        "The `ModelSpec` a lent factory should build on; `None` means the cheap jobs' model."
        if model:
            try: return self.routing._resolve(str(model))
            except Exception: return None   # never substituted for a name asked for by name
        b = self._be_or_none('oneshot')
        return None if b is None or b.chat is None else b.spec

    # -- standing interests --------------------------------------------------
    def poll_watches(self, force=False):
        "Fire whatever the host has due, in a daemon thread, at most every `poll_every` seconds."
        import time
        if not self.poll_every and not force: return None
        if self._poll_thread is not None and self._poll_thread.is_alive(): return self._poll_thread
        now = time.monotonic()
        if not force and self._polled and now - self._polled < self.poll_every: return None
        self._polled = now

        def run():
            try: r = self.host.poll() or {}
            except NotImplementedError: return           # no watches here; nothing to say about it
            except Exception as e: return self.host.note(f'could not poll watches: {agent_err(e)}')
            if r.get('ran'): self.host.note(f"{r['ran']} of {r.get('checked', 0)} watches fired; see memory_search")
        from fastcore.parallel import startthread
        self._poll_thread = startthread(run, daemon=True)
        self._poll_thread.name = 'ramabana-poll'
        return self._poll_thread

    # -- turns ---------------------------------------------------------------
    def _prepare(self, prompt):
        "Everything that happens before a message goes out: notices, hooks, and prospective compaction."
        self.before.clear()                    # `changes()` reports this turn, not the session
        self._drawn = []                       # pictures this turn's tools wrote, for the frontend
        self._walked = False
        self.turn_use = Usage()                # a failed turn cannot inherit the previous turn's cost
        self._tool_calls_turn = 0               # applies even when a native engine owns the loop
        self.turn_seq += 1
        self.current_turn_id = f'{self.session_id}:turn_{self.turn_seq:06d}'
        self.activity.mark(self.current_turn_id) # and so does `turn_md()`
        self.checkpoints[self.current_turn_id] = {'before': self._be('turn').snapshot_hist(),
                                                  'branch_id': self.current_branch_id}
        # each checkpoint is a whole conversation, so the dict stays bounded
        for old in list(self.checkpoints)[:-MAX_CHECKPOINTS]: self.checkpoints.pop(old, None)
        self.registry.fire('before_turn', self, prompt)
        self.poll_watches()
        outgoing = _with_notices(prompt) if self.instruction_style == 'aai' else prompt
        request = request_text(prompt)
        requested, loaded = prompt_directives(request, self.tools, self.skills)
        route, plan = tool_plan(request)
        if requested:
            route = 'explicit'
            names = ', '.join(dict.fromkeys(name for name, _ in requested))
            plan = f'The user explicitly selected these tools: {names}. Use them before completing the task.'
        self._turn_plan = {'route': route, 'text': plan,
                           'tools': [name for name, _ in requested],
                           'skills': [skill.name for skill in loaded]}
        # planning has teeth: safe query tools run before generation, so the model gets evidence
        preflights = []
        first = {'repo': 'search_code', 'web': 'web_search'}.get(route)
        if first: preflights.append((first, request))
        eager = {'search_code', 'web_search', 'research', 'memory_search', 'list_files'}
        preflights += [(name, query or request) for name, query in requested if name in eager]
        by_name = {getattr(t, '__name__', ''): t for t in self.tools}
        outgoing = _append(outgoing, f'\n\n<tool-plan route="{route}">{plan}</tool-plan>')
        if tool_channel(self.spec_or_none()) == 'tags': outgoing = _append(outgoing, OUTPUT_CONTRACT)
        for name, query in dict.fromkeys(preflights):
            tool = by_name.get(name)
            if tool is None: continue
            try: evidence = tool(query)
            except Exception as e: evidence = f'{name} failed: {agent_err(e)}'
            outgoing = _append(outgoing, f'\n\n<preflight-tool name="{name}">\n{evidence}\n</preflight-tool>')
        for skill in loaded:
            outgoing = _append(outgoing, f'\n\n<requested-skill name="{skill.name}">\n{skill.text()}\n</requested-skill>')
        b = self._be('turn')
        # measure the pending message too: a pasted notebook can cross the limit in one turn
        if self.compactor.auto and (self.compactor.due(b) or not b.fits(outgoing)): self.compact()
        # only when the turn cannot fit; compaction cannot shrink the pending message
        if not b.fits(outgoing): outgoing = compact_notebook_context(outgoing, b.fits)
        if not b.fits(outgoing):
            projected = b.projected_tokens(outgoing)
            raise ValueError(f'input is too large for {b.spec.name}: about {projected:,} tokens '
                             f'with a {b.spec.ctx:,}-token context window')
        return outgoing

    @property
    def history_path(self):
        return None if self.cfg is None else self.cfg/f'{self.history_name}-history.jsonl'

    @property
    def plan_path(self):
        "Per-session plan file beside the history log."
        if self.cfg is None or not getattr(self, 'session_id', None): return None
        return self.cfg/f'{self.history_name}-plans'/f'{self.session_id}.json'

    def _load_plan(self):
        p = self.plan_path
        if p is None or not p.exists(): return
        try: self.plan = Plan.from_dict(json.loads(p.read_text()))
        except Exception: pass

    def _save_plan(self):
        p = self.plan_path
        if p is None: return
        try:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(json.dumps(self.plan.dict(), ensure_ascii=False, indent=2))
        except Exception: pass
        if self.on_plan:
            try: self.on_plan(self.plan)
            except Exception: pass

    def _load_history(self):
        p = self.history_path
        if p is None or not p.exists(): return
        try: self.history = [json.loads(line) for line in p.read_text().splitlines() if line.strip()][-2000:]
        except Exception: self.history = []

    def sessions(self):
        "Persisted conversations, newest first, with enough detail for a picker."
        grouped = {}
        for turn in self.history:
            sid = turn.get('session') or ''
            if not sid: continue
            grouped.setdefault(sid, []).append(turn)
        return [{'id': sid, 'turns': len(turns), 'at': turns[-1].get('at', 0),
                 'model': turns[-1].get('model', ''),
                 'title': str(turns[0].get('prompt', '')).replace('\n', ' ')[:72]}
                for sid, turns in sorted(grouped.items(), key=lambda x: x[1][-1].get('at', 0), reverse=True)]

    def resume_session(self, selector='latest'):
        "Resume a persisted conversation by full/prefix id, or the newest with `latest`."
        if self.busy: raise RuntimeError('cannot resume while the assistant is working')
        choices = self.sessions()
        if not choices: raise KeyError('no saved sessions; start the CLI with --cfg or use its default config')
        selector = (selector or 'latest').strip()
        if selector == 'latest': picked = choices[0]
        else:
            matches = [s for s in choices if s['id'] == selector or s['id'].startswith(selector)]
            if len(matches) != 1: raise KeyError(f'session {selector!r} matched {len(matches)} conversations')
            picked = matches[0]
        turns = [t for t in self.history if t.get('session') == picked['id']]
        canonical = []
        for turn in turns:
            canonical.append({'role': 'user', 'content': str(turn.get('prompt', ''))})
            if turn.get('reply'): canonical.append({'role': 'assistant', 'content': str(turn['reply'])})
        if picked['model']: self.set_model(picked['model'])
        self._be('turn').resume_hist(canonical)
        self.session_id = picked['id']
        self.plan = Plan()
        self._load_plan()
        bit = f" · plan {self.plan.line()}" if self.plan else ''
        self.note = f"resumed {picked['id']} · {picked['turns']} turns · {picked['model']}{bit}"
        return picked

    def _remember(self, prompt, text, error=''):
        turn = {'at': time.time(), 'session': getattr(self, 'session_id', '') or '',
                'turn_id': self.current_turn_id, 'branch_id': self.current_branch_id,
                'model': self._be('turn').spec.name,
                'prompt': str(prompt), 'reply': text, 'error': error,
                'plan': dict(getattr(self, '_turn_plan', {})),
                'usage': self.turn_use.dict(), 'usage_label': repr(self.turn_use),
                'activity': self.activity.rows(mark=self.activity._mark)}
        self.history.append(turn)
        del self.history[:-2000]
        if (p := self.history_path) is not None:
            try:
                p.parent.mkdir(parents=True, exist_ok=True)
                with p.open('a') as f: f.write(json.dumps(turn, ensure_ascii=False) + '\n')
            except Exception: pass

    def _finish(self, text, prompt=''):
        b = self._be('turn')
        # a backend counts cumulatively, so fold in each backend's delta
        turn_use = Usage(model=b.use.model)
        backends = list(self._backends.items())
        if all(backend is not b for _, backend in backends):
            backends.append(((b.spec.backend, b.spec.model_id), b))
        for key, backend in backends:
            previous = self._usage_seen.get(key, Usage(model=backend.use.model))
            turn_use = turn_use + (backend.use - previous)
            self._usage_seen[key] = Usage(**backend.use.dict())
        turn_use.model = b.use.model or b.spec.model_id   # the foreground model is the label
        self.turn_use = turn_use
        self.use = self.use + turn_use
        self.registry.fire('after_turn', self, text)
        if self.current_turn_id in self.checkpoints: self.checkpoints[self.current_turn_id]['after'] = b.snapshot_hist()
        self._remember(prompt, text)
        return text

    def ask(self, prompt, **kw):
        "One turn. Returns the assistant's text, or the reason there isn't any."
        if self.start() is None: return self.note
        with self.lock:
            try:
                outgoing = self._prepare(prompt)
                return self._finish(self._be('turn').send(outgoing, **kw), prompt)
            except Exception as e:
                self.note = f'the assistant failed ({agent_err(e)})'
                self._remember(prompt, self.note, agent_err(e))
                return self.note

    def stream(self, prompt, **kw):
        "One turn as an iterator of markdown chunks, for a frontend that can render as it arrives."
        if self.start() is None:
            yield self.note
            return
        with self.lock:
            try:
                outgoing = self._prepare(prompt)
                out = []
                for chunk in self._be('turn').stream(outgoing, **kw):
                    out.append(chunk)
                    yield chunk
                self._finish(''.join(out), prompt)
            except Exception as e:
                self.note = f'the assistant failed ({agent_err(e)})'
                self._remember(prompt, self.note, agent_err(e))
                yield f'\n\n{self.note}'

    def compose(self, prompt, context='', screen='', image=None, context_path=''):
        "One message from what the frontend can supply: the notebook, the screen as text, the screen as a picture."
        parts = []
        # a text-only LiteRT engine cannot accept image parts, so leave a truthful marker
        local_text_only = bool(image) and self.model.runtime == 'litert' and not self.local_multimodal
        if local_text_only: parts.append('[Image attachment omitted: local multimodal is disabled.]')
        if context:
            # the path is operational context: without it a small model invents one
            attr = f' path="{context_path}"' if context_path else ''
            parts.append(f'<notebook{attr}>\n{context}\n</notebook>')
        if screen: parts.append(f'<screen>\n{screen}\n</screen>')
        parts.append(f'<user-request>\n{prompt}\n</user-request>')
        ask = '\n\n'.join(parts)
        if not image or local_text_only: return ask
        media = list(image) if isinstance(image, (list, tuple)) else [image]
        return [*media, ask]

    def ask_with(self, prompt, context='', screen='', image=None, context_path='', **kw):
        "One turn with the frontend's context attached. Blocking; see `stream_with` for the live one."
        return self.ask(self.compose(prompt, context, screen, image, context_path), **kw)

    def stream_with(self, prompt, context='', screen='', image=None, context_path='', **kw):
        "The same turn, as an iterator of markdown chunks."
        return self.stream(self.compose(prompt, context, screen, image, context_path), **kw)

    def cancel(self):
        "Stop the turn in flight, and release anyone waiting on an approval for it."
        if self.approvals is not None: self.approvals.cancel_all('the turn was stopped')
        return bool(self._be('turn').cancel())

    def close(self):
        for b in list(self._backends.values()):
            try: b.close()
            except Exception: pass
        self._backends.clear()

    def fork(self, turn_id, stage='after', branch_id=''):
        "Fork model context from a captured turn boundary and make it active."
        cp = self.checkpoints.get(str(turn_id))
        if cp is None or stage not in cp: raise KeyError(f'no {stage} checkpoint for {turn_id}')
        branch_id = branch_id or f'branch_{uuid.uuid4().hex[:8]}'
        self._be('turn').restore_hist(cp[stage])
        self.current_branch_id = branch_id
        return {'branch_id': branch_id, 'parent_turn_id': str(turn_id), 'stage': stage}

    def revise(self, turn_id, text, branch_id=''):
        "Fork after a turn and replace its prose response with a user-authored revision."
        branch = self.fork(turn_id, 'after', branch_id)
        self._be('turn').revise_last_assistant(text)
        branch['revision'] = str(text)
        return branch

    # -- the cheap jobs ------------------------------------------------------
    def oneshot(self, prompt, sp='', job='oneshot', max_tokens=None):
        "A question on whichever model `job` routes to, in a conversation that is thrown away."
        b = self._be_or_none(job)
        return '' if b is None else b.oneshot(prompt, sp, max_tokens)

    def classify(self, text, labels):
        "One label for `text`, on the cheap model. Returns the matched label, or the raw reply."
        out = self.oneshot(f'{text}\n\nChoose exactly one label from: {", ".join(labels)}.',
                           'Reply with only the single best label and nothing else.', 'classify', 32).lower()
        return next((l for l in labels if l.lower() in out), out.strip())

    def summarise(self, text, sp='Summarise concisely. Output only the summary.'):
        return self.oneshot(text, sp, 'summary')

    def compact(self, extra=''):
        "Compact the conversation now. Returns the summary text, or `''` with `compactor.note` set."
        b = self._be('turn')
        if b.chat is None:
            self.compactor.note = 'nothing to compact: the model is not running'
            return ''
        sub = self._be_or_none('summary')
        summary_backend = sub if sub is not None else b
        # derived from the model actually used: a 4k model cannot reserve 4k output tokens
        summary_output = min(1024, max(256, summary_backend.spec.ctx // 4))
        summariser = summary_backend.oneshot
        text = self.compactor.compact(
            b, lambda p, sp: summariser(p, sp, summary_output), extra,
            summary_ctx=summary_backend.spec.ctx, summary_output=summary_output,
            summary_count=summary_backend.count_tokens)
        if text: self.registry.fire('compact', self, text)
        self.note = self.compactor.note
        return text

    # -- what to show --------------------------------------------------------
    @property
    def pct_full(self):
        try: return self._be('turn').pct_full
        except Exception: return 0.0

    @property
    def context_used(self):
        try: return self._be('turn').used_tokens
        except Exception: return 0

    def turn_md(self, title='what I did'):
        "This turn's tool calls as foldable markdown, to save alongside the answer in a cell."
        return self.activity.md(mark=self.activity._mark, title=title)

    def turn_lines(self):
        "This turn's tool calls as plain summary lines, for a pane that cannot fold."
        return self.activity.lines(mark=self.activity._mark)

    @property
    def problems(self):
        "Everything that went wrong and had nowhere to be reported, newest last."
        out = []
        for b in self._backends.values():
            for p in b.problems:
                if p not in out: out.append(p)
        if (n := self.compactor.note).startswith('compaction') and n not in out: out.append(n)
        return out[-10:]

    def clear_problems(self):
        "Forget them, for a frontend that has shown them."
        for b in self._backends.values(): b.problems.clear()
        return self

    def status(self):
        "Everything a status bar or an `/agent` command wants, in one dict."
        return {'ready': self.ready, 'busy': self.busy, 'note': self.note,
                'problems': self.problems,
                'model': self.model.name, 'model_note': model_note(self.model),
                'budget': self.budget.note, 'tool_budget': self.tool_budget, 'step_budget': self.step_budget,
                'tool_calls': self._tool_calls_turn, 'tool_limit': self.max_tool_calls, 'step_limit': self.max_steps,   # a tool withheld for a small window is invisible otherwise
                'ntools': len(self.tools), 'nskills': len(self.skills),
                'pct_full': round(self.pct_full, 3), 'compactions': self.compactor.count,
                'use': self.use.dict(), 'usage': repr(self.use),
                'plan': self.plan.dict(), 'plan_line': self.plan.line(),
                'activity': self.activity.rows(40),
                'approval': (self.approvals.pending.dict() if self.approvals is not None
                             and self.approvals.pending is not None else None),
                'calls': [{'tool': t, 'args': str(a)[:300]} for t, a in self.calls[-40:]]}

    def command(self, line):
        "Run a slash command. Returns text to show, or None when the command is unknown."
        line = (line or '').strip().lstrip('/')
        name, _, arg = line.partition(' ')
        arg = arg.strip()
        if name == 'model':
            if not arg: return self.routing.summary()
            job, _, m = arg.partition(' ')
            try: return f'{model_note(self.set_model(m or job, job if m else "turn"))}'
            except Exception as e: return agent_err(e)
        if name == 'sessions':
            rows = self.sessions()
            if rows:
                return '\n'.join(f"{s['id']}  {s['turns']:>3} turns  {s['model']:<20} {s['title']}" for s in rows)
            where = str(self.history_path) if self.history_path is not None else '(history disabled: no cfg directory)'
            return f'no saved sessions in {where}; a session is saved after its first completed turn'
        if name == 'resume':
            try:
                s = self.resume_session(arg or 'latest')
                return f"resumed {s['id']} · {s['turns']} turns · {s['model']}"
            except Exception as e: return agent_err(e)
        if name == 'models':
            rows = available_models(include_legacy=arg.lower() in ('all', 'legacy'))
            if not rows: return 'no models available'
            width = max(len(r['value']) for r in rows)
            return '\n'.join(f"{'*' if r['value'] == self.model.name else ' '} {r['value']:<{width}}  {r['provider']:<12} {r['source']}" for r in rows)
        if name == 'cost': return repr(self.use)
        if name == 'compact':
            t = self.compact(arg)
            return f'{self.compactor.note}\n\n{t}' if t else self.compactor.note
        if name == 'skills':
            return '\n'.join(f'{s.name:16} {s.source:8} {s.description[:90]}' for s in self.skills) or 'no skills found'
        if name == 'skill': return clip(_skill_text(self.skills, arg))
        if name == 'tools': return '\n'.join(sorted(getattr(t, '__name__', '?') for t in self.tools))
        if name == 'extensions': return '\n'.join(self.registry.notes) or 'no extensions loaded'
        if name == 'reload':
            self.reload()
            return f'reloaded: {len(self.tools)} tools, {len(self.skills)} skills'
        if name in ('plan', 'todos'):
            if not arg: return self.plan.md()
            if arg.lower() in ('clear', 'reset', 'none'):
                self.plan.clear(); self._save_plan(); return 'plan cleared'
            if '|' in arg:
                title, _, rest = arg.partition('|')
                items = [x.strip() for x in rest.split('|') if x.strip()]
            else:
                lines = [ln.strip() for ln in arg.splitlines() if ln.strip()]
                title, items = (lines[0], lines[1:]) if lines else (arg, [])
            self.plan.set(title, items); self._save_plan()
            return self.plan.md()
        if name == 'todo':
            if not arg: return self.plan.md()
            head, _, rest = arg.partition(' ')
            rest = rest.strip()
            if self.plan.find(head) is not None and rest:
                status, _, note = rest.partition(' ')
                if status in TODO_STATUSES:
                    try: self.plan.update(head, status=status, note=note.strip() or None)
                    except Exception as e: return agent_err(e)
                    self._save_plan(); return self.plan.md()
            try: self.plan.add(arg)
            except Exception as e: return agent_err(e)
            self._save_plan(); return self.plan.md()
        if name in self.registry.commands:
            fn, _ = self.registry.commands[name]
            try: return fn(self, arg)
            except Exception as e: return agent_err(e)
        return None

    def commands(self):
        "Every command name, built-in and registered, for a help line or an autocomplete."
        return sorted({'model', 'models', 'sessions', 'resume', 'cost', 'compact', 'skills', 'skill', 'tools', 'extensions', 'reload',
                       'plan', 'todos', 'todo', *self.registry.commands})


# %% ../nbs/03_agent.ipynb #15c8df1f
@patch
def _drew(self: Agent, paths):
    "Record pictures a tool wrote this turn, so a frontend can show them."
    self._drawn = getattr(self, '_drawn', []) + list(paths)

@patch(as_prop=True)
def last_media(self: Agent):
    """Pictures from the newest turn, as `{'mime','data'}` dicts.

    Two routes produce one: the model returns the image on its response, or a tool writes a file
    and returns its path. A frontend cannot draw a filename, so both arrive here."""
    be = self._be('turn')
    m = next((m for m in reversed(list(be.hist if be else []))
              if isinstance(m, dict) and m.get('role') == 'assistant'), None)
    out = list((m or {}).get('media') or [])
    for p in getattr(self, '_drawn', []):
        p = Path(p)
        try: out.append({'mime': mime_for(p), 'data': p.read_bytes()})
        except OSError: pass
    return out

# %% ../nbs/03_agent.ipynb #821de023
def _named(f, a, kw=None):
    "Every argument as a dict, positional ones matched to their parameter names."
    kw = dict(kw or {})
    if not a: return kw
    try:
        import inspect
        return {**dict(zip(list(inspect.signature(f).parameters), a)), **kw}
    except Exception: return {**{'args': a}, **kw}


def _append(prompt, text):
    "Add `text` to a message that may be a list of content parts rather than a string."
    if not isinstance(prompt, (list, tuple)): return prompt + text
    parts = list(prompt)
    for i in range(len(parts) - 1, -1, -1):
        if isinstance(parts[i], str):
            parts[i] += text
            return parts
    return [*parts, text]


def _skill_text(skills, name):
    s = find(skills, name)
    return f'no skill matching {name!r}' if s is None else s.text()


def _with_notices(prompt):
    "Append the aai-coding style prompt notices, when the prompt earns any. Text prompts only."
    if not isinstance(prompt, str): return prompt
    return prompt + notices_block(prompt)

# %% ../nbs/03_agent.ipynb #8fd374fe
COMPLETE_SP = """You are a code completion engine inside an editor. You are given the code before \
the cursor in <before> and the code after it in <after>.

Reply with ONLY the code that belongs at the cursor. No explanation, no markdown fence, no \
repetition of <before> or <after>. Keep it short -- finish the current expression, statement or \
short block and stop. Match the surrounding indentation and style exactly. If nothing sensible \
belongs there, reply with nothing at all."""

MAX_COMPLETION_LINES = 4     # a suggestion longer than this is a guess about the design, not a completion
COMPLETION_TOKENS = 96
CTX_BEFORE, CTX_AFTER = 2000, 600   # chars of surrounding code sent as context


def _strip_echo(before, out):
    "Drop a re-emitted tail of `before` from the front of `out` -- models like to restate the line they continue."
    tail = before[-200:]
    for n in range(len(tail), 0, -1):
        if out.startswith(tail[-n:]): return out[n:]
    return out

# %% ../nbs/03_agent.ipynb #35da5eee
def _fence_tail(text):
    "What follows an *unterminated* fence, or None -- everything before the opener is prose."
    if '```' not in text: return None
    head, _, rest = text.rpartition('```')
    if '```' in head and head.count('```') % 2: return None   # a complete block: fenced_blocks has it
    return rest.partition('\n')[2] if '\n' in rest else ''


def _clean(text, before, max_lines):
    "A raw model reply as something safe to insert: fences off, prose off, echo off, `max_lines` long."
    from fastcore.xtras import fenced_blocks
    text = text or ''
    if (blocks := fenced_blocks(text)): out = blocks[-1][1]
    elif (tail := _fence_tail(text)) is not None: out = tail
    else: out = text
    out = _strip_echo(before, (out or '').strip('\n'))
    lines = out.split('\n')[:max_lines]
    while lines and not lines[-1].strip(): lines.pop()
    return '\n'.join(lines)

# %% ../nbs/03_agent.ipynb #d5db0743
class Completer:
    "Inline completion: the local model, a throwaway conversation, and only when asked for."

    def __init__(self, agent, max_lines=MAX_COMPLETION_LINES, max_tokens=COMPLETION_TOKENS):
        self.a, self.max_lines, self.max_tokens = agent, max_lines, max_tokens
        self.note = 'not asked yet'

    @property
    def ready(self):
        b = self.a._be_or_none('completion')
        return b is not None

    def _prompt(self, code, pos, lang, context=''):
        try: variables = self.a.host.list_vars()
        except Exception: variables = ''
        support = ''
        if context: support += f'<related_code>\n{context[-6000:]}\n</related_code>\n'
        if variables: support += f'<runtime_variables>\n{variables[:4000]}\n</runtime_variables>\n'
        # whatever the application pinned to completion; a host that keeps none has no `ws`
        try: memory = self.a.ws.agent_memory_context('completion', max_chars=6000)
        except Exception: memory = ''
        if memory: support += f'<user_memory>\n{memory}\n</user_memory>\n'
        return (f'Language: {lang}\n\n{support}<before>\n{code[:pos][-CTX_BEFORE:]}\n</before>\n'
                f'<after>\n{code[pos:][:CTX_AFTER]}\n</after>')

    def complete(self, code, pos, lang='python', context=''):
        "The text to insert at `pos` in `code`, or `''` with `note` saying why there isn't any."
        b = self.a._be_or_none('completion')
        if b is None:
            self.note = 'no completion model available'
            return ''
        if b.busy:   # one engine, one generation: declining beats queueing behind a tool loop
            self.note = 'model busy -- it is mid-turn'
            return ''
        text = b.oneshot(self._prompt(code, pos, lang, context), COMPLETE_SP, self.max_tokens)
        if not text:
            self.note = b.note if not b.ready else 'no suggestion'
            return ''
        out = _clean(text, code[:pos], self.max_lines)
        self.note = f'{len(out.splitlines())} line(s) from {b.spec.name}' if out else 'no suggestion'
        return out

# %% ../nbs/03_agent.ipynb #0358c91a
@patch
def _cloud_backend_or_none(self:Agent, model):
    "A started remote backend for one delegated fan-out, without changing routing."
    try:
        spec = self.routing._resolve(str(model))
        if spec.local: return None
        key = (spec.backend, spec.model_id)
        if key not in self._backends: self._backends[key] = make_backend(spec)
        backend = self._backends[key]
        return backend if backend.start() is not None else None
    except Exception: return None


# %% ../nbs/03_agent.ipynb #46f071e0
_TOOL_MIN, _TOOL_MAX = 20, 400
_STEP_MIN, _STEP_MAX = 8, 80


def _limit(value, lo, hi, default):
    if str(value or '').lower() == 'auto': return 'auto'
    try: return max(lo, min(hi, int(value)))
    except (TypeError, ValueError): return default


def _auto_limits(prompt, continued=False):
    text = request_text(prompt).lower()
    score = int(continued) * 2 + sum(word in text for word in (
        'implement', 'build', 'fix', 'feature', 'test', 'verify', 'refactor', 'migration', 'continue'))
    if score >= 5: return 240, 60
    if score >= 2: return 160, 40
    if score: return 80, 20
    return 24, 8


_agent_init_limits = Agent.__init__
def _init_limits(self, *args, max_tool_calls='auto', max_steps='auto', **kwargs):
    _agent_init_limits(self, *args, **kwargs)
    self.tool_budget = _limit(max_tool_calls, _TOOL_MIN, _TOOL_MAX, 'auto')
    self.step_budget = _limit(max_steps, _STEP_MIN, _STEP_MAX, 'auto')
    self.max_tool_calls, self.max_steps = 80, 20
Agent.__init__ = _init_limits


_agent_prepare_limits = Agent._prepare
def _prepare_limits(self, prompt):
    continued = self._tool_calls_turn >= self.max_tool_calls
    auto_tools, auto_steps = _auto_limits(prompt, continued)
    self.max_tool_calls = auto_tools if self.tool_budget == 'auto' else self.tool_budget
    self.max_steps = auto_steps if self.step_budget == 'auto' else self.step_budget
    backend = self._be('turn')
    if hasattr(backend, 'max_steps'): backend.max_steps = self.max_steps
    return _agent_prepare_limits(self, prompt)
Agent._prepare = _prepare_limits


_agent_command_limits = Agent.command
def _command_limits(self, line):
    raw = (line or '').strip().lstrip('/')
    name, _, arg = raw.partition(' ')
    arg = arg.strip()
    if name in ('tool-budget', 'steps'):
        attr, lo, hi = ('tool_budget', _TOOL_MIN, _TOOL_MAX) if name == 'tool-budget' else ('step_budget', _STEP_MIN, _STEP_MAX)
        if arg:
            value = _limit(arg, lo, hi, getattr(self, attr))
            if value == getattr(self, attr) and str(arg).lower() != 'auto' and not str(arg).isdigit():
                return f'usage: /{name} [auto|{lo}..{hi}]'
            setattr(self, attr, value)
        value = getattr(self, attr)
        active = self.max_tool_calls if name == 'tool-budget' else self.max_steps
        return f'{name}: {value} (last turn: {active})'
    return _agent_command_limits(self, line)
Agent.command = _command_limits


_agent_commands_limits = Agent.commands
def _commands_limits(self): return sorted(set(_agent_commands_limits(self)) | {'tool-budget', 'steps'})
Agent.commands = _commands_limits

