"""Ramabana in a terminal: a transcript of blocks, a status bar, and one line to type in.

## Blocks and keys

Six kinds of block, one gutter each. The gutter glyph is also the click target, so folding
a tool result is a click on its dot -- which is the entire reason a tool result is a block
rather than part of the reply.

## The turn

`agent.stream` is a blocking generator on the model's thread, so its chunks come back over a
queue rather than being awaited. The loop has to stay free the entire time: an approval that
cannot be answered until the turn ends is not an approval, and a tool call that cannot
repaint until then is not a live feed.

## The surface

`Ui` is the whole terminal surface, and every method on it is synchronous and free of tty
work -- which is what lets the tests below drive it against an emulated terminal instead of
mocking one. The one hazard it has to handle is thread affinity: activity and approval
callbacks arrive on the model's worker thread, and a compositor may only be touched from the
loop thread, so everything they do goes through `_post`.

It carries three responsibilities: painting the tail (status bar plus input line), turning
tool calls and approval requests into blocks, and deciding what one keystroke means -- which
is either a coroutine for the caller to spawn, `'quit'`, or nothing.

## Folding

A block taller than `FOLD` is born folded, so a four-hundred-line file view costs one row
until it is asked for. Clicking its gutter toggles it; so does ctrl-O on the last block.

## Approvals in a terminal

The gate blocks the model's worker thread until a person answers, so the request arrives on
that thread and the answer comes from the loop. The input line becomes the answer: type a
reason, then `y`, `n`, or `a` for the rest of the session.

## Commands

Slash commands are answered by the agent, not by the terminal: there is one implementation of
`/model`, and it is not in a frontend. `/help` is the only one this layer owns, because the
keys it describes are this layer's.

## Running it

`mk_agent` is the assembly: a `LocalHost` over the folders named on the command line, an
`Agent` over that, and the approval gate wired to both. `amain` is the tty loop, and it is
short because everything it could get wrong lives in `Ui`.

One turn with no terminal at all, for a pipe or a script -- and the entry point itself, which
is `ramabana` on the command line.

Docs: https://vedicreader.github.io/ramabana/cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_cli.ipynb.

# %% auto #0
__all__ = ['GUTTERS', 'FOLD', 'HELP', 'run_turn', 'Ui', 'mk_agent', 'amain', 'ask_once', 'main']

# %% ../nbs/05_cli.ipynb #77060a68
import asyncio, sys, threading
from pathlib import Path
from rich.text import Text
from fastcore.script import call_parse
from teleprint.buffer import Buffer
from teleprint.compositor import Compositor
from teleprint.tty import RealTty
from .core import agent_err
from .tools import WRITE_TOOLS, LocalHost
from .agent import Agent, Approvals, answer_md

# %% ../nbs/05_cli.ipynb #6e18fa31
GUTTERS = {'user':  (Text('› ', style='bold cyan'), Text('  ')),
           'reply': (Text('  '),                    Text('  ')),
           'tool':  (Text('· ', style='dim'),        Text('  ')),
           'ask':   (Text('? ', style='bold yellow'), Text('  ')),
           'note':  (Text('! ', style='yellow'),     Text('  ')),
           'error': (Text('✗ ', style='bold red'),   Text('  '))}

FOLD = 12          # a block taller than this is born folded; click or ctrl-O to open it
HELP = """keys    enter send · ctrl+o fold the last block · ctrl+c stop the turn · ctrl+d quit
approve y approve · n refuse · a approve all · or type a reason and press enter to refuse
extra   /help, and every ramabana command: /model /cost /compact /skills /tools /reload"""

# %% ../nbs/05_cli.ipynb #07ecef35
async def run_turn(ui, prompt):
    """One turn, streamed into the transcript.

    The agent's `stream` is a blocking generator on the model's own thread, so the chunks
    come back over a queue rather than being awaited: the loop has to stay free the whole
    time, or an approval could never be answered and a tool call could never repaint.
    """
    loop, q = asyncio.get_running_loop(), asyncio.Queue()
    def pump():
        try:
            for chunk in ui.agent.stream(prompt): loop.call_soon_threadsafe(q.put_nowait, chunk)
        except Exception as e: loop.call_soon_threadsafe(q.put_nowait, agent_err(e))
        finally: loop.call_soon_threadsafe(q.put_nowait, None)
    threading.Thread(target=pump, daemon=True).start()
    blk = None
    try:
        while (chunk := await q.get()) is not None: blk = ui.stream(blk, chunk)
    finally:
        ui.turn = None
        for p in ui.agent.problems: ui.say(Text(p), 'error')
        ui.agent.clear_problems()
        ui.paint()
    return blk

# %% ../nbs/05_cli.ipynb #2874a64d
class Ui:
    """The terminal surface: a transcript of blocks, a status bar, and one line to type in.

    Every method here is synchronous and free of tty work, so the whole surface can be
    driven in a test against an emulated terminal -- which is why the async loop below is
    as small as it is.

    Callbacks arrive from the model's worker thread (`Activity.on_change`, `Approvals`), and
    a compositor may only be touched from the loop thread, so everything they do goes
    through `_post`. Without a loop registered it calls straight through, which is what
    makes the synchronous tests possible.
    """

    def __init__(self, comp, agent, loop=None):
        self.comp, self.agent, self.loop = comp, agent, loop
        self.buf = Buffer()
        self.ask = None            # the `Ask` waiting on an answer, or None
        self.turn = None           # the running turn's task, or None
        self.acts = {}             # act id -> its block
        self.hint = ''
        self._reply = ''           # the reply text so far, so a streamed block repaints whole
        agent.activity.on_change = self.on_act
        if agent.approvals is not None: agent.approvals.listen(self.on_ask, self.on_answer)

    def _post(self, fn, *a):
        "Run `fn` on the loop thread, or now when there is no loop (a test, or startup)."
        if self.loop is None: return fn(*a)
        self.loop.call_soon_threadsafe(fn, *a)

    # -- the tail ------------------------------------------------------------
    def status(self):
        "The status bar: what is loaded, how full it is, and what it has cost so far."
        s = self.agent.status()
        state = 'working' if s['busy'] else ('ready' if s['ready'] else 'idle')
        bits = [f"{s['model']}", state, f"{s['ntools']} tools", f"{s['nskills']} skills",
                f"{round(s['pct_full'] * 100)}% ctx"]
        if s['compactions']: bits.append(f"{s['compactions']} compaction(s)")
        if self.agent.use.total: bits.append(s['usage'])
        if s['problems']: bits.append(f"{len(s['problems'])} problem(s)")
        return Text(' ' + ' · '.join(bits), style='reverse')

    #: The approval prompt. `y`/`n`/`a` answer only while nothing is typed, because a reason
    #: like "put it in docs/ instead" contains all three letters -- so once there is text, the
    #: letters are text and `enter` is the answer.
    ASKING = 'approve? [y/n/a, or a reason + enter] '

    def prompt(self):
        "The input line: an approval question when one is pending, otherwise the prompt."
        if self.ask is not None:
            return Text(self.ASKING, style='bold yellow') + Text(self.buf.text)
        return Text('› ', style='bold cyan') + Text(self.buf.text)

    def paint(self):
        pre = self.ASKING if self.ask is not None else '› '
        tail = [self.status()] + ([Text(self.hint, style='dim')] if self.hint else []) + [self.prompt()]
        self.comp.set_tail(*tail, cursor=(len(tail) - 1, self.buf.cell_cursor(pre)))

    # -- the transcript ------------------------------------------------------
    def say(self, body, kind='reply', fold=FOLD):
        "Print one block. Text is wrapped in `Text` so nothing in a model reply is read as markup."
        return self.comp.print_block(body if isinstance(body, Text) else Text(str(body)),
                                     gutter=GUTTERS.get(kind, GUTTERS['reply']),
                                     tag=kind, collapse_at=fold)

    def on_act(self, act):
        "Called twice per tool call, from the model's thread: once running, once finished."
        self._post(self._act, act)

    def _act(self, act):
        line = Text(act.line())
        blk = self.acts.get(act.id)
        if blk is None:
            self.acts[act.id] = self.say(line, 'tool')
            return self.paint()
        body = [line] if not act.detail else [line, Text(act.detail, style='dim')]
        self.comp.set_body(blk, *body)
        self.comp.refresh_block(blk)
        self.paint()

    # -- approvals -----------------------------------------------------------
    def on_ask(self, ask):
        "A write is waiting on a person. Print what it would do, and take over the input line."
        self._post(self._ask, ask)

    def _ask(self, ask):
        self.ask = ask
        self.buf.clear()
        self.say(Text(ask.summary, style='bold') + Text('\n\n') + Text(ask.preview), 'ask', fold=None)
        self.paint()

    def on_answer(self, ask):
        self._post(self._answered, ask)

    def _answered(self, ask):
        if self.ask is not None and self.ask.id == ask.id: self.ask = None
        self.say(Text(answer_md(ask).replace('**', '')), 'note')
        self.paint()

    def answer(self, ok, session=False):
        """Answer the pending request, using whatever has been typed as the reason.

        A refusal with a reason is the point of the gate: it reaches the model, which can
        change approach instead of retrying the same edit.
        """
        if self.ask is None: return None
        note, self.buf.text = self.buf.text.strip(), ''
        return self.agent.approvals.answer(self.ask.id, ok, note, session=session)

    # -- input ---------------------------------------------------------------
    def submit(self):
        """Handle the typed line. Returns a coroutine for a turn, or None when it was handled here.

        Slash commands are answered by the agent, so every command the IDE has works here
        too -- there is one implementation of `/model`, and it is not in a frontend.
        """
        line = self.buf.text.strip()
        self.buf.clear()
        if not line: return None
        self.say(Text(line), 'user')
        if line in ('/help', '/?'):
            self.say(Text(HELP), 'note', fold=None)
            return None
        if line.startswith('/'):
            out = self.agent.command(line)
            self.say(Text(out) if out is not None else Text(f'unknown command: {line}'),
                     'note' if out is not None else 'error', fold=None)
            return None
        return run_turn(self, line)

    def on_key(self, k):
        "One keystroke. Returns a coroutine to spawn, `'quit'`, or None."
        if self.ask is not None:
            bare = not self.buf.text.strip()
            if bare and k.name in ('y', 'Y'):     self.answer(True)
            elif bare and k.name in ('n', 'N'):   self.answer(False)
            elif bare and k.name in ('a', 'A'):   self.answer(True, session=True)
            elif k.name == 'enter':               self.answer(False)   # a typed reason is a refusal
            elif k.name == 'ctrl+y':              self.answer(True)    # ...unless approved with it as guidance
            elif k.name == 'ctrl+c':              self.answer(False)     # stopping the turn refuses what it was waiting on
            else: self.buf.handle(k)
            return self.paint()
        if k.name == 'ctrl+d' and not self.buf.text: return 'quit'
        if k.name == 'ctrl+c':
            if self.turn is not None:
                self.agent.cancel()
                self.turn.cancel()
                self.turn = None
                self.say(Text('stopped'), 'note')
            self.buf.clear()
            return self.paint()
        if k.name == 'enter':
            coro = self.submit()
            self.paint()
            return coro
        if k.name == 'ctrl+o':
            live = [b for b in self.comp.blocks.values() if not b.committed and b.height > 1]
            if live: self.comp.toggle(live[-1])
            return self.paint()
        self.buf.handle(k)
        self.paint()

    def stream(self, blk, chunk):
        """Grow the reply as the model produces it, repainting the block from its whole text.

        Not `Compositor.extend`, for two reasons: each extend appends at least one row, so a
        token stream would print one word per line; and a tool call that starts mid-reply
        makes the reply no longer the last block, which extend refuses. Repainting from the
        accumulated text is correct under both, and a reply is small enough to repaint.
        """
        self._reply = (self._reply + chunk) if blk is not None else chunk
        if blk is None: return self.say(Text(self._reply), 'reply', fold=None)
        self.comp.set_body(blk, Text(self._reply))
        self.comp.refresh_block(blk)
        return blk

# %% ../nbs/05_cli.ipynb #79b1ca2e
def mk_agent(roots=('.',), model=None, approve='ask', web=True, **kw):
    "A `LocalHost` and an `Agent` over it, gated the way `approve` says."
    approvals = None if approve == 'none' else Approvals(tools=WRITE_TOOLS, mode=approve)
    host = LocalHost(roots, approvals=approvals, web=web)
    return Agent(host, model=model, approvals=approvals, **kw), host

# %% ../nbs/05_cli.ipynb #ccb8ca7b
async def amain(agent, hint=''):
    "The tty loop: one terminal, one event loop, one place that owns the keyboard."
    tty = RealTty()
    tty.write('\x1b[?1000;1006h\x1b[?2004h')     # SGR mouse (clicks fold blocks) + bracketed paste
    done = asyncio.Event()
    try:
        comp = await Compositor(tty).start()
        ui = Ui(comp, agent, loop=asyncio.get_running_loop())
        ui.hint = hint
        comp.on_task_error = lambda e, t: ui.say(Text(f'{t.get_name()} failed: {e!r}'), 'error')
        def on_key(k):
            out = ui.on_key(k)
            if out == 'quit': return done.set()
            if out is not None:
                ui.turn = comp.spawn(out, name='turn')
                ui.paint()
        comp.on_key = on_key
        comp.on_paste = lambda text: (ui.buf.insert(text), ui.paint())
        comp.on_resize = lambda: (comp.resize(), ui.paint())
        comp.on_click = lambda blk: comp.toggle(blk)
        ui.say(Text(f'ramabana · {agent.note}\n{HELP}'), 'note', fold=None)
        ui.paint()
        loop = asyncio.get_running_loop()
        loop.add_reader(tty.fd, lambda: comp.on_bytes(tty.read(timeout=0)))
        try:
            while not done.is_set():          # the key parser needs periodic flushes (esc disambiguation)
                try: await asyncio.wait_for(done.wait(), 0.2)
                except asyncio.TimeoutError: comp.flush_input()
        finally:
            loop.remove_reader(tty.fd)
            comp.stop()
    finally:
        tty.write('\x1b[?2004l\x1b[?1000;1006l\r\n')
        tty.restore()
        agent.close()

# %% ../nbs/05_cli.ipynb #b6d74293
def ask_once(agent, prompt):
    "One turn with no terminal at all, for a pipe or a script. Returns the exit code."
    print(agent.ask(prompt))
    for p in agent.problems: print(f'! {p}', file=sys.stderr)
    agent.close()
    return 0 if agent.ready else 1

# %% ../nbs/05_cli.ipynb #ce629efa
@call_parse
def main(
    prompt: str = '',                    # run one turn and exit; omit for the interactive session
    root: str = '.',                     # folders the agent may touch, comma separated
    model: str = None,                   # the turn model; the routing default when omitted
    approve: str = 'ask',                # ask | auto | off | none (gate nothing at all)
    web: bool = True,                    # let the web tools reach the network through fossick
    cfg: str = None,                     # config dir, for skills, extensions and history
):
    "Ramabana in a terminal: a coding agent over the folders you name."
    roots = [r.strip() for r in str(root).split(',') if r.strip()]
    agent, host = mk_agent(roots, model=model, approve=approve, web=web,
                           cfg=Path(cfg).expanduser() if cfg else None)
    if agent.start() is None and not prompt:
        print(f'no model available: {agent.note}', file=sys.stderr)
    if prompt: return sys.exit(ask_once(agent, prompt))
    hint = f"{', '.join(host.roots)} · /help"
    try: asyncio.run(amain(agent, hint))
    except KeyboardInterrupt: pass
