"""The error type, the environment convention, and the one place that decides which model runs what.

Docs: https://vedicreader.github.io/ramabana/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ENV_PREFIX', 'ENV_FALLBACK', 'JOBS', 'ONESHOT_JOBS', 'LOCAL', 'MLX', 'LLAMA', 'GPT', 'CLOUD', 'CLAUDE_MODELS',
           'CLAUDE', 'CLAUDE_ALIASES', 'DFLT_AGENT_CTX', 'RUNTIMES', 'AGENTS', 'HOSTED', 'COPILOT_UNAVAILABLE',
           'CUSTOM', 'MODELS', 'DFLT_LOCAL', 'completer', 'cheap', 'DEFAULT_POLICY', 'DFLT_LOCAL_CTX', 'PREFIXES',
           'RETIRED', 'SMALL_CTX', 'TOOL_MAX_FLOOR', 'FRUGAL_DROP', 'TAGS_SCHEMA_TOKENS', 'TOOL_CHANNELS', 'AgentError',
           'agent_err', 'use_env_prefix', 'env', 'runtime_available', 'auth_status', 'copilot_catalog',
           'available_models', 'local_ctx', 'ModelSpec', 'unknown_model', 'resolve', 'spec_caps', 'accepts',
           'model_note', 'Budget', 'budget_for', 'register_model', 'unregister_model', 'force_tags',
           'forget_forced_tags', 'tool_channel', 'Routing']

# %% ../nbs/00_core.ipynb #41a0b203
import difflib, functools, importlib, importlib.util, json, os, platform, re, shutil, subprocess, sys, time
from fastcore.all import Path
from dataclasses import dataclass, field

# %% ../nbs/00_core.ipynb #2049138c
ENV_PREFIX, ENV_FALLBACK = 'RAMABANA_', 'LEELA_'

class AgentError(Exception):
    "Something the harness refuses to do, rather than a failure while doing it."

def agent_err(e):
    "A caught exception for a user-facing harness surface."
    return f'{type(e).__name__}: {e}'

def use_env_prefix(prefix, fallback=None):
    """Name the environment variables this application reads, most specific first.
    `use_env_prefix('LEELA_', 'RAMABANA_')`
    """
    global ENV_PREFIX, ENV_FALLBACK
    ENV_PREFIX = prefix if prefix.endswith('_') else prefix + '_'
    if fallback is not None: ENV_FALLBACK = fallback if fallback.endswith('_') else fallback + '_'
    return ENV_PREFIX, ENV_FALLBACK


def env(name, dflt=None):
    "`$<prefix><name>`, then `$<fallback><name>`, then `dflt`. See `use_env_prefix`."
    return os.environ.get(ENV_PREFIX+name) or os.environ.get(ENV_FALLBACK+name) or dflt

# %% ../nbs/00_core.ipynb #9df3b26a
JOBS = ('turn', 'oneshot', 'inline', 'completion', 'classify', 'summary', 'subagent')

#: One-shot jobs share the `oneshot` policy unless set individually. Not `turn` or `subagent`.
ONESHOT_JOBS = ('oneshot', 'completion', 'classify', 'summary', 'inline')
LOCAL = {'gemma-e2b': 'litert-community/gemma-4-E2B-it-litert-lm',
    'gemma-e4b': 'litert-community/gemma-4-E4B-it-litert-lm',
    'gemma-12b': 'litert-community/gemma-4-12B-it-litert-lm'}
MLX = {'qwen-4b': 'mlx-community/Qwen3.5-4B-MLX-4bit',
       'mini-coder-4b': 'mlx-community/mini-coder-4b-OptiQ-4bit',
       'ornith-9b': 'mlx-community/Ornith-1.0-9B-8bit'}
LLAMA = {'llama-qwen-0.6b': 'Qwen/Qwen3-0.6B-GGUF',
         'llama-qwen-1.7b': 'Qwen/Qwen3-1.7B-GGUF',
         'llama-qwen-4b': 'Qwen/Qwen3-4B-GGUF'}

GPT = {name: f'openai/{name}' for name in (
    'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano',
    'gpt-5.4', 'gpt-5.4-mini', 'gpt-5.6', 'gpt-5.6-luna', 'gpt-5.6-sol', 'gpt-5.6-terra')}
GPT.update({name: f'codex/{name}' for name in (
    'gpt-5.3-codex-spark', 'gpt-5.5')})
CLOUD = {**GPT, 'gpt': GPT['gpt-5.6-terra'],
    'gpt-mini': GPT['gpt-5.6-luna'], 'gpt-sol': GPT['gpt-5.6-sol']}

#: Claude Code's catalogue, prefixed the same way and for the same reason
CLAUDE_MODELS = ('claude-opus-5', 'claude-sonnet-5', 'claude-haiku-4-5', 'claude-fable-5',
                 'claude-opus-4-8', 'claude-sonnet-4-6', 'claude-sonnet-4-5', 'claude-opus-4-6')
CLAUDE = {f'claude/{mid}': mid for mid in CLAUDE_MODELS}

#: The same models under their bare names and the short aliases.
CLAUDE_ALIASES = {**{mid: mid for mid in CLAUDE_MODELS},
                  'sonnet': 'claude-sonnet-5', 'opus': 'claude-opus-5', 'fable': 'claude-fable-5'}

DFLT_AGENT_CTX = 128_000
RUNTIMES = ('litert', 'mlx', 'llama', 'claude', 'copilot', 'remote')
AGENTS = ('claude',)
HOSTED = ('remote', 'copilot', *AGENTS)
COPILOT_UNAVAILABLE = ('copilot runtime is unavailable; install rishi[copilot], then sign in to '
    'Copilot in an editor or run `python -c "from rishi.copilot import copilot_login; copilot_login()"`')
CUSTOM = {}
_RUNTIME_DEPS = {'litert': 'litert_lm', 'mlx': 'mlx_lm', 'llama': 'llama_cpp'}

def _harness_available(mod, binary):
    "Whether an agent harness can be reached at all: its SDK, or the binary it drives."
    try: m = importlib.import_module(mod)
    except Exception: return False
    try:
        if m.sdk_available(): return True
    except Exception: pass
    try: return bool(getattr(m, binary)())
    except Exception: return False

def _claude_available(): return _harness_available('rishi.claude', 'claude_bin')

def _copilot_available():
    """Whether Copilot can be reached: rishi imports it, and a GitHub OAuth token is on hand to
    exchange. Reads the environment and the editor config files, and never the network."""
    try:
        m = importlib.import_module('rishi.copilot')
        return bool(m.copilot_oauth())
    except Exception: return False

def runtime_available(runtime):
    "Whether Rishi's optional dependency for `runtime` can be reached. Never raises."
    if runtime == 'remote': return True
    if runtime == 'claude': return _claude_available()
    if runtime == 'copilot': return _copilot_available()
    try: return importlib.util.find_spec(_RUNTIME_DEPS[runtime]) is not None
    except (ImportError, KeyError, ValueError): return False

MODELS = {**{k: ('litert', v) for k, v in LOCAL.items()},
          **{k: ('mlx', v) for k, v in MLX.items()},
          **{k: ('llama', v) for k, v in LLAMA.items()},
          **{k: ('claude', v) for k, v in {**CLAUDE, **CLAUDE_ALIASES}.items()},
          **{k: ('remote', v) for k, v in CLOUD.items()}}

# %% ../nbs/00_core.ipynb #9881cc3b
def _json_has(path, *keys):
    "Whether nested keys in a JSON file are present and truthy."
    try:
        from fastcore.basics import nested_idx
        return bool(nested_idx(Path(path).expanduser().read_json(), *keys))
    except Exception: return False

def _claude_login():
    "Only status metadata. Credentials never leave Claude Code or enter Leela."
    if not shutil.which('claude'): return False
    try:
        p = subprocess.run(['claude', 'auth', 'status', '--json'], capture_output=True, text=True, timeout=3)
        return p.returncode == 0 and bool(json.loads(p.stdout).get('loggedIn'))
    except Exception: return False


def auth_status():
    'Credential sources FastLLM can use, without reading or returning any secret.'
    codex = bool(os.getenv('CODEX_AUTH_TOKEN') or _json_has(os.getenv('CODEX_AUTH_PATH', '~/.codex/auth.json'), 'tokens', 'access_token'))
    claude_login = _claude_login() and _claude_available()
    copilot = _copilot_available()
    return {
        'openai': {'available': bool(os.getenv('OPENAI_API_KEY')), 'source': 'OPENAI_API_KEY'},
        'codex': {'available': codex, 'source': 'Codex login' if codex else ''},
        'anthropic': {'available': bool(os.getenv('ANTHROPIC_API_KEY')), 'source': 'ANTHROPIC_API_KEY'},
        'claude': {'available': claude_login,
                   'source': 'Claude Code login' if claude_login else ''},
        'gemini': {'available': bool(os.getenv('GEMINI_API_KEY')), 'source': 'GEMINI_API_KEY'},
        'copilot': {'available': copilot,
                    'source': 'GitHub Copilot sign-in' if copilot else ''},
    }

# %% ../nbs/00_core.ipynb #56303cec
_oai_cache = (0.0, [])
def _openai_models(include_legacy=False):
    "Canonical models the current OpenAI key can list. Older coding models are opt-in."
    global _oai_cache
    ids = _oai_cache[1] if (time.time() - _oai_cache[0]) < 300 else None
    if not (key := os.getenv('OPENAI_API_KEY')): return []
    if ids is None:
        try:
            import httpx2 as httpx
            r = httpx.get('https://api.openai.com/v1/models', headers={'Authorization': f'Bearer {key}'}, timeout=10)
            r.raise_for_status()
            ids = [x.get('id', '') for x in r.json().get('data', [])]
        except Exception: ids = []
        _oai_cache = (time.time(), ids)
    current = re.compile(r'^(?:gpt-5(?:\.\d+)?(?:-(?:mini|nano|pro|codex(?:-mini|-max)?|chat-latest|search-api|[a-z]+))?|o[34](?:-mini|-pro)?)$')
    legacy = re.compile(r'^gpt-4\.1(?:-mini|-nano)?$')
    return sorted({x for x in ids if (current.match(x) or (include_legacy and legacy.match(x))) and not re.search(r'-20\d\d-', x)})

_copilot_cat = (0., {})
def copilot_catalog(ttl=300):
    "Copilot's catalogue for this account, cached: `{id: entry}`, or `{}` when it cannot be reached."
    global _copilot_cat
    if (time.time() - _copilot_cat[0]) < ttl: return _copilot_cat[1]
    try:
        from rishi.copilot import copilot_catalog as cat
        d = cat()
    except Exception: d = {}
    _copilot_cat = (time.time(), d)
    return d

def _copilot_chat_models():
    "Chat ids this Copilot plan can reach. Per-plan and it moves. It is asked for, never tabled."
    return [i for i, m in copilot_catalog().items()
            if (m.get('capabilities') or {}).get('type') == 'chat']

def available_models(include_legacy=False):
    "Models selectable here. Specialized older generations appear only when requested."
    rows = []
    for runtime, models in (('litert', LOCAL), ('mlx', MLX), ('llama', LLAMA)):
        if not runtime_available(runtime): continue
        rows += [{'value': name, 'label': name, 'provider': runtime,
                  'source': f'on device via Rishi {runtime}'} for name in models]
    if runtime_available('claude'):
        rows += [{'value': name, 'label': mid, 'provider': 'claude',
                  'source': 'Claude Code (CLI or SDK)'} for name, mid in CLAUDE.items()]
    if runtime_available('copilot'):
        for model in _copilot_chat_models():
            rows.append({'value': f'copilot/{model}', 'label': model, 'provider': 'copilot',
                         'source': 'GitHub Copilot subscription'})
    auth = auth_status()
    if auth['openai']['available']:
        for model in _openai_models(include_legacy):
            rows.append({'value': f'openai/{model}', 'label': model, 'provider': 'openai',
                         'source': auth['openai']['source']})
    try:
        from fastllm.types import model_info_registry
        vendors = ('openai', 'codex', 'gemini')
        for vendor in vendors:
            if not auth.get(vendor, {}).get('available'): continue
            for v, model in model_info_registry:
                if v != vendor: continue
                if not include_legacy and re.match(r'^gpt-4(?:\.|-|$)', model): continue
                rows.append({'value': f'{vendor}/{model}', 'label': model, 'provider': vendor,
                             'source': auth[vendor]['source']})
    except Exception: pass
    if auth['anthropic']['available']:
        catalog = set()
        try:
            from fastllm.types import model_info_registry
            catalog = {model for vendor, model in model_info_registry if vendor == 'anthropic' and model.startswith('claude-')}
        except Exception: pass
        catalog.update(model.split('/', 1)[1] for model in CLOUD.values() if model.startswith('anthropic/'))
        for model in sorted(catalog): rows.append({'value': f'anthropic/{model}', 'label': model,
                                                   'provider': 'anthropic', 'source': auth['anthropic']['source']})
    seen, out = set(), []
    for row in rows:
        if row['value'] in seen: continue
        seen.add(row['value']); out.append(row)
    return out

# %% ../nbs/00_core.ipynb #70d7dfa3
DFLT_LOCAL = 'gemma-e4b'
completer = DFLT_LOCAL
cheap = completer          # back-compat alias

#: `None` for the one-shot jobs, which is not "unset" but "whatever `oneshot` says" -- see
#: `Routing.name_for`. Spelling each of them out as the same constant meant the cheap model
#: could only be moved three times or not at all.
DEFAULT_POLICY = {'turn': None, 'oneshot': completer, 'inline': None, 'completion': None,
                  'classify': None, 'summary': None, 'subagent': DFLT_LOCAL}

_LOCAL_CTX = {'gemma-e2b': 16_384, 'gemma-e4b': 16_384, 'gemma-12b': 32_000,
              'qwen-4b': 32_768, 'mini-coder-4b': 32_768, 'ornith-9b': 32_768,
              'llama-qwen-0.6b': 32_768, 'llama-qwen-1.7b': 32_768, 'llama-qwen-4b': 32_768}
DFLT_LOCAL_CTX = 32_768


def local_ctx(name, dflt=DFLT_LOCAL_CTX):
    "The context window for a local model: `$LEELA_LOCAL_CTX` if it says, else the table."
    if (ovr := (env('LOCAL_CTX') or '').strip()):
        if ovr.isdigit(): return int(ovr)
        for part in ovr.split(','):
            k, _, v = part.partition(':')
            if k.strip() == name and v.strip().isdigit(): return int(v)
    return _LOCAL_CTX.get(name, dflt)

# %% ../nbs/00_core.ipynb #64093121
@dataclass(frozen=True)
class ModelSpec:
    'One model, resolved: which backend runs it, what to call it, and how big it is.'
    name: str                 # what the user types
    backend: str              # 'rishi' | 'fastllm'
    model_id: str             # what the backend is given
    ctx: int = 128_000        # context window in tokens
    note: str = ''            # anything worth showing about how this was resolved
    config: dict = field(default_factory=dict, compare=False) # runtime options. Never persisted secrets

    @property
    def runtime(self): return self.backend
    @property
    def local(self): return self.backend not in HOSTED
    def __str__(self): return f'{self.name} ({self.model_id})'

def _copilot_ctx(model_id):
    """Context window and a note for a Copilot model. Copilot reports its own. Nothing is guessed.
    Reads the entry here rather than through `rishi.copilot.copilot_ctx`: the catalogue is already
    in hand, and this then needs no rishi newer than the one that fetched it."""
    lim = ((copilot_catalog().get(model_id) or {}).get('capabilities') or {}).get('limits') or {}
    if (n := lim.get('max_prompt_tokens') or lim.get('max_context_window_tokens')): return int(n), ''
    return _cloud_ctx(model_id)      # the same id under its own vendor is the next best answer

def _cloud_ctx(model_id):
    "Context window and a note for a cloud model, from fastllm's tables. Silent about failure."
    try:
        from fastllm.types import get_model_info
        v, _, m = model_id.partition('/')
        info = get_model_info(m or v, v if m else None)
        n = info.get('max_input_tokens') or info.get('max_tokens')
        if n: return int(n), ''
        return 128_000, 'context window unknown, assuming 128k'
    except Exception as e: return 128_000, f'context window unknown ({agent_err(e)}), assuming 128k'

# %% ../nbs/00_core.ipynb #1d37d28a
def unknown_model(name):
    """What to say about a name nothing matches.

    Printing all of `MODELS` buried the useful part: `claude-sonnet-4.6` for `claude-sonnet-4-6` is
    one character, and the reader had to find it among forty-odd names. `/models` lists them.
    """
    near = difflib.get_close_matches(str(name), MODELS, n=2, cutoff=0.6)
    hint = f'; did you mean {" or ".join(repr(n) for n in near)}?' if near else '.'
    return (f'unknown model {name!r}{hint} `/models` lists what is configured, and any '
            f'vendor/model spec works too.')

#: Prefixes that name a runtime or a transport rather than a vendor, in the spelling that works.
PREFIXES = RUNTIMES

#: Prefixes that used to route somewhere and no longer do, and what to say about each. Without
#: this an id left in a config is read as a vendor and handed to `remote`, which asks for an API
#: key nothing about the request needs: a credentials error several layers from the cause.
RETIRED = {'claude_code': 'use `claude/` instead: the same models, through Claude Code itself',
           'cursor': 'the Cursor backend was removed'}

def resolve(name, default_local=DFLT_LOCAL):
    'A `ModelSpec` for `name`: a short name from the tables, or any full `vendor/model` spec.'
    if not name: name = default_local
    if name in MODELS:
        backend, mid = MODELS[name]
        config = CUSTOM.get(name, {}).get('config', {})
        if backend not in ('remote', 'copilot'):
            if not runtime_available(backend): raise RuntimeError(f'{backend} runtime is unavailable; install rishi[{backend}]')
            # deliberately not the model's own window: an agent harness carries no session
            # state, so every turn re-renders the whole conversation as a prompt and sends it
            # again. The ceiling is what that costs to re-send, not what the model could hold
            ctx = DFLT_AGENT_CTX if backend in AGENTS else local_ctx(name)
            return ModelSpec(name, backend, mid, ctx, config=config)
        if backend == 'copilot':
            ctx, note = _copilot_ctx(mid)
            return ModelSpec(name, backend, mid, ctx, note, config)
        ctx, note = _cloud_ctx(mid)
        return ModelSpec(name, backend, mid, ctx, note, config)
    if '/' in name:
        runtime, model_id = name.split('/', 1)
        if runtime in RETIRED: raise KeyError(f'{name!r}: the {runtime!r} prefix was removed -- {RETIRED[runtime]}')
        if runtime == 'copilot':
            if not runtime_available('copilot'): raise RuntimeError(COPILOT_UNAVAILABLE)
            ctx, note = _copilot_ctx(model_id)
            return ModelSpec(name, 'copilot', model_id, ctx, note)
        if runtime in ('litert', 'mlx', 'llama', *AGENTS):
            if not runtime_available(runtime): raise RuntimeError(f'{runtime} runtime is unavailable; install rishi[{runtime}]')
            ctx = DFLT_AGENT_CTX if runtime in AGENTS else local_ctx(name)
            return ModelSpec(name, runtime, model_id, ctx)
        ctx, note = _cloud_ctx(name)
        return ModelSpec(name, 'remote', name, ctx, note)
    raise KeyError(unknown_model(name))

@functools.lru_cache(maxsize=256)
def _caps(model_id, runtime):
    "`rishi.model_caps`, memoised. `None` where rishi predates it."
    try:
        from rishi.core import model_caps
        return model_caps(model_id, runtime=runtime)
    except Exception: return None

def spec_caps(spec):
    "What `spec`'s model accepts and what it hands back, or `None` where rishi cannot say."
    return _caps(spec.model_id, spec.backend if spec.local else 'remote')

def accepts(spec, kind):
    "Can `spec`'s model be sent `kind`? Unknown counts as yes."
    c = spec_caps(spec)
    return True if c is None or not c.known else c.accepts(kind)

def model_note(spec):
    "One line about a resolved model, for a status bar."
    where = 'local' if spec.local else 'cloud'
    out = f'{spec.name} · {where} · {spec.ctx//1000}k ctx'
    if (c := spec_caps(spec)) is not None and (m := c.fmt()): out += f' · {m}'
    return out + (f' · {spec.note}' if spec.note else '')

# %% ../nbs/00_core.ipynb #4e529923
SMALL_CTX = 24_000       # at or below this window, a model is briefed frugally
TOOL_MAX_FLOOR = 1500    # chars. Below this a file view stops being a file view
FRUGAL_DROP = ('memory', 'web')

@dataclass(frozen=True)
class Budget:
    'What a model can afford to be told, and to be sent back.'
    drop: tuple = ()         # capability groups to withhold from `tools_for`
    inline: bool = True      # whether the briefing may inline a skill body
    tool_max: int = 0        # chars one tool result may spend
    note: str = ''           # why, for a status bar

TAGS_SCHEMA_TOKENS = 3300

def budget_for(spec, tool_max, channel='native'):
    """The briefing `spec`'s model can afford, from its context window.

    `tool_max` is the caller's own default, and this only ever lowers it. Raising the clip on a
    large window would change the case that already works, and the case that does not is the
    only reason this exists.

    A spec with no window, or one we could not read, gets the full briefing. Withholding tools
    from a model whose size is unknown turns not knowing into a smaller agent, and `_cloud_ctx`
    already assumes 128k when a table fails it.
    """
    ctx = getattr(spec, 'ctx', 0) or 0
    if ctx > 0 and channel == 'tags': ctx = max(1, ctx - TAGS_SCHEMA_TOKENS)
    if ctx <= 0 or ctx > SMALL_CTX: return Budget(tool_max=tool_max, note='full briefing')
    mx = min(tool_max, max(TOOL_MAX_FLOOR, (ctx//16)*4))
    return Budget(FRUGAL_DROP, False, mx,
                  f'{ctx//1000}k window: no inlined skills, no {"/".join(FRUGAL_DROP)} tools, '
                  f'tool results clipped to {mx} chars')

# %% ../nbs/00_core.ipynb #3e2adbad
def register_model(name, model_id, runtime=None, ctx=128_000, note='custom model', **config):
    "Register a configurable model alias for this process. Persistence belongs to the host app."
    name, model_id = (name or '').strip(), (model_id or '').strip()
    if model_id.startswith(('https://huggingface.co/', 'http://huggingface.co/')):
        model_id = model_id.split('huggingface.co/', 1)[1].strip('/').split('/tree/', 1)[0]
    if not name: name = model_id.rsplit('/', 1)[-1]
    if not name or not model_id: raise ValueError('model name and model id are required')
    if runtime is None:
        from rishi.core import resolve_runtime
        runtime, model_id = resolve_runtime(model_id)
    # `RUNTIMES`, not a literal: whatever `resolve_runtime` can infer has to be here, or
    # `register_model` fails on the answer it just asked for
    if runtime not in RUNTIMES: raise ValueError(f'unknown runtime {runtime!r}')
    if runtime != 'remote' and not runtime_available(runtime):
        raise RuntimeError(f'{runtime} runtime is unavailable; install rishi[{runtime}]')
    MODELS[name] = (runtime, model_id); _LOCAL_CTX[name] = int(ctx or 128_000)
    CUSTOM[name] = {'name': name, 'model_id': model_id, 'runtime': runtime,
                    'ctx': int(ctx or 128_000), 'note': note, 'config': config}
    return resolve(name)

def unregister_model(name):
    "Remove one process-local configurable model alias."
    CUSTOM.pop(name, None); MODELS.pop(name, None); _LOCAL_CTX.pop(name, None)

# %% ../nbs/00_core.ipynb #1e5cd7ee
TOOL_CHANNELS = ('native', 'tags')

_forced_tags = {}   # model_id -> why its wire tool channel is closed on this machine


def force_tags(model_id, why=''):
    "Record that this model's tools cannot travel on the wire here. Later turns stop trying."
    why = why or 'the wire tool channel was refused'
    _forced_tags[str(model_id)] = why
    return why


def forget_forced_tags():
    "Forget what was learned about wire channels. A fixed configuration is tried again."
    _forced_tags.clear()


def tool_channel(spec, chat=None):
    """Which channel a model's tool schemas travel on: `'native'` on the wire, `'tags'` in the
    system prompt. Takes a `ModelSpec` or a bare model id, and the live chat when there is one.

    A chat is the authority. An agent runtime decides its own channel from the path it took and from
    what the harness accepted. No property of the spec can be sure. A Claude chat that opened an
    MCP server and had it refused is on tags now, and only it knows. Without one this predicts, which
    is all `budget_for` can have: it sizes the tool list, and the tool list is what builds the chat.
    """
    if (v := (env('TOOL_CHANNEL') or '').strip().lower()) in TOOL_CHANNELS: return v
    if (ch := getattr(chat, 'tool_channel', None)) in TOOL_CHANNELS: return ch
    mid = str(getattr(spec, 'model_id', spec) or '')
    # a bare id carries its runtime in the prefix, and nowhere else: without this an agent
    # harness's id fell through to the default for a hosted model
    rt = getattr(spec, 'runtime', '') or (mid.split('/', 1)[0] if '/' in mid else '')
    # an agent harness has no native channel: its only way to carry a tool it did not ship with
    # is an MCP server, and a managed configuration refuses even the in-process kind
    if rt in AGENTS: return 'tags'
    if mid in _forced_tags: return 'tags'
    return 'native'

# %% ../nbs/00_core.ipynb #e81acb32
@dataclass
class Routing:
    """Job -> model. The policy, and the one place that decides what runs where.
    Environment overrides (`LEELA_MODEL`, `LEELA_MODEL_SUMMARY`, ...) exist.
    """
    turn: str = None
    policy: dict = field(default_factory=lambda: dict(DEFAULT_POLICY))
    default_local: str = DFLT_LOCAL

    def __post_init__(self):
        if not self.turn: self.turn = env('MODEL') or self.default_local
        for job in JOBS:
            if (v := env(f'MODEL_{job.upper()}')): self.policy[job] = v
        self._cache, self.notes = {}, {}

    def name_for(self, job='turn'):
        """The model name `job` runs on: its own policy, then `oneshot` if it is a cheap job, then `turn`."""
        if job == 'turn': return self.turn
        if (n := self.policy.get(job)): return n
        if job in ONESHOT_JOBS and (n := self.policy.get('oneshot')): return n
        return self.turn

    def _resolve(self, name):
        "One resolution, cached: reading fastllm's tables for a cloud model is not free."
        if name not in self._cache: self._cache[name] = resolve(name, self.default_local)
        return self._cache[name]

    def alternatives(self, job):
        "Where `job` goes when its own model is not on this machine, best first."
        seen, out = {self.name_for(job)}, []
        for alt in (self.policy.get('oneshot') if job in ONESHOT_JOBS else None,
                    self.turn, *(self.policy.get(j) for j in JOBS), self.default_local):
            if alt and alt not in seen:
                seen.add(alt); out.append(alt)
        return out

    def spec(self, job='turn', fallback=True):
        """The resolved `ModelSpec` for `job`, on another model when its own is not installed here."""
        n = self.name_for(job)
        try: return self._resolve(n)
        except Exception as e:
            if not fallback or job == 'turn': raise
            for alt in self.alternatives(job):
                try: spec = self._resolve(alt)
                except Exception: continue
                self.notes[job] = f'{n} unavailable ({agent_err(e)}); using {alt}'
                return spec
            raise

    def set(self, name, job='turn'):
        "Point `job` at `name`, validating it first so a typo fails here rather than mid-turn."
        spec = resolve(name, self.default_local)
        if job == 'turn': self.turn = name
        else: self.policy[job] = name
        self._cache[name] = spec
        return spec

    def backends(self):
        "The distinct backend/model pairs this policy needs. An engine is built once and shared."
        out = set()
        for j in JOBS:
            try: s = self.spec(j)
            except Exception: continue      # a job with nowhere to run needs no engine built
            out.add((s.backend, s.model_id))
        return out

    def summary(self):
        "The whole policy in one block, for `/model` with no argument, including anything that moved."
        rows = []
        for j in JOBS:
            try: row = model_note(self.spec(j))
            except Exception as e: row = f'unavailable ({agent_err(e)})'
            rows.append(f'{j:11} {row}' + (f'  [{self.notes[j]}]' if j in self.notes else ''))
        return '\n'.join(rows)
