"""The error type, the environment convention, and the one place that decides which model runs what.

## Errors and environment

A harness fails in two ways, and a person needs to be told them differently. `AgentError`
is a refusal -- something the harness will not do, which the user can act on. Anything else
is a bug, and should look like one.

## The model tables

`MODELS` maps shared short names to LiteRT models on device or cloud model ids. `JOBS` is
the set of distinct jobs the policy can route separately.

## Credentials

`auth_status` reports which credential sources fastllm could use. It reads status
metadata only: no function here returns, logs or stores a secret, and the Claude Code
login is probed by asking the `claude` binary, never by reading its credential file.

## Listing models

`available_models` is what a model picker renders. It lists the on-device models
unconditionally, adds llama.cpp only when that package is importable, and adds a vendor's
cloud catalog only when a credential for it exists -- so the list never offers a model the
process cannot actually run.

## Defaults and context windows

LiteRT is the only local runtime. `DEFAULT_POLICY` leaves `turn` unset -- that is the
user's choice -- and points the cheap, frequent jobs at the small local Gemma.

## Resolving a model

A `ModelSpec` is a model after every question about it has been answered: which backend
runs it, what that backend should be handed, how big its context is, and anything worth
telling the user about how that was decided. Everything downstream takes a spec, never a
name, so the guessing happens once and in one place.

## Configurable models

`register_model` adds an alias for this process only. Persisting it is the host
application's business, since Ramabana does not own the user's configuration file. Passing
a Hugging Face URL is enough; rishi decides which runtime can serve it.

## Routing

`Routing` is job to model, and the only thing that decides what runs where. `turn` is
the model the user chose; every other job falls back to it when the policy has nothing to
say, so adding a job to `JOBS` cannot strand a caller without a model.

Docs: https://vedicreader.github.io/ramabana/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ENV_PREFIX', 'ENV_FALLBACK', 'JOBS', 'ONESHOT_JOBS', 'LOCAL', 'MLX', 'LLAMA', 'GPT', 'CLAUDE', 'CLOUD', 'CUSTOM',
           'MODELS', 'DFLT_LOCAL', 'completer', 'cheap', 'DEFAULT_POLICY', 'DFLT_LOCAL_CTX', 'SMALL_CTX',
           'TOOL_MAX_FLOOR', 'FRUGAL_DROP', 'AgentError', 'agent_err', 'use_env_prefix', 'env', 'runtime_available',
           'claude_tags', 'auth_status', 'available_models', 'local_ctx', 'ModelSpec', 'resolve', 'model_note',
           'Budget', 'budget_for', 'register_model', 'unregister_model', 'Routing']

# %% ../nbs/00_core.ipynb #41a0b203
import importlib, importlib.util, json, os, platform, re, shutil, subprocess, sys, time
from fastcore.all import Path
from dataclasses import dataclass, field

# %% ../nbs/00_core.ipynb #2049138c
ENV_PREFIX, ENV_FALLBACK = 'RAMABANA_', 'LEELA_'

class AgentError(Exception):
    "Something the harness refuses to do, rather than a failure while doing it."

def agent_err(e):
    "A caught exception for a user-facing harness surface."
    return f'{type(e).__name__}: {e}'

def use_env_prefix(prefix, fallback=None):
    """Name the environment variables this application reads, most specific first.

    `leela.agent` is an alias for this package rather than a copy of it, and leela's users
    already have `$LEELA_MODEL` set. Calling `use_env_prefix('LEELA_', 'RAMABANA_')` at
    startup makes that the one that wins inside leela, without making leela's name the
    primary namespace for everything else built on this core.
    """
    global ENV_PREFIX, ENV_FALLBACK
    ENV_PREFIX = prefix if prefix.endswith('_') else prefix + '_'
    if fallback is not None: ENV_FALLBACK = fallback if fallback.endswith('_') else fallback + '_'
    return ENV_PREFIX, ENV_FALLBACK


def env(name, dflt=None):
    "`$<prefix><name>`, then `$<fallback><name>`, then `dflt`. See `use_env_prefix`."
    return os.environ.get(ENV_PREFIX+name) or os.environ.get(ENV_FALLBACK+name) or dflt

# %% ../nbs/00_core.ipynb #9df3b26a
JOBS = ('turn', 'oneshot', 'inline', 'completion', 'classify', 'summary', 'subagent')

#: The jobs that are one short stateless call and nothing else. They take the `oneshot`
#: policy unless set individually, so "run the cheap jobs somewhere else" is one setting
#: rather than three -- and so the model they run on has a *name*, which is what makes it
#: something a person can point at and something `Routing` can find a substitute for.
#: `subagent` is not here: it is a whole conversation. Nor is `turn`.
ONESHOT_JOBS = ('oneshot', 'completion', 'classify', 'summary', 'inline')
LOCAL = {'gemma-e2b': 'litert-community/gemma-4-E2B-it-litert-lm',
    'gemma-e4b': 'litert-community/gemma-4-E4B-it-litert-lm',
    'gemma-12b': 'litert-community/gemma-4-12B-it-litert-lm'}
MLX = {'qwen-4b': 'mlx-community/Qwen3.5-4B-MLX-4bit',
       'mini-coder-4b': 'mlx-community/mini-coder-4b-OptiQ-4bit',
       'ornith-9b': 'mlx-community/Ornith-1.0-9B-8bit'}
LLAMA = {'llama-qwen-0.6b': 'Qwen/Qwen3-0.6B-GGUF',
         'llama-qwen-1.7b': 'Qwen/Qwen3-1.7B-GGUF',
         'llama-qwen-4b': 'Qwen/Qwen3-4B-GGUF'}

GPT = {name: f'openai/{name}' for name in (
    'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano',
    'gpt-5.4', 'gpt-5.4-mini', 'gpt-5.6', 'gpt-5.6-luna', 'gpt-5.6-sol', 'gpt-5.6-terra')}
GPT.update({name: f'codex/{name}' for name in (
    'gpt-5.3-codex-spark', 'gpt-5.5')})
CLAUDE = {name: f'claude_code/{name}' for name in (
    'claude-haiku-4-5', 'claude-sonnet-4-5', 'claude-sonnet-4-6',
    'claude-opus-4-6', 'claude-opus-4-8', 'claude-fable-5',
    'claude-sonnet-5', 'claude-opus-5')}
CLOUD = {**GPT, **CLAUDE,
    'sonnet': CLAUDE['claude-sonnet-5'], 'opus': CLAUDE['claude-opus-5'],
    'fable': CLAUDE['claude-fable-5'], 'gpt': GPT['gpt-5.6-terra'],
    'gpt-mini': GPT['gpt-5.6-luna'], 'gpt-sol': GPT['gpt-5.6-sol']}

CUSTOM = {}
_RUNTIME_DEPS = {'litert': 'litert_lm', 'mlx': 'mlx_lm', 'llama': 'llama_cpp'}

def runtime_available(runtime):
    "Whether Rishi's optional dependency for `runtime` can be imported. Never raises."
    if runtime == 'remote': return True
    try: return importlib.util.find_spec(_RUNTIME_DEPS[runtime]) is not None
    except (ImportError, KeyError, ValueError): return False

MODELS = {**{k: ('litert', v) for k, v in LOCAL.items()},
          **{k: ('mlx', v) for k, v in MLX.items()},
          **{k: ('llama', v) for k, v in LLAMA.items()},
          **{k: ('remote', v) for k, v in CLOUD.items()}}

# %% ../nbs/00_core.ipynb #9881cc3b
def _json_has(path, *keys):
    try:
        value = Path(path).expanduser().read_json()
        for key in keys: value = value[key]
        return bool(value)
    except Exception: return False

def _claude_login():
    "Only status metadata; credentials never leave Claude Code or enter Leela."
    if not shutil.which('claude'): return False
    try:
        p = subprocess.run(['claude', 'auth', 'status', '--json'], capture_output=True, text=True, timeout=3)
        return p.returncode == 0 and bool(json.loads(p.stdout).get('loggedIn'))
    except Exception: return False


def _install_toolslm_funccall():
    """Expose fastcore's replacement under the module name python-fastllm 0.0.36 imports.

    Called where it is needed, not at import. Writing into `sys.modules` is a process-wide
    edit to somebody else's package, and doing it as a side effect of `import ramabana.core`
    meant importing anything at all from this library rearranged `toolslm` for every other
    consumer in the interpreter -- a test that imports Ramabana to read one constant, a
    notebook that imports it beside a library with its own opinion about `toolslm`.

    Only `fastllm.chat` needs the shim, and only the Claude Code transport imports that, so
    the two callers are `_load_claude_transport` and the moment a `claude_code/` model is
    resolved -- both of which already run before anything can reach the transport.
    """
    try: return importlib.import_module('toolslm.funccall')
    except ModuleNotFoundError as e:
        if e.name != 'toolslm.funccall': raise
    import toolslm
    funccall = importlib.import_module('fastcore.funccall')
    sys.modules['toolslm.funccall'] = funccall
    toolslm.funccall = funccall
    return funccall
def _managed_claude_mcp():
    "Whether this machine has an organisation-controlled Claude Code MCP configuration."
    paths = [Path('/Library/Application Support/ClaudeCode/managed-mcp.json'),
             Path('/etc/claude-code/managed-mcp.json')]
    if appdata := os.getenv('PROGRAMDATA'):
        paths.append(Path(appdata)/'ClaudeCode'/'managed-mcp.json')
    return any(path.exists() for path in paths)


def _claude_payload_compat(transport):
    """Make FastLLM's Claude Code payload legal under an enterprise-managed MCP policy.

    The transport declares Ramabana's tools to Claude Code as an in-process MCP server, and a
    managed configuration forbids every dynamic MCP server there is. Stripping them is the
    only legal payload -- and on its own it left the model with no tools at all, which is a
    coding agent that cannot read a file.

    So the tools go through the other channel, the one no policy can close: the system prompt.
    `claude_tags` is what asks Rishi for that, and this stays what it always was -- the last
    edit before the payload goes out, making it legal.
    """
    mk_payload = transport.mk_payload
    if getattr(mk_payload, '_ramabana_enterprise_mcp', False): return
    def compatible_payload(*args, **kwargs):
        payload = mk_payload(*args, **kwargs)
        if _managed_claude_mcp():
            options = payload['options']
            options.strict_mcp_config = False
            options.mcp_servers = {}
            options.allowed_tools = []
        return payload
    compatible_payload._ramabana_enterprise_mcp = True
    transport.mk_payload = compatible_payload


def claude_tags(model_id):
    """Whether this model's tools have to travel in the system prompt rather than over MCP.

    Only Claude Code, and only under a managed configuration. Everywhere else the transport's
    own tool declaration is better in every way -- the schemas are validated, the calls come
    back structured, and nothing depends on the model minding its punctuation.

    `$RAMABANA_CLAUDE_TAG_TOOLS` forces it either way, because the managed-config probe reads
    three fixed paths and an organisation that has moved them should not have to discover this
    by watching an agent sit there with no tools.
    """
    if (v := (env('CLAUDE_TAG_TOOLS') or '').strip().lower()) in ('1', 'true', 'yes'): return True
    if v in ('0', 'false', 'no'): return False
    return str(model_id or '').startswith('claude_code/') and _managed_claude_mcp()


def _load_claude_transport():
    "Load and verify FastLLM's Claude Code plugin."
    try:
        _install_toolslm_funccall()
        from fastllm.acomplete import api_registry
        _claude_payload_compat(api_registry['claude_code'])
        return True, ''
    except Exception as e: return False, agent_err(e)


def auth_status():
    'Credential sources FastLLM can use, without reading or returning any secret.'
    codex = bool(os.getenv('CODEX_AUTH_TOKEN') or _json_has(os.getenv('CODEX_AUTH_PATH', '~/.codex/auth.json'), 'tokens', 'access_token'))
    claude_transport, claude_error = _load_claude_transport()
    claude_login = _claude_login()
    return {
        'openai': {'available': bool(os.getenv('OPENAI_API_KEY')), 'source': 'OPENAI_API_KEY'},
        'codex': {'available': codex, 'source': 'Codex login' if codex else ''},
        'anthropic': {'available': bool(os.getenv('ANTHROPIC_API_KEY')), 'source': 'ANTHROPIC_API_KEY'},
        'claude_code': {'available': claude_login and claude_transport,
                        'source': ('Claude Code login' if claude_login and claude_transport else ''),
                        'note': (f'Claude Code login found, but its FastLLM transport failed: {claude_error}'
                                 if claude_login and not claude_transport else '')},
        'gemini': {'available': bool(os.getenv('GEMINI_API_KEY')), 'source': 'GEMINI_API_KEY'},
    }

# %% ../nbs/00_core.ipynb #56303cec
_oai_cache = (0.0, [])
def _openai_models(include_legacy=False):
    "Canonical models the current OpenAI key can list; older coding models are opt-in."
    global _oai_cache
    ids = _oai_cache[1] if (time.time() - _oai_cache[0]) < 300 else None
    if not (key := os.getenv('OPENAI_API_KEY')): return []
    if ids is None:
        try:
            import httpx2 as httpx
            r = httpx.get('https://api.openai.com/v1/models', headers={'Authorization': f'Bearer {key}'}, timeout=10)
            r.raise_for_status()
            ids = [x.get('id', '') for x in r.json().get('data', [])]
        except Exception: ids = []
        _oai_cache = (time.time(), ids)
    current = re.compile(r'^(?:gpt-5(?:\.\d+)?(?:-(?:mini|nano|pro|codex(?:-mini|-max)?|chat-latest|search-api|[a-z]+))?|o[34](?:-mini|-pro)?)$')
    legacy = re.compile(r'^gpt-4\.1(?:-mini|-nano)?$')
    return sorted({x for x in ids if (current.match(x) or (include_legacy and legacy.match(x))) and not re.search(r'-20\d\d-', x)})

def available_models(include_legacy=False):
    "Models selectable here; specialized older generations appear only when requested."
    rows = []
    for runtime, models in (('litert', LOCAL), ('mlx', MLX), ('llama', LLAMA)):
        if not runtime_available(runtime): continue
        rows += [{'value': name, 'label': name, 'provider': runtime,
                  'source': f'on device via Rishi {runtime}'} for name in models]
    auth = auth_status()
    if auth['openai']['available']:
        for model in _openai_models(include_legacy):
            rows.append({'value': f'openai/{model}', 'label': model, 'provider': 'openai',
                         'source': auth['openai']['source']})
    try:
        from fastllm.types import model_info_registry
        vendors = ('openai', 'codex', 'claude_code', 'gemini')
        for vendor in vendors:
            if not auth.get(vendor, {}).get('available'): continue
            for v, model in model_info_registry:
                if v != vendor: continue
                if not include_legacy and re.match(r'^gpt-4(?:\.|-|$)', model): continue
                rows.append({'value': f'{vendor}/{model}', 'label': model, 'provider': vendor,
                             'source': auth[vendor]['source']})
    except Exception: pass
    if auth['anthropic']['available']:
        catalog = set()
        try:
            from fastllm.types import model_info_registry
            catalog = {model for vendor, model in model_info_registry if vendor in ('anthropic', 'claude_code') and model.startswith('claude-')}
        except Exception: pass
        catalog.update(model.split('/', 1)[1] for model in CLOUD.values() if model.startswith('anthropic/'))
        for model in sorted(catalog): rows.append({'value': f'anthropic/{model}', 'label': model,
                                                   'provider': 'anthropic', 'source': auth['anthropic']['source']})
    seen, out = set(), []
    for row in rows:
        if row['value'] in seen: continue
        seen.add(row['value']); out.append(row)
    return out

# %% ../nbs/00_core.ipynb #70d7dfa3
DFLT_LOCAL = 'gemma-e4b'
completer = DFLT_LOCAL
cheap = completer          # back-compat alias

#: `None` for the one-shot jobs, which is not "unset" but "whatever `oneshot` says" -- see
#: `Routing.name_for`. Spelling each of them out as the same constant meant the cheap model
#: could only be moved three times or not at all.
DEFAULT_POLICY = {'turn': None, 'oneshot': completer, 'inline': None, 'completion': None,
                  'classify': None, 'summary': None, 'subagent': DFLT_LOCAL}

_LOCAL_CTX = {'gemma-e2b': 16_384, 'gemma-e4b': 16_384, 'gemma-12b': 32_000,
              'qwen-4b': 32_768, 'mini-coder-4b': 32_768, 'ornith-9b': 32_768,
              'llama-qwen-0.6b': 32_768, 'llama-qwen-1.7b': 32_768, 'llama-qwen-4b': 32_768}
DFLT_LOCAL_CTX = 32_768


def local_ctx(name, dflt=DFLT_LOCAL_CTX):
    "The context window for a local model: `$LEELA_LOCAL_CTX` if it says, else the table."
    if (ovr := (env('LOCAL_CTX') or '').strip()):
        if ovr.isdigit(): return int(ovr)
        for part in ovr.split(','):
            k, _, v = part.partition(':')
            if k.strip() == name and v.strip().isdigit(): return int(v)
    return _LOCAL_CTX.get(name, dflt)

# %% ../nbs/00_core.ipynb #64093121
@dataclass(frozen=True)
class ModelSpec:
    'One model, resolved: which backend runs it, what to call it, and how big it is.'
    name: str                 # what the user types
    backend: str              # 'rishi' | 'fastllm'
    model_id: str             # what the backend is given
    ctx: int = 128_000        # context window in tokens
    note: str = ''            # anything worth showing about how this was resolved
    config: dict = field(default_factory=dict, compare=False) # runtime options; never persisted secrets

    @property
    def runtime(self): return self.backend
    @property
    def local(self): return self.backend != 'remote'
    def __str__(self): return f'{self.name} ({self.model_id})'


def _cloud_ctx(model_id):
    "Context window and a note for a cloud model, from fastllm's tables; silent about failure."
    try:
        from fastllm.types import get_model_info
        v, _, m = model_id.partition('/')
        info = get_model_info(m or v, v if m else None)
        n = info.get('max_input_tokens') or info.get('max_tokens')
        if n: return int(n), ''
        return 128_000, 'context window unknown, assuming 128k'
    except Exception as e: return 128_000, f'context window unknown ({agent_err(e)}), assuming 128k'

# %% ../nbs/00_core.ipynb #1d37d28a
def resolve(name, default_local=DFLT_LOCAL):
    'A `ModelSpec` for `name`: a short name from the tables, or any full `vendor/model` spec.'
    if not name: name = default_local
    if name in MODELS:
        backend, mid = MODELS[name]
        config = CUSTOM.get(name, {}).get('config', {})
        if backend != 'remote':
            # The same check the `vendor/model` branch below has always made, and the reason
            # this one lacking it mattered: a short MLX name resolved cleanly on a machine
            # with no MLX, so a job routed to it got a `ModelSpec`, built a backend, failed at
            # `start()`, and reported nothing -- while `Routing`, told the model was fine,
            # never looked for one that was.
            if not runtime_available(backend):
                raise RuntimeError(f'{backend} runtime is unavailable; install rishi[{backend}]')
            return ModelSpec(name, backend, mid, local_ctx(name), config=config)
        if mid.startswith('claude_code/'):
            ok, error = _load_claude_transport()
            if not ok: raise RuntimeError(f'Claude Code transport unavailable: {error}')
        ctx, note = _cloud_ctx(mid)
        return ModelSpec(name, backend, mid, ctx, note, config)
    if '/' in name:
        runtime, model_id = name.split('/', 1)
        if runtime == 'claude_code':
            ok, error = _load_claude_transport()
            if not ok: raise RuntimeError(f'Claude Code transport unavailable: {error}')
        if runtime in ('litert', 'mlx', 'llama'):
            if not runtime_available(runtime):
                raise RuntimeError(f'{runtime} runtime is unavailable; install rishi[{runtime}]')
            return ModelSpec(name, runtime, model_id, local_ctx(name))
        ctx, note = _cloud_ctx(name)
        return ModelSpec(name, 'remote', name, ctx, note)
    raise KeyError(f'unknown model {name!r}; known: {", ".join(sorted(MODELS))}, or a vendor/model spec')

def model_note(spec):
    "One line about a resolved model, for a status bar."
    where = 'local' if spec.local else 'cloud'
    return f'{spec.name} · {where} · {spec.ctx//1000}k ctx' + (f' · {spec.note}' if spec.note else '')

# %% ../nbs/00_core.ipynb #4e529923
SMALL_CTX = 24_000       # at or below this window, a model is briefed frugally
TOOL_MAX_FLOOR = 1500    # chars; below this a file view stops being a file view

#: The capability groups a small window gives up first. Research is what a 16k model cannot
#: use even when it has it: one `read_url` at that model's own clip is most of the room the
#: briefing leaves it, so carrying the schemas buys a route that cannot finish anyway.
FRUGAL_DROP = ('memory', 'web')


@dataclass(frozen=True)
class Budget:
    'What a model can afford to be told, and to be sent back.'
    drop: tuple = ()         # capability groups to withhold from `tools_for`
    inline: bool = True      # whether the briefing may inline a skill body
    tool_max: int = 0        # chars one tool result may spend
    note: str = ''           # why, for a status bar


def budget_for(spec, tool_max):
    """The briefing `spec`'s model can afford, from its context window.

    `tool_max` is the caller's own default, and this only ever lowers it. Raising the clip on a
    large window would change the case that already works, and the case that does not is the
    only reason this exists.

    A spec with no window, or one we could not read, gets the full briefing. Withholding tools
    from a model whose size is unknown turns not knowing into a smaller agent, and `_cloud_ctx`
    already assumes 128k when a table fails it.
    """
    ctx = getattr(spec, 'ctx', 0) or 0
    if ctx <= 0 or ctx > SMALL_CTX: return Budget(tool_max=tool_max, note='full briefing')
    mx = min(tool_max, max(TOOL_MAX_FLOOR, (ctx//16)*4))
    return Budget(FRUGAL_DROP, False, mx,
                  f'{ctx//1000}k window: no inlined skills, no {"/".join(FRUGAL_DROP)} tools, '
                  f'tool results clipped to {mx} chars')


# %% ../nbs/00_core.ipynb #3e2adbad
def register_model(name, model_id, runtime=None, ctx=128_000, note='custom model', **config):
    "Register a configurable model alias for this process; persistence belongs to the host app."
    name, model_id = (name or '').strip(), (model_id or '').strip()
    if model_id.startswith(('https://huggingface.co/', 'http://huggingface.co/')):
        model_id = model_id.split('huggingface.co/', 1)[1].strip('/').split('/tree/', 1)[0]
    if not name: name = model_id.rsplit('/', 1)[-1]
    if not name or not model_id: raise ValueError('model name and model id are required')
    if runtime is None:
        from rishi.core import resolve_runtime
        runtime, model_id = resolve_runtime(model_id)
    if runtime not in ('litert', 'mlx', 'llama', 'remote'): raise ValueError(f'unknown runtime {runtime!r}')
    if runtime != 'remote' and not runtime_available(runtime):
        raise RuntimeError(f'{runtime} runtime is unavailable; install rishi[{runtime}]')
    MODELS[name] = (runtime, model_id); _LOCAL_CTX[name] = int(ctx or 128_000)
    CUSTOM[name] = {'name': name, 'model_id': model_id, 'runtime': runtime,
                    'ctx': int(ctx or 128_000), 'note': note, 'config': config}
    return resolve(name)


def unregister_model(name):
    "Remove one process-local configurable model alias."
    CUSTOM.pop(name, None); MODELS.pop(name, None); _LOCAL_CTX.pop(name, None)

# %% ../nbs/00_core.ipynb #e81acb32
@dataclass
class Routing:
    """Job -> model. The policy, and the one place that decides what runs where.

    `turn` is the model the user chose; everything else defaults to the local one and can
    be overridden individually, so "use flash for summaries" is a line of config and not a
    code change. Environment overrides (`LEELA_MODEL`, `LEELA_MODEL_SUMMARY`, ...) exist
    because the first thing anyone does with a routing policy is try a different one.
    """
    turn: str = None
    policy: dict = field(default_factory=lambda: dict(DEFAULT_POLICY))
    default_local: str = DFLT_LOCAL

    def __post_init__(self):
        if not self.turn: self.turn = env('MODEL') or self.default_local
        for job in JOBS:
            if (v := env(f'MODEL_{job.upper()}')): self.policy[job] = v
        self._cache, self.notes = {}, {}

    def name_for(self, job='turn'):
        """The model name `job` runs on: its own policy, then `oneshot` if it is a cheap job, then `turn`.

        The middle step is the one worth having. Every short stateless call -- a label, a
        summary, a completion -- wants the same small fast model, and naming that model once
        is the difference between a policy you can change and three constants that happened
        to be equal.
        """
        if job == 'turn': return self.turn
        if (n := self.policy.get(job)): return n
        if job in ONESHOT_JOBS and (n := self.policy.get('oneshot')): return n
        return self.turn

    def _resolve(self, name):
        "One resolution, cached: reading fastllm's tables for a cloud model is not free."
        if name not in self._cache: self._cache[name] = resolve(name, self.default_local)
        return self._cache[name]

    def alternatives(self, job):
        "Where `job` goes when its own model is not on this machine, best first."
        seen, out = {self.name_for(job)}, []
        for alt in (self.policy.get('oneshot') if job in ONESHOT_JOBS else None,
                    self.turn, *(self.policy.get(j) for j in JOBS), self.default_local):
            if alt and alt not in seen:
                seen.add(alt); out.append(alt)
        return out

    def spec(self, job='turn', fallback=True):
        """The resolved `ModelSpec` for `job`, on another model when its own is not installed here.

        A policy names a model; a machine either has it or does not, and `resolve` raises for
        a runtime whose optional dependency is missing. Every cheap job pointed at the default
        local model, which is a LiteRT one -- so on a machine with MLX and no LiteRT, every
        classify, summary and completion raised, `Agent._be_or_none` swallowed it, and
        `Agent.oneshot` returned `''`. The cheap jobs did not fail; they silently stopped
        happening, which is much harder to notice.

        `turn` never falls back and that asymmetry is the point: the user chose that model and
        running a different one for their conversation without saying so would be worse than
        failing. Nobody chose the model a summary runs on, and a summary from somewhere else
        is still a summary. Why a job moved is recorded in `notes` and shown by `summary()`.
        """
        n = self.name_for(job)
        try: return self._resolve(n)
        except Exception as e:
            if not fallback or job == 'turn': raise
            for alt in self.alternatives(job):
                try: spec = self._resolve(alt)
                except Exception: continue
                self.notes[job] = f'{n} unavailable ({agent_err(e)}); using {alt}'
                return spec
            raise

    def set(self, name, job='turn'):
        "Point `job` at `name`, validating it first so a typo fails here rather than mid-turn."
        spec = resolve(name, self.default_local)
        if job == 'turn': self.turn = name
        else: self.policy[job] = name
        self._cache[name] = spec
        return spec

    def backends(self):
        "The distinct backend/model pairs this policy needs, so an engine is built once and shared."
        out = set()
        for j in JOBS:
            try: s = self.spec(j)
            except Exception: continue      # a job with nowhere to run needs no engine built
            out.add((s.backend, s.model_id))
        return out

    def summary(self):
        "The whole policy in one block, for `/model` with no argument, including anything that moved."
        rows = []
        for j in JOBS:
            try: row = model_note(self.spec(j))
            except Exception as e: row = f'unavailable ({agent_err(e)})'
            rows.append(f'{j:11} {row}' + (f'  [{self.notes[j]}]' if j in self.notes else ''))
        return '\n'.join(rows)
