"""The error type, the environment convention, and the model policy.

Docs: https://vedicreader.github.io/ramabana/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ENV_PREFIX', 'ENV_FALLBACK', 'AgentError', 'JOBS', 'ONESHOT_JOBS', 'LOCAL', 'MLX', 'LLAMA', 'GPT', 'CLOUD',
           'CLAUDE_MODELS', 'CLAUDE_ALIASES', 'CLAUDE', 'DFLT_AGENT_CTX', 'CLAUDE_CTX', 'RUNTIME_NAMES', 'AGENTS',
           'HOSTED', 'COPILOT_UNAVAILABLE', 'CUSTOM', 'RUNTIME_REMEDY', 'MODELS', 'PII_OFF', 'PII_MODES', 'PROBE_TTL',
           'PROBE_DIR', 'HARNESS', 'EXTRAS', 'SCRIPTS', 'DFLT_LOCAL', 'completer', 'cheap', 'DEFAULT_POLICY',
           'DFLT_LOCAL_CTX', 'PREFIXES', 'RETIRED', 'SMALL_CTX', 'TOOL_MAX_FLOOR', 'FRUGAL_DROP', 'TAGS_SCHEMA_TOKENS',
           'PROFILES', 'SMALL_PROFILE_CTX', 'SMALL_TOOLS', 'API_KEYS', 'MODEL_ALIASES', 'TOOL_CHANNELS',
           'BranchChanged', 'agent_err', 'use_env_prefix', 'env', 'claude_ctx', 'probe_path', 'probed', 'forget_probes',
           'runtime_remedy', 'runtime_detail', 'runtime_available', 'installed', 'need', 'auth_status',
           'copilot_catalog', 'available_models', 'local_window', 'local_ctx', 'ModelSpec', 'unknown_model', 'resolve',
           'spec_caps', 'accepts', 'model_note', 'Budget', 'budget_for', 'profile_for', 'register_model',
           'unregister_model', 'alias_path', 'saved_models', 'load_models', 'save_model', 'delete_model', 'force_tags',
           'forget_forced_tags', 'tool_channel', 'Routing']

# %% ../nbs/00_core.ipynb #41a0b203
import difflib, functools, importlib, importlib.util, json, os, platform, re, shutil, subprocess, sys, threading, time
from fastcore.all import Path, atomic_save
from shalya.host import HostError
import urai, rishi.core   # registers rishi's backends with urai
from .models import CATALOG, claude_ids, claude_aliases, provider_models
from dataclasses import dataclass, field

# %% ../nbs/00_core.ipynb #2049138c
ENV_PREFIX, ENV_FALLBACK = 'RAMABANA_', 'LEELA_'

AgentError = HostError
class BranchChanged(AgentError): "A branch moved while a person decided on it, so nothing was written."

def agent_err(e):
    "Render a caught exception for a user-facing surface, keeping its type."
    return f'{type(e).__name__}: {e}'

def use_env_prefix(prefix, fallback=None):
    "Set the env var prefixes this application reads, most specific first."
    global ENV_PREFIX, ENV_FALLBACK
    ENV_PREFIX = prefix if prefix.endswith('_') else prefix + '_'
    if fallback is not None: ENV_FALLBACK = fallback if fallback.endswith('_') else fallback + '_'
    return ENV_PREFIX, ENV_FALLBACK

def env(name, dflt=None):
    "Read `$<prefix><name>`, then `$<fallback><name>`, else `dflt`."
    return os.environ.get(ENV_PREFIX+name) or os.environ.get(ENV_FALLBACK+name) or dflt

# %% ../nbs/00_core.ipynb #9df3b26a
JOBS = ('turn', 'oneshot', 'inline', 'completion', 'classify', 'summary', 'subagent')
ONESHOT_JOBS = ('oneshot', 'completion', 'classify', 'inline')
LOCAL = {'gemma-e2b': 'litert-community/gemma-4-E2B-it-litert-lm','gemma-e4b': 'litert-community/gemma-4-E4B-it-litert-lm','gemma-12b': 'litert-community/gemma-4-12B-it-litert-lm'}
MLX = {'qwen-4b': 'mlx-community/Qwen3.5-4B-MLX-4bit','mini-coder-4b': 'mlx-community/mini-coder-4b-OptiQ-4bit','ornith-9b': 'mlx-community/Ornith-1.0-9B-8bit'}
LLAMA = {'llama-qwen-0.6b': 'Qwen/Qwen3-0.6B-GGUF','llama-qwen-1.7b': 'Qwen/Qwen3-1.7B-GGUF','llama-qwen-4b': 'Qwen/Qwen3-4B-GGUF'}
GPT = {name: f'openai/{name}' for name in ('gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano','gpt-5.4', 'gpt-5.4-mini', 'gpt-5.6', 'gpt-5.6-luna', 'gpt-5.6-sol', 'gpt-5.6-terra')}
GPT.update({name: f'codex/{name}' for name in ('gpt-5.3-codex-spark', 'gpt-5.5')})
CLOUD = {**GPT, 'gpt': GPT['gpt-5.6-terra'],'gpt-mini': GPT['gpt-5.6-luna'], 'gpt-sol': GPT['gpt-5.6-sol']}
CLAUDE_MODELS = claude_ids()
CLAUDE_ALIASES = {**{mid: mid for mid in CLAUDE_MODELS}, **claude_aliases()}
CLAUDE = {f'claude/{name}': mid for name, mid in CLAUDE_ALIASES.items()}
DFLT_AGENT_CTX = 128_000
CLAUDE_CTX = {'claude-opus': 200_000, 'claude-sonnet': 200_000}
RUNTIME_NAMES = tuple(urai.RUNTIMES)
AGENTS = ('claude',)
HOSTED = ('remote', 'copilot', *AGENTS)
COPILOT_UNAVAILABLE = ('copilot runtime is unavailable; sign in to Copilot in an editor or run `python -c "from rishi.copilot import copilot_login; copilot_login()"`')
CUSTOM = {}
_RUNTIME_DEPS = {'litert': 'litert_lm', 'mlx': 'mlx_lm', 'llama': 'llama_cpp'}
RUNTIME_REMEDY = {
    'remote': 'hosted models need an API key in the environment',
    'claude': 'install Claude Code (https://claude.com/claude-code) and run `claude /login`',
    'copilot': 'sign in to GitHub Copilot in an editor, or run `copilot_login()` from rishi.copilot',
    'litert': 'LiteRT ships with rishi; reinstall it with `pip install --upgrade rishi`',
}
MODELS = {**{k: ('litert', v) for k, v in LOCAL.items()}, **{k: ('mlx', v) for k, v in MLX.items()},**{k: ('llama', v) for k, v in LLAMA.items()},**{k: ('claude', v) for k, v in {**CLAUDE, **CLAUDE_ALIASES}.items()},**{k: ('remote', v) for k, v in CLOUD.items()}}
PII_OFF = 'off'
PII_MODES = (PII_OFF, 'redact', 'refuse')

# %% ../nbs/00_core.ipynb #68d2ad3a
def claude_ctx(model_id):
    "A Claude Code model's context window, else `DFLT_AGENT_CTX`."
    mid = str(model_id or '')
    return next((c for p, c in CLAUDE_CTX.items() if mid.startswith(p)), DFLT_AGENT_CTX)

# %% ../nbs/00_core.ipynb #07efd167
PROBE_TTL = 90                                  #: seconds
PROBE_DIR = Path('~/.config/ramabana/probes')
_PROBED, _probe_lock = {}, threading.Lock()
_probe_gen = 0

def probe_path(key, dir=None):
    "Where one probe's last answer is kept between runs."
    return Path(dir or PROBE_DIR).expanduser()/f"{re.sub(r'[^A-Za-z0-9_.-]', '_', str(key))}.json"

def _read_probe(key, dir):
    "The answer a previous run left, or None if missing or malformed."
    try: return json.loads(probe_path(key, dir).read_text())['value']
    except Exception: return None

def _write_probe(key, value, dir):
    p = probe_path(key, dir)
    try:
        with atomic_save(p, 'w') as f: f.write(json.dumps({'at': time.time(), 'value': value}))
    except Exception: pass

def _keep(key, value, gen, dir, disk):
    "Store an answer, unless `forget_probes` ran since it was gathered."
    # under the lock, or an in-flight refresh recreates a file `forget_probes` removed
    with _probe_lock:
        if gen != _probe_gen: return
        _PROBED[key] = {'at': time.time(), 'value': value, 'busy': False}
        if disk: _write_probe(key, value, dir)

def probed(key, fn, ttl=PROBE_TTL, dir=None, disk=True):
    "`fn()`'s last answer, refreshing a stale one in the background."
    with _probe_lock: row, gen = _PROBED.get(key), _probe_gen
    if row is None and disk and (kept := _read_probe(key, dir)) is not None:
        row = {'at': 0.0, 'value': kept, 'busy': False}
        with _probe_lock:
            if gen == _probe_gen: _PROBED[key] = row
    if row is None:
        value = fn()
        _keep(key, value, gen, dir, disk)
        return value
    if time.time() - row['at'] < ttl or row['busy']: return row['value']
    row['busy'] = True
    def again():
        try: _keep(key, fn(), gen, dir, disk)
        except Exception:
            with _probe_lock: row['at'], row['busy'] = time.time(), False
    threading.Thread(target=again, daemon=True, name=f'ramabana-probe-{key}').start()
    return row['value']

def forget_probes(disk=False, dir=None):
    "Drop every cached answer, and with `disk` its file too."
    global _probe_gen
    with _probe_lock:
        keys, _probe_gen, _ = list(_PROBED), _probe_gen+1, _PROBED.clear()
        if not disk: return
        for key in keys:
            try: probe_path(key, dir).unlink(missing_ok=True)
            except Exception: pass

# %% ../nbs/00_core.ipynb #de745a4a
HARNESS = {'claude': ('rishi.claude', 'claude_bin'), 'copilot': ('rishi.copilot', 'copilot_oauth')}

def _harness_detail(mod, binary):
    "Empty when an agent harness can be reached; otherwise what stopped it."
    try: m = importlib.import_module(mod)
    except Exception as e: return f'import {mod}: {agent_err(e)}'
    try: return '' if getattr(m, binary)() else f'{binary}() found nothing'
    except Exception as e: return f'{binary}(): {agent_err(e)}'

def _harness_available(mod, binary):
    "Whether an agent harness can be reached: its module imports, and the binary its SDK spawns."
    return not _harness_detail(mod, binary)

# %% ../nbs/00_core.ipynb #8f978b99
def _claude_available(): return _harness_available(*HARNESS['claude'])

# %% ../nbs/00_core.ipynb #ae0f2158
def _copilot_available():
    "Whether Copilot is reachable, from its OAuth token and editor config, offline."
    return _harness_available(*HARNESS['copilot'])

# %% ../nbs/00_core.ipynb #3613bae4
def runtime_remedy(runtime):
    "One sentence saying what to do about a runtime that cannot be reached here."
    return RUNTIME_REMEDY.get(runtime, f'install the backend with `pip install rishi[{runtime}]`')

def runtime_detail(runtime):
    "Why a harness runtime cannot be reached, or `''` when it can."
    mod, binary = HARNESS.get(runtime) or (None, None)
    return _harness_detail(mod, binary) if mod else ''

# %% ../nbs/00_core.ipynb #3af627ce
@functools.lru_cache(maxsize=1)
def _ollama_available():
    "Whether ollama can serve here: the daemon is answering, or its binary is on hand."
    try:
        from rishi.ollama import OllamaClient, ollama_bin
        try: return bool(OllamaClient().models() is not None)
        except Exception: return bool(ollama_bin())
    except Exception: return False

# %% ../nbs/00_core.ipynb #174500b5
def runtime_available(runtime):
    "Whether Rishi's optional dependency for `runtime` can be reached. Never raises."
    if runtime == 'remote': return True
    if runtime == 'claude': return _claude_available()
    if runtime == 'copilot': return _copilot_available()
    if runtime == 'ollama': return _ollama_available()
    try: return importlib.util.find_spec(_RUNTIME_DEPS[runtime]) is not None
    except (ImportError, KeyError, ValueError): return False

# %% ../nbs/00_core.ipynb #2b914187
#: the modules of each extra that ramabana imports
EXTRAS = dict(search=('vishalakshi', 'litesearch', 'kosha', 'rgapi', 'fossick'),
              python=('dhrishti', 'jupyter_client'),
              serve=('mcp', 'acp'),
              cli=('teleprint', 'fastpylight'),
              dhrona=('dhrona',))

def installed(mod):
    "Whether `mod` would import, without importing it."
    try: return importlib.util.find_spec(mod) is not None
    except (ImportError, ValueError): return False

def need(extra, *mods):
    "`''` when `mods`, by default all of `extra`'s, are installed; else what to install."
    miss = [m for m in mods or EXTRAS[extra] if not installed(m)]
    return f"{', '.join(miss)} not installed: pip install 'ramabana[{extra}]'" if miss else ''

#: console scripts: the module whose `main` runs, its extra, and the modules it needs
SCRIPTS = dict(run_cli=('cli', 'cli', ()), run_mcp=('mcp', 'serve', ('mcp',)), run_acp=('racp', 'serve', ('acp',)))

def _refuse(msg):
    "A console script that prints `msg` and exits 2."
    def main():
        print(msg, file=sys.stderr)
        return 2
    return main

def __getattr__(name):
    "The `main` a console script in `SCRIPTS` calls itself, so `call_parse` reads the command line; or one naming the missing extra."
    if name not in SCRIPTS: raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
    mod, extra, mods = SCRIPTS[name]
    return _refuse(msg) if (msg := need(extra, *mods)) else importlib.import_module(f'ramabana.{mod}').main

# %% ../nbs/00_core.ipynb #9881cc3b
def _json_has(path, *keys):
    "Whether nested keys in a JSON file are present and truthy."
    try:
        from fastcore.basics import nested_idx
        return bool(nested_idx(Path(path).expanduser().read_json(), *keys))
    except Exception: return False

def _claude_login():
    "Whether Claude Code is logged in, from status metadata only."
    if not shutil.which('claude'): return False
    try:
        p = subprocess.run(['claude', 'auth', 'status', '--json'], capture_output=True, text=True, timeout=3)
        return p.returncode == 0 and bool(json.loads(p.stdout).get('loggedIn'))
    except Exception: return False

def auth_status():
    'Credential sources FastLLM can use, without reading or returning any secret.'
    codex = bool(os.getenv('CODEX_AUTH_TOKEN') or _json_has(os.getenv('CODEX_AUTH_PATH', '~/.codex/auth.json'), 'tokens', 'access_token'))
    claude_login = _claude_login() and _claude_available()
    copilot = _copilot_available()
    return {
        'openai': {'available': bool(os.getenv('OPENAI_API_KEY')), 'source': 'OPENAI_API_KEY'},
        'codex': {'available': codex, 'source': 'Codex login' if codex else ''},
        'anthropic': {'available': bool(os.getenv('ANTHROPIC_API_KEY')), 'source': 'ANTHROPIC_API_KEY'},
        'claude': {'available': claude_login, 'source': 'Claude Code login' if claude_login else ''},
        'gemini': {'available': bool(os.getenv('GEMINI_API_KEY')), 'source': 'GEMINI_API_KEY'},
        'copilot': {'available': copilot, 'source': 'GitHub Copilot sign-in' if copilot else ''},
    }

# %% ../nbs/00_core.ipynb #56303cec
def _copilot_catalog():
    try:
        from rishi.copilot import copilot_catalog as cat
        return cat()
    except Exception: return {}

def copilot_catalog(ttl=300):
    "Copilot's catalogue for this account, cached: `{id: entry}`, or `{}` when it cannot be reached."
    return probed('copilot-catalog', _copilot_catalog, ttl=ttl, disk=False)

def _copilot_chat_models():
    "Chat ids this Copilot plan can reach, queried rather than tabled."
    return [i for i, m in copilot_catalog().items() if (m.get('capabilities') or {}).get('type') == 'chat']

def available_models(include_legacy=False):
    "Models selectable here, with older generations only when `include_legacy`."
    rows = []
    for runtime, models in (('litert', LOCAL), ('mlx', MLX), ('llama', LLAMA)):
        if not runtime_available(runtime): continue
        rows += [{'value': name, 'label': name, 'provider': runtime, 'source': f'on device via Rishi {runtime}'} for name in models]
    if runtime_available('ollama'):
        try:
            from rishi.ollama import OllamaClient
            for m in OllamaClient().models():
                rows.append({'value': f'ollama/{m}', 'label': m, 'provider': 'ollama', 'source': 'on device via the ollama daemon'})
        except Exception: pass
    if runtime_available('claude'):
        rows += [{'value': f'claude/{m}', 'label': m, 'provider': 'claude', 'source': 'Claude Code (CLI or SDK)'} for m in provider_models('claude', include_legacy)]
    if runtime_available('copilot'):
        for model in _copilot_chat_models():
            rows.append({'value': f'copilot/{model}', 'label': model, 'provider': 'copilot', 'source': 'GitHub Copilot subscription'})
    auth = auth_status()
    for vendor in ('openai', 'codex', 'gemini', 'anthropic'):
        if not auth[vendor]['available']: continue
        rows += [{'value': f'{vendor}/{m}', 'label': m, 'provider': vendor, 'source': auth[vendor]['source']} for m in provider_models(vendor, include_legacy)]
    seen, out = set(), []
    for row in rows:
        if row['value'] in seen: continue
        seen.add(row['value']); out.append(row)
    return out

# %% ../nbs/00_core.ipynb #70d7dfa3
DFLT_LOCAL = 'gemma-e4b'
completer = DFLT_LOCAL
cheap = completer

DEFAULT_POLICY = {'turn': None, 'oneshot': completer, 'inline': None, 'completion': None, 'classify': None, 'summary': None, 'subagent': 'gpt-4.1'}
_LOCAL_CTX = {'gemma-e2b': 16_384, 'gemma-e4b': 16_384, 'gemma-12b': 16_384, 'qwen-4b': 32_768, 'mini-coder-4b': 32_768, 'ornith-9b': 32_768, 'llama-qwen-0.6b': 32_768, 'llama-qwen-1.7b': 32_768, 'llama-qwen-4b': 32_768}
DFLT_LOCAL_CTX = 32_768


@functools.lru_cache(maxsize=64)
def local_window(runtime, model_id):
    "A local model's trained context window from its own config, else 0."
    try:
        if runtime == 'ollama':
            from rishi.ollama import OllamaClient
            info = OllamaClient().show(model_id).get('model_info') or {}
            return int(next((v for k, v in info.items() if k.endswith('.context_length')), 0) or 0)
        if runtime == 'mlx':
            from rishi.mlx import ctx_len, read_config
            return int(ctx_len(read_config(model_id), 0) or 0)
        if runtime == 'llama':
            from llama_cpp import Llama
            from rishi.llama import _get_model
            meta = Llama(_get_model(model_id), vocab_only=True, verbose=False).metadata
            return int(meta.get(f"{meta.get('general.architecture')}.context_length") or 0)
    except Exception: pass
    return 0

def local_ctx(name, dflt=DFLT_LOCAL_CTX):
    "How much of a local model to use: `$LEELA_LOCAL_CTX` if it says, else the table."
    if (ovr := (env('LOCAL_CTX') or '').strip()):
        if ovr.isdigit(): return int(ovr)
        for part in ovr.split(','):
            k, _, v = part.partition(':')
            if k.strip() == name and v.strip().isdigit(): return int(v)
    return _LOCAL_CTX.get(name, dflt)

# %% ../nbs/00_core.ipynb #64093121
class ModelSpec(urai.ModelSpec):
    "urai's `ModelSpec`, with `backend` and `config` as views of `runtime` and `opts`."
    @property
    def backend(self): return self.runtime
    @property
    def config(self): return self.opts
    @property
    def local(self): return self.rt.local if self.runtime in urai.RUNTIMES else self.runtime not in HOSTED

def _copilot_ctx(model_id):
    "Context window and a note for a Copilot model."
    lim = ((copilot_catalog().get(model_id) or {}).get('capabilities') or {}).get('limits') or {}
    if (n := lim.get('max_prompt_tokens') or lim.get('max_context_window_tokens')): return int(n), ''
    return _cloud_ctx(model_id)

def _cloud_ctx(model_id):
    "Context window and a note for a cloud model, from fastllm's tables."
    try:
        from fastllm.types import get_model_info
        v, _, m = model_id.partition('/')
        info = get_model_info(m or v, v if m else None)
        n = info.get('max_input_tokens') or info.get('max_tokens')
        if n: return int(n), ''
        return 128_000, 'context window unknown, assuming 128k'
    except Exception as e: return 128_000, f'context window unknown ({agent_err(e)}), assuming 128k'

# %% ../nbs/00_core.ipynb #1d37d28a
def unknown_model(name):
    near = difflib.get_close_matches(str(name), MODELS, n=2, cutoff=0.6)
    hint = f'; did you mean {" or ".join(repr(n) for n in near)}?' if near else '.'
    return (f'unknown model {name!r}{hint} `/models` lists what is configured, and any vendor/model spec works too.')

PREFIXES = RUNTIME_NAMES
RETIRED = {'claude_code': 'use `claude/` instead: the same models, through Claude Code itself', 'cursor': 'the Cursor backend was removed'}

def resolve(name, default_local=DFLT_LOCAL):
    'A `ModelSpec` for `name`: a short name from the tables, or any full `vendor/model` spec.'
    if not name: name = default_local
    if name in MODELS:
        backend, mid = MODELS[name]
        config = CUSTOM.get(name, {}).get('config', {})
        if backend not in ('remote', 'copilot'):
            if not runtime_available(backend): raise RuntimeError(f'{backend} runtime is unavailable; {runtime_remedy(backend)}')
            ctx = claude_ctx(mid) if backend == 'claude' else DFLT_AGENT_CTX if backend in AGENTS else local_ctx(name)
            return ModelSpec(name, backend, mid, ctx, opts=config)
        if backend == 'copilot':
            ctx, note = _copilot_ctx(mid)
            return ModelSpec(name, backend, mid, ctx, note, config)
        ctx, note = _cloud_ctx(mid)
        return ModelSpec(name, backend, mid, ctx, note, config)
    if re.match(r'^(?:claude-|(?:opus|sonnet|haiku|fable)-\d)', name):    # an untabled Claude id; Claude Code decides
        if not runtime_available('claude'): raise RuntimeError(f'claude runtime is unavailable; {runtime_remedy("claude")}')
        mid = name if name.startswith('claude-') else f'claude-{name}'
        return ModelSpec(name, 'claude', mid, claude_ctx(mid))
    if '/' in name:
        runtime, model_id = name.split('/', 1)
        if runtime in RETIRED: raise KeyError(f'{name!r}: the {runtime!r} prefix was removed -- {RETIRED[runtime]}')
        if runtime == 'copilot':
            if not runtime_available('copilot'): raise RuntimeError(COPILOT_UNAVAILABLE)
            ctx, note = _copilot_ctx(model_id)
            return ModelSpec(name, 'copilot', model_id, ctx, note)
        if runtime in ('litert', 'mlx', 'llama', 'ollama', *AGENTS):
            if not runtime_available(runtime): raise RuntimeError(f'{runtime} runtime is unavailable; {runtime_remedy(runtime)}')
            ctx = claude_ctx(model_id) if runtime == 'claude' else DFLT_AGENT_CTX if runtime in AGENTS else local_ctx(name)
            return ModelSpec(name, runtime, model_id, ctx)
        from urai import infer_runtime
        if (inferred := infer_runtime(name)) in ('litert', 'mlx', 'llama'):
            if not runtime_available(inferred): raise RuntimeError(f'{inferred} runtime is unavailable; {runtime_remedy(inferred)}')
            return ModelSpec(name, inferred, name, local_ctx(name))
        ctx, note = _cloud_ctx(name)
        return ModelSpec(name, 'remote', name, ctx, note)
    raise KeyError(unknown_model(name))

@functools.lru_cache(maxsize=256)
def _caps(model_id, runtime):
    "`urai.model_caps`, memoised."
    try:
        from urai import model_caps
        return model_caps(model_id, runtime=runtime)
    except Exception: return None

def spec_caps(spec):
    "What `spec`'s model accepts and what it hands back, or `None` where rishi cannot say."
    return _caps(spec.model_id, spec.backend if spec.local else 'remote')

def accepts(spec, kind):
    "Can `spec`'s model be sent `kind`? Unknown counts as yes."
    c = spec_caps(spec)
    return True if c is None or not c.known else c.accepts(kind)

def model_note(spec):
    "One line about a resolved model, for a status bar."
    where = 'local' if spec.local else 'cloud'
    out = f'{spec.name} · {where} · {spec.ctx//1000}k ctx'
    if (c := spec_caps(spec)) is not None and (m := c.fmt()): out += f' · {m}'
    return out + (f' · {spec.note}' if spec.note else '')

# %% ../nbs/00_core.ipynb #4e529923
SMALL_CTX = 24_000
TOOL_MAX_FLOOR = 1500    # chars
FRUGAL_DROP = ('memory', 'web')
TAGS_SCHEMA_TOKENS = 3300

@dataclass(frozen=True)
class Budget:
    'What a model can afford to be told, and to be sent back.'
    drop: tuple = ()         # capability groups to withhold from `tools_for`
    inline: bool = True      # whether the briefing may inline a skill body
    tool_max: int = 0        # chars one tool result may spend
    note: str = ''           # why, for a status bar

def budget_for(spec, tool_max, channel='native'):
    "A `Budget` sized to `spec`'s window, never above `tool_max`."
    ctx = getattr(spec, 'ctx', 0) or 0
    if ctx > 0 and channel == 'tags': ctx = max(1, ctx - TAGS_SCHEMA_TOKENS)
    if ctx <= 0 or ctx > SMALL_CTX: return Budget(tool_max=tool_max, note='full briefing')
    mx = min(tool_max, max(TOOL_MAX_FLOOR, (ctx//16)*4))
    return Budget(FRUGAL_DROP, False, mx, f'{ctx//1000}k window: no inlined skills, no {"/".join(FRUGAL_DROP)} tools, tool results clipped to {mx} chars')

# %% ../nbs/00_core.ipynb #baf2dbfe
PROFILES = ('auto', 'small', 'full')
SMALL_PROFILE_CTX = 32_000
SMALL_TOOLS = ('view_file', 'replace_text', 'create_file', 'ls', 'grep', 'search_code', 'run_shell', 'run_python',
               'git_status', 'git_diff', 'git_commit', 'notebook_cells', 'view_cell', 'edit_cell')

def profile_for(spec, profile='auto'):
    "Resolve `profile` for `spec`: `auto` is `small` for a local or small-window model."
    if profile not in PROFILES: raise ValueError(f'profile must be one of {", ".join(PROFILES)}, not {profile!r}')
    if profile != 'auto': return profile
    ctx = getattr(spec, 'ctx', 0) or 0
    return 'small' if getattr(spec, 'local', False) or 0 < ctx <= SMALL_PROFILE_CTX else 'full'


# %% ../nbs/00_core.ipynb #3e2adbad
def register_model(name, model_id, runtime=None, ctx=128_000, note='custom model', **config):
    "Register a configurable model alias for this process. `save_model` is the persistent form."
    name, model_id = (name or '').strip(), (model_id or '').strip()
    if model_id.startswith(('https://huggingface.co/', 'http://huggingface.co/')): 
        model_id = model_id.split('huggingface.co/', 1)[1].strip('/').split('/tree/', 1)[0]
    if not name: name = model_id.rsplit('/', 1)[-1]
    if not name or not model_id: raise ValueError('model name and model id are required')
    if runtime is None:
        from urai import resolve_runtime
        runtime, model_id = resolve_runtime(model_id)
    if runtime not in RUNTIME_NAMES: raise ValueError(f'unknown runtime {runtime!r}')
    if runtime != 'remote' and not runtime_available(runtime): raise RuntimeError(f'{runtime} runtime is unavailable; {runtime_remedy(runtime)}')
    MODELS[name] = (runtime, model_id); _LOCAL_CTX[name] = int(ctx or 128_000)
    CUSTOM[name] = {'name': name, 'model_id': model_id, 'runtime': runtime, 'ctx': int(ctx or 128_000), 'note': note, 'config': config}
    return resolve(name)

def unregister_model(name):
    "Remove one process-local configurable model alias."
    CUSTOM.pop(name, None); MODELS.pop(name, None); _LOCAL_CTX.pop(name, None)

# %% ../nbs/00_core.ipynb #17dbd05c
#: never a secret: `api_key_env` names the env var
API_KEYS = ('base_url', 'api_key_env', 'vendor_name', 'api_name')
MODEL_ALIASES = Path('~/.config/ramabana/models.json')

def alias_path(path=None):
    "The file one application keeps its model aliases in."
    return Path(path or MODEL_ALIASES).expanduser()

def saved_models(path=None):
    "The alias rows on disk, or `[]` if the file is missing or malformed."
    try: rows = json.loads(alias_path(path).read_text())
    except Exception: return []
    return rows if isinstance(rows, list) else []

def _write_aliases(rows, path=None):
    p = alias_path(path)
    with atomic_save(p, 'w') as f: f.write(json.dumps(rows, indent=2)+'\n')

def load_models(path=None):
    "Register every saved alias that still resolves, and return those rows."
    out = []
    for row in saved_models(path):
        try:
            cfg = {k: row.get(k) for k in API_KEYS if row.get(k)}
            spec = register_model(row.get('name'), row.get('model_id'), row.get('runtime'),
                                  row.get('ctx', 128_000), 'saved model', **cfg)
            out.append({**row, 'name': spec.name, 'model_id': spec.model_id, 'runtime': spec.runtime, 'ctx': spec.ctx})
        except Exception: continue
    return out

def save_model(row, path=None):
    "Validate, register and persist one alias. Returns the row as written."
    name = str(row.get('name') or '').strip()
    model_id = str(row.get('model_id') or '').strip()
    runtime = str(row.get('runtime') or '').strip()
    if not re.match(r'^[A-Za-z0-9][\w.-]{0,63}$', name): raise ValueError('name must use letters, numbers, _, . or -')
    if runtime not in RUNTIME_NAMES: raise ValueError(f'runtime must be one of {", ".join(RUNTIME_NAMES)}')
    if name in MODELS and name not in CUSTOM: raise ValueError(f'{name!r} is a built-in model name')
    ctx = int(row.get('ctx') or 128_000)
    if not 1024 <= ctx <= 10_000_000: raise ValueError('context must be between 1,024 and 10,000,000 tokens')
    cfg = {k: str(row.get(k) or '').strip() for k in API_KEYS if row.get(k)}
    if runtime != 'remote' and cfg: raise ValueError('API settings apply only to the remote runtime')
    spec = register_model(name, model_id, runtime, ctx, 'saved model', **cfg)
    clean = {'name': name, 'model_id': spec.model_id, 'runtime': runtime, 'ctx': ctx, **cfg}
    _write_aliases([x for x in saved_models(path) if x.get('name') != name] + [clean], path)
    return clean

def delete_model(name, path=None):
    "Forget one alias, on disk and in this process."
    _write_aliases([x for x in saved_models(path) if x.get('name') != name], path)
    unregister_model(name)
    return name

# %% ../nbs/00_core.ipynb #1e5cd7ee
TOOL_CHANNELS = ('native', 'tags')
_forced_tags = {}

def force_tags(model_id, why=''):
    "Record that this model's tools cannot travel on the wire here."
    why = why or 'the wire tool channel was refused'
    _forced_tags[str(model_id)] = why
    return why

def forget_forced_tags():
    "Forget which models were forced onto tags, so the wire is tried again."
    _forced_tags.clear()

def tool_channel(spec, chat=None):
    "The channel ('native' or 'tags') a model's tool schemas travel on."
    if (v := (env('TOOL_CHANNEL') or '').strip().lower()) in TOOL_CHANNELS: return v
    if (ch := getattr(chat, 'tool_channel', None)) in TOOL_CHANNELS: return ch
    mid = str(getattr(spec, 'model_id', spec) or '')
    rt = getattr(spec, 'runtime', '') or (mid.split('/', 1)[0] if '/' in mid else '')
    if rt in AGENTS: return 'tags'
    if mid in _forced_tags: return 'tags'
    return 'native'

# %% ../nbs/00_core.ipynb #e81acb32
@dataclass
class Routing:
    "Job -> model: the policy, and the one place that decides what runs where."
    turn: str = None
    policy: dict = field(default_factory=lambda: dict(DEFAULT_POLICY))
    default_local: str = DFLT_LOCAL

    def __post_init__(self):
        if not self.turn: self.turn = env('MODEL') or self.default_local
        for job in JOBS:
            if (v := env(f'MODEL_{job.upper()}')): self.policy[job] = v
        self._cache, self.notes = {}, {}

    def name_for(self, job='turn'):
        "The model name for `job`: its policy, then `oneshot` for a cheap job, then `turn`."
        if job == 'turn': return self.turn
        if (n := self.policy.get(job)): return n
        if job in ONESHOT_JOBS and (n := self.policy.get('oneshot')): return n
        return self.turn

    def _resolve(self, name):
        "Resolve `name`, cached."
        if name not in self._cache: self._cache[name] = resolve(name, self.default_local)
        return self._cache[name]

    def alternatives(self, job):
        "Where `job` goes when its own model is not on this machine, best first."
        seen, out = {self.name_for(job)}, []
        for alt in (self.policy.get('oneshot') if job in ONESHOT_JOBS else None,
                    self.turn, *(self.policy.get(j) for j in JOBS), self.default_local):
            if alt and alt not in seen:
                seen.add(alt); out.append(alt)
        return out

    def spec(self, job='turn', fallback=True):
        "The `ModelSpec` for `job`, on another model when its own is not installed."
        n = self.name_for(job)
        try: return self._resolve(n)
        except Exception as e:
            if not fallback or job == 'turn': raise
            for alt in self.alternatives(job):
                try: spec = self._resolve(alt)
                except Exception: continue
                self.notes[job] = f'{n} unavailable ({agent_err(e)}); using {alt}'
                return spec
            raise

    def set(self, name, job='turn'):
        "Validate `name`, then point `job` at it."
        spec = resolve(name, self.default_local)
        if job == 'turn': self.turn = name
        else: self.policy[job] = name
        self._cache[name] = spec
        return spec

    def backends(self):
        "The distinct backend/model pairs this policy needs."
        out = set()
        for j in JOBS:
            try: s = self.spec(j)
            except Exception: continue
            out.add((s.backend, s.model_id))
        return out

    def summary(self):
        "The whole policy in one block, with any fallbacks, for a bare `/model`."
        rows = []
        for j in JOBS:
            try: row = model_note(self.spec(j))
            except Exception as e: row = f'unavailable ({agent_err(e)})'
            rows.append(f'{j:11} {row}' + (f'  [{self.notes[j]}]' if j in self.notes else ''))
        return '\n'.join(rows)
