"""User Python that registers more tools, skills, commands and hooks.

Docs: https://vedicreader.github.io/ramabana/extensions.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_extensions.ipynb.

# %% auto #0
__all__ = ['EVENTS', 'Registry', 'ext_dirs', 'load']

# %% ../nbs/12_extensions.ipynb #ex_imports
import runpy
from pathlib import Path
from .core import agent_err

# %% ../nbs/12_extensions.ipynb #ex_00
# The events an extension can hook. Small on purpose: both backends already have rich
# callback systems, and this is the seam for the *harness's* lifecycle, not the engine's.
EVENTS = ('before_turn', 'after_turn', 'before_tool', 'after_tool', 'compact', 'approval')

# %% ../nbs/12_extensions.ipynb #ex_01
class Registry:
    """What `setup(ext)` is handed: everything an extension may add, and nothing else.

    `host` and `agent` are exposed because an extension that cannot read a file or see the
    conversation is not worth writing. What is deliberately *not* here is any way to reach
    a backend's internals -- an extension that pokes at a litert conversation would break
    on the next model switch, and would break silently.
    """

    def __init__(self, host=None, agent=None):
        self.host, self.agent = host, agent
        self.tools, self.skills, self.commands = [], [], {}
        self.hooks = {e: [] for e in EVENTS}
        self.approve = None
        self.notes = []          # one line per extension: loaded, or why not

    # -- registration --------------------------------------------------------
    def tool(self, f):
        """Add a tool. Usable as a decorator.

        The contract is the backends' own: a plain function with type hints and a
        docstring. That docstring is what the model reads, so it is documentation and not
        a comment.
        """
        self.tools.append(f)
        return f

    def skill(self, name, text, description=''):
        "Add a skill the discovery pass would not find -- a file, a string, anything callable."
        from ramabana.skills import Skill, _describe
        s = Skill(name=name, source='ext', description=description or _describe(text if isinstance(text, str) else ''),
                  where='extension', _text=text)
        self.skills.append(s)
        return s

    def command(self, name, fn, help=''):
        "Add a slash command. `fn(agent, arg)` returns text for the frontend to show."
        self.commands[name.lstrip('/')] = (fn, help)
        return fn

    def on(self, event, fn):
        "Hook a harness lifecycle event. Unknown event names are an error, not a silent no-op."
        if event not in EVENTS: raise KeyError(f'unknown event {event!r}; known: {", ".join(EVENTS)}')
        self.hooks[event].append(fn)
        return fn

    def approval(self, fn):
        "Replace the approval policy wholesale. The last extension to call this wins."
        self.approve = fn
        return fn

    # -- dispatch ------------------------------------------------------------
    def fire(self, event, *args, **kw):
        "Run every hook for `event`, swallowing failures. Returns how many ran cleanly."
        n = 0
        for f in self.hooks.get(event, ()):
            try: f(*args, **kw); n += 1
            except Exception as e: self.notes.append(f'{event} hook failed: {agent_err(e)}')
        return n

# %% ../nbs/12_extensions.ipynb #ex_02
def ext_dirs(roots=(), cfg=None, project=False):
    "Where extensions are looked for. Project directories only when explicitly allowed."
    ds = []
    if cfg is not None: ds.append(Path(cfg)/'extensions')
    if project:
        for r in roots: ds.append(Path(r)/'.leela'/'extensions')
    return ds

# %% ../nbs/12_extensions.ipynb #ex_03
def load(reg, roots=(), cfg=None, project=False, paths=()):
    """Run every extension found, calling its `setup(reg)`. Returns the registry.

    A file with no `setup` is loaded and left alone rather than reported as broken: that is
    how a shared helper module sitting in the same directory should behave.
    """
    files = []
    for d in ext_dirs(roots, cfg, project):
        if Path(d).is_dir(): files += sorted(p for p in Path(d).glob('*.py') if not p.name.startswith('_'))
    for p in paths or ():
        p = Path(p)
        files += sorted(p.glob('*.py')) if p.is_dir() else [p]
    for f in files:
        try:
            ns = runpy.run_path(str(f))
        except Exception as e:
            reg.notes.append(f'{f.name}: failed to load ({agent_err(e)})')
            continue
        fn = ns.get('setup')
        if not callable(fn):
            reg.notes.append(f'{f.name}: loaded, no setup()')
            continue
        before = (len(reg.tools), len(reg.skills), len(reg.commands))
        try: fn(reg)
        except Exception as e:
            reg.notes.append(f'{f.name}: setup() failed ({agent_err(e)})')
            continue
        d = [n - b for n, b in zip((len(reg.tools), len(reg.skills), len(reg.commands)), before)]
        reg.notes.append(f'{f.name}: {d[0]} tool(s), {d[1]} skill(s), {d[2]} command(s)')
    return reg
