"""The approval hook fastllm does not have, written the way it should be added upstream.

Docs: https://vedicreader.github.io/ramabana/fastllm_hitl.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_fastllm_hitl.ipynb.

# %% auto #0
__all__ = ['PATCHED_ATTR', 'applied', 'note', 'apply']

# %% ../nbs/07_fastllm_hitl.ipynb #fh_imports
from .core import agent_err
from .hitl import DENIED, _tc

# %% ../nbs/07_fastllm_hitl.ipynb #fh_00
PATCHED_ATTR = '_leela_hitl'      # set on fastllm.chat once, so applying twice is free

# %% ../nbs/07_fastllm_hitl.ipynb #fh_01
_note = 'not attempted'

# %% ../nbs/07_fastllm_hitl.ipynb #fh_02
def applied():
    "Whether fastllm currently has the approval hook, without importing it if it is absent."
    import sys
    m = sys.modules.get('fastllm.chat')
    return bool(m is not None and getattr(m, PATCHED_ATTR, False))

# %% ../nbs/07_fastllm_hitl.ipynb #fh_03
def note():
    "Why the patch is or is not in place. Shown next to the model in the IDE's status."
    return _note

# %% ../nbs/07_fastllm_hitl.ipynb #fh_04
def apply():
    """Give `fastllm.AsyncChat` an `approve` callback. Returns True when it is in place.

    Never raises. fastllm being absent is an ordinary state for a leela install that only
    ever runs local models, and an editor that will not open because a cloud provider
    stack is missing is a worse editor.
    """
    global _note
    try:
        import fastllm.chat as fc
    except Exception as e:
        _note = f'fastllm not available ({agent_err(e)})'
        return False
    if getattr(fc, PATCHED_ATTR, False):
        _note = 'approval hook installed'
        return True
    try:
        _patch(fc)
    except Exception as e:
        _note = f'approval hook could not be installed ({agent_err(e)}); cloud tool calls are ungated'
        return False
    setattr(fc, PATCHED_ATTR, True)
    _note = 'approval hook installed'
    return True

# %% ../nbs/07_fastllm_hitl.ipynb #fh_05
def _patch(fc):
    """The three-line change itself, isolated so the diff to send upstream is obvious.

    Upstream these would be an `approve=None` parameter on `AsyncChat.__init__`, a
    `@patch(as_prop=True)` on `tcdict`, and an edited `_alite_call_func`. From outside the
    package `@patch` cannot be used for `tcdict`: it reads the `self:AsyncChat` annotation
    to find its target, and under `from __future__ import annotations` that name would
    have to be resolvable in *this* module's globals -- which would mean importing fastllm
    at import time, exactly what the lazy loading elsewhere is avoiding. A direct property
    assignment says the same thing without the ceremony.
    """
    from fastllm.chat import AsyncChat, _call_func, _mk_tool_result
    from toolslm.funccall import call_func_async
    from fastcore.utils import maybe_await

    # (1) Default: no policy, i.e. exactly today's behaviour.
    if not hasattr(AsyncChat, 'approve'): AsyncChat.approve = None

    # (2) Thread the policy to where the calls are made. `tcdict` is already the carrier
    #     for everything `_alite_call_func` needs, so there is no new plumbing.
    AsyncChat.tcdict = property(lambda self: dict(
        tool_schemas=self.tool_schemas, ns=self.ns, approve=getattr(self, 'approve', None)))

    # (3) The gate. Signature-compatible with the original, so an un-patched caller that
    #     passes only the old three arguments still works.
    async def _alite_call_func(tc, tool_schemas, ns, approve=None):
        "Call a tool asynchronously, unless `approve(tc)` says not to."
        ok = True
        if approve is not None:
            try: ok = approve(tc)
            except Exception as e: return f'{DENIED}. The approval policy failed: {agent_err(e)}'
            if not ok: return _decision_text(ok) or DENIED
        res = _call_func(tc, tool_schemas, ns, call_func_async)
        out = _mk_tool_result(await maybe_await(res))
        # An approval can come with a condition attached ("yes, but keep the docstring").
        # That is guidance the model needs *while* it works, so it rides back on the result.
        if (said := _decision_text(ok)): out = f'{out}\n\n{said}'
        return out

    fc._alite_call_func = _alite_call_func

# %% ../nbs/07_fastllm_hitl.ipynb #fh_06
def _decision_text(ok):
    """Whatever the policy wanted to say about its decision, or ''.

    A policy may return a plain bool -- in which case there is nothing to say and the
    canned refusal stands -- or an object with `reply()`, which is how `hitl.Ask` carries
    the reason a person gave. Anything that raises while explaining itself is ignored: a
    broken message must not turn an answered approval into a failed tool call.
    """
    r = getattr(ok, 'reply', None)
    if not callable(r): return ''
    try: return r() or ''
    except Exception: return ''
