"""Ramabana's tools, and Ramabana's whole agent, as an MCP server.

## The server

With an agent, the tools mounted here are the very objects a turn gets. The recorded wrappers. A client's call lands in the same activity feed and the same `changes()` a turn does. `functools.wraps` in `Agent._record` kept their signatures and docstrings, and that is exactly what FastMCP reads to build a schema. There is no second description of any tool anywhere and nothing to drift. Without an agent the tools are built straight off the host.

`readonly` defaults to True because the client is another agent whose approval UI this server does not control. Writes are one flag away, and should be gated the usual way when they are mounted.

## Skills as resources

Skills are resources rather than tools, because that is what they are: text a client can read, not a call with an effect. The index is one resource and each skill is another. A client can list what is available and fetch only the one it needs. The same economy `read_skill` gives a model in a turn.

## The agent as one tool

With an agent passed in, the server also offers `ask`: a whole Ramabana turn behind a single call. The client spends one question and one answer. The tool loop, the tool results and the compaction all happen on this side and are discarded.

## Running it

`ramabana-mcp` on the command line. `--model` is what turns the `ask` tool on: without a model there is nothing to delegate to. The server offers tools only.

Docs: https://vedicreader.github.io/ramabana/mcp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_mcp.ipynb.

# %% auto #0
__all__ = ['UNSAFE', 'INSTRUCTIONS', 'server', 'main']

# %% ../nbs/06_mcp.ipynb #6322b4c6
import json
from pathlib import Path
import anyio
from fastcore.script import call_parse
from mcp.server.fastmcp import FastMCP
from mcp.types import ToolAnnotations
from .tools import WRITE_TOOLS, LocalHost, discover, find, skill_index, tools_for
from .cli import mk_agent, mk_host

# %% ../nbs/06_mcp.ipynb #6d6ba498
UNSAFE = WRITE_TOOLS | {'delegate_search', 'delegate_parallel'}

INSTRUCTIONS = """Ramabana's tools over the folders this server was started on.

`search_code` and `view_file` are the way in: file views are `lineno|hash|content`, and those
hashes are the addresses `edit_file` takes, so an edit built on a stale view fails instead of
damaging the wrong line. Notebooks are addressed by cell id (`notebook_cells`, then
`view_cell`/`edit_cell`), never by line. `ask` hands a whole task to Ramabana's own agent and
returns just its answer."""


def _annotate(name):
    "MCP's hints about a tool. A client can style and gate it without guessing from the name."
    return ToolAnnotations(readOnlyHint=name not in UNSAFE,
                           destructiveHint=name in WRITE_TOOLS,
                           idempotentHint=name not in WRITE_TOOLS,
                           openWorldHint=name in ('web_search', 'read_url', 'research'))

# %% ../nbs/06_mcp.ipynb #87a9e0ed
def server(host=None, agent=None, name='ramabana', readonly=True, delegate=True, **kw):
    """An MCP server over one host's tools, and optionally over Ramabana's own agent.

    The tools are the same objects the model gets in a turn. FastMCP reads their own
    signatures. `readonly` by default: the client is an agent whose approval UI is not ours.
    """
    host = host if host is not None else LocalHost()
    mcp = FastMCP(name, instructions=INSTRUCTIONS, **kw)
    skills = discover(host.roots, getattr(agent, 'cfg', None)) if agent is None else agent.skills
    # the agent's own recorded tools when there is one. A client's call reaches its feed
    every = agent.tools if agent is not None else tools_for(host, get_skills=lambda: skills)
    mounted = []
    for tool in every:
        nm = getattr(tool, '__name__', '')
        if readonly and nm in UNSAFE: continue
        mcp.add_tool(tool, annotations=_annotate(nm))
        mounted.append(nm)

    @mcp.resource('skill://{name}', mime_type='text/markdown')
    def skill(name: str) -> str:
        "One skill in full, by name. The same text `read_skill` returns in a turn."
        s = find(skills, name)
        return f'no skill matching {name!r}' if s is None else s.text()

    @mcp.resource('ramabana://skills', mime_type='text/markdown')
    def skill_list() -> str:
        "Every skill this server can read, with the one-line description of when it applies."
        return skill_index(skills) or 'no skills found'

    @mcp.resource('ramabana://status', mime_type='application/json')
    def status() -> str:
        "What is loaded: folders, model, tools, skills, and anything that has gone wrong."
        out = {'roots': list(host.roots), 'tools': mounted, 'skills': [s.name for s in skills]}
        if agent is not None: out['agent'] = agent.status()
        return json.dumps(out, default=str, indent=2)

    if agent is not None and delegate: _mount_ask(mcp, agent)
    return mcp

# %% ../nbs/06_mcp.ipynb #71696cad
def _mount_ask(mcp, agent):
    "Add the `ask` tool: one whole Ramabana turn, with only its answer coming back."

    @mcp.tool(annotations=ToolAnnotations(readOnlyHint=False, openWorldHint=True))
    async def ask(task: str) -> str:
        """Hand a whole task to Ramabana's agent and get back only its answer.

        Use this when answering would take many tool calls whose results you do not need to
        keep. "where else do we do X", "what does this module actually do", "make this
        change and tell me what you changed". Ramabana runs its own tool loop with its own
        model. This costs you one question and one answer.

        Ask one self-contained task: this agent cannot see your conversation.
        """
        return await anyio.to_thread.run_sync(agent.ask, task)

# %% ../nbs/06_mcp.ipynb #9ceb572b
@call_parse
def main(
    root: str = '.',                 # folders to serve, comma separated
    model: str = None,               # the model `ask` runs on. Omit to serve tools only
    write: bool = False,             # mount the write tools too
    web: bool = True,                # let the web tools reach the network through fossick
    read_outside: bool = False,      # let reads name any path on this machine. Writes stay inside
    vault: bool = False,             # keep what is read in a vishalakshi vault, for the next session
    transport: str = 'stdio',        # stdio | sse | streamable-http
    cfg: str = None,                 # config dir, for skills and extensions
):
    "Serve Ramabana tools over MCP."
    roots = [r.strip() for r in str(root).split(',') if r.strip()]
    if model:
        agent, host = mk_agent(roots, model=model, approve='none', web=web, vault=vault,
                               read_outside=read_outside,
                               cfg=Path(cfg).expanduser() if cfg else None)
    else:
        agent, host = None, mk_host(roots, web=web, vault=vault, read_outside=read_outside)
    server(host, agent, readonly=not write).run(transport=transport)
