"""A Python prompt you own, and an agent in the layer above it.

Docs: https://vedicreader.github.io/ramabana/pyrepl.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_pyrepl.ipynb.

# %% auto #0
__all__ = ['ExecOutcome', 'output_text']

# %% ../nbs/11_pyrepl.ipynb #pyr0004
import asyncio, codeop, json, os, queue, shutil, sys, tempfile, threading, urllib.parse, urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from rich.text import Text
from .core import agent_err
from .tools import LocalHost, WRITE_TOOLS
from .agent import Agent, Approvals
from .cli import Ui, GRUVBOX, HELP

# %% ../nbs/11_pyrepl.ipynb #pyr0006
@dataclass
class ExecOutcome:
    "One kernel request in nbformat's output shape."
    ok: bool = True
    outputs: list = field(default_factory=list)
    execution_count: int | None = None
    error: str | None = None

def output_text(outputs):
    "Flatten notebook outputs for tests, logs and plain terminal fallbacks."
    parts = []
    for out in outputs:
        kind = out.get('output_type')
        if kind == 'stream': parts.append(_text(out.get('text')))
        elif kind in ('execute_result', 'display_data'):
            data = out.get('data') or {}
            parts.append(_text(data.get('text/plain') or data.get('text/markdown')))
        elif kind == 'error':
            trace = out.get('traceback') or []
            parts.append('\n'.join(trace) if trace else f"{out.get('ename')}: {out.get('evalue')}")
    return '\n'.join(p.rstrip('\n') for p in parts if p is not None)

def _text(value):
    return ''.join(value) if isinstance(value, list) else str(value or '')
