"""A Python prompt you own, and an agent in the layer above it.

Docs: https://vedicreader.github.io/ramabana/pyrepl.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_pyrepl.ipynb.

# %% auto #0
__all__ = ['PY_HELP', 'PY_GUIDE', 'ExecOutcome', 'output_text', 'Kernel', 'DhrishtiHost', 'annotate', 'mk_pyagent',
           'find_session', 'amain', 'main', 'hl', 'run_code', 'run_agent', 'PyreplUi', 'code_state', 'promote']

# %% ../nbs/11_pyrepl.ipynb #pyr0004
import asyncio, codeop, json, os, queue, re, shutil, sys, tempfile, urllib.parse, urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from rich.text import Text
from .core import agent_err
from .tools import LocalHost, WRITE_TOOLS
from .agent import Agent, Approvals
from .cli import Ui, GRUVBOX, HELP, attach_refs, key_card, run_turn

# %% ../nbs/11_pyrepl.ipynb #pyr0006
@dataclass
class ExecOutcome:
    "One kernel request in nbformat's output shape."
    ok: bool = True
    outputs: list = field(default_factory=list)
    execution_count: int | None = None
    error: str | None = None

def output_text(outputs):
    "Flatten notebook outputs for tests, logs and plain terminal fallbacks."
    parts = []
    for out in outputs:
        kind = out.get('output_type')
        if kind == 'stream': parts.append(_text(out.get('text')))
        elif kind in ('execute_result', 'display_data'):
            data = out.get('data') or {}
            parts.append(_text(data.get('text/plain') or data.get('text/markdown')))
        elif kind == 'error':
            trace = out.get('traceback') or []
            parts.append('\n'.join(trace) if trace else f"{out.get('ename')}: {out.get('evalue')}")
    return '\n'.join(p.rstrip('\n') for p in parts)

def _text(value):
    return ''.join(value) if isinstance(value, list) else str(value or '')

# %% ../nbs/11_pyrepl.ipynb #pyr0009
class Kernel:
    "A private ipykernel with Dhrishti serving its live namespace."
    def __init__(self, cwd='.'):
        self.cwd = Path(cwd).resolve()
        self.km = self.kc = None
        self.base = None
        self._ipc_dir = None
        self._exec_lock = asyncio.Lock()
        self._shell_lock = asyncio.Lock()

    @property
    def alive(self):
        return self.km is not None and self.kc is not None and self.km.has_kernel

    async def start(self, timeout=60):
        from jupyter_client.kernelspec import KernelSpec
        from jupyter_client.manager import AsyncKernelManager
        opts = {'kernel_name': 'python3'}
        if os.name != 'nt':
            self._ipc_dir = tempfile.mkdtemp(prefix='rama-k-', dir='/tmp' if os.path.isdir('/tmp') else None)
            opts.update(transport='ipc', ip=os.path.join(self._ipc_dir, 'k'))
        self.km = AsyncKernelManager(**opts)
        self.km._kernel_spec = KernelSpec(
            argv=[sys.executable, '-m', 'ipykernel_launcher', '-f', '{connection_file}'],
            display_name='Ramabana PyREPL', language='python')
        try:
            await self.km.start_kernel(cwd=str(self.cwd))
            self.kc = self.km.client()
            self.kc.start_channels()
            await self.kc.wait_for_ready(timeout=timeout)
            await self._bootstrap()
            return self
        except BaseException:
            await self.shutdown()
            raise

    async def _bootstrap(self):
        root = self.cwd/'.ramabana'/'pyrepl'
        # '<project>-pyrepl-<pid>', sanitised because --attach is where a human types it
        proj = re.sub(r'[^a-z0-9]+', '-', (self.cwd.name or 'ramabana').lower()).strip('-') or 'ramabana'
        source = (
            'def _ramabana_bootstrap():\n'
            ' import dhrishti.serving as ds, os\n'
            f' p = ds.serve_in_kernel(name={proj!r} + "-pyrepl-" + str(os.getpid()), agent="restricted", token=True, '
            f'session_dir={str(root/"sessions")!r}, agent_session_dir={str(root/"agents")!r})\n'
            ' print("__RAMABANA_DHRISHTI__" + str(p))\n'
            '_ramabana_bootstrap()\n'
            'del _ramabana_bootstrap')
        result = await self.execute(source, store_history=False)
        marker = next((line for out in result.outputs if out.get('output_type') == 'stream'
                       for line in _text(out.get('text')).splitlines()
                       if line.startswith('__RAMABANA_DHRISHTI__')), '')
        if not result.ok or not marker:
            raise RuntimeError(result.error or output_text(result.outputs) or 'Dhrishti did not start')
        self.base = f'http://127.0.0.1:{int(marker.removeprefix("__RAMABANA_DHRISHTI__"))}'

    async def execute(self, code, store_history=True, on_output=None):
        "Execute one cell and stream each nbformat-shaped output to `on_output`."
        if not self.alive: return ExecOutcome(ok=False, error='kernel is not running')
        async with self._exec_lock, self._shell_lock:
            msg_id = self.kc.execute(str(code), store_history=store_history, allow_stdin=False)
            outputs = await self._collect(msg_id, on_output)
            reply = await self._reply(msg_id)
        content = (reply or {}).get('content') or {}
        error = None
        if content.get('status') == 'error': error = f"{content.get('ename')}: {content.get('evalue')}"
        elif content.get('status') == 'abort': error = 'aborted'
        if error is None:
            err = next((o for o in outputs if o.get('output_type') == 'error'), None)
            if err: error = f"{err.get('ename')}: {err.get('evalue')}"
        return ExecOutcome(error is None, outputs, content.get('execution_count'), error)

    async def _collect(self, msg_id, on_output):
        outputs, displays = [], {}
        while True:
            try: message = await self.kc.get_iopub_msg(timeout=.5)
            except (queue.Empty, asyncio.TimeoutError):
                if not self.alive: break
                continue
            if (message.get('parent_header') or {}).get('msg_id') != msg_id: continue
            kind, content = message['header']['msg_type'], message['content']
            if kind == 'status' and content.get('execution_state') == 'idle': break
            if kind == 'clear_output': outputs.clear(); displays.clear(); continue
            out = self._output(kind, content)
            if out is None: continue
            display_id = (content.get('transient') or {}).get('display_id')
            if kind == 'update_display_data' and display_id in displays:
                outputs[displays[display_id]] = out
            elif (out['output_type'] == 'stream' and outputs and outputs[-1].get('output_type') == 'stream'
                  and outputs[-1].get('name') == out.get('name')):
                outputs[-1]['text'] += out['text']
            else:
                outputs.append(out)
                if display_id: displays[display_id] = len(outputs) - 1
            if on_output: on_output(out)
        return outputs

    @staticmethod
    def _output(kind, content):
        if kind == 'stream':
            return {'output_type': 'stream', 'name': content.get('name', 'stdout'), 'text': content.get('text', '')}
        if kind == 'error':
            return {'output_type': 'error', 'ename': content.get('ename', ''),
                    'evalue': content.get('evalue', ''), 'traceback': list(content.get('traceback') or [])}
        if kind in ('execute_result', 'display_data', 'update_display_data'):
            return {'output_type': 'execute_result' if kind == 'execute_result' else 'display_data',
                    'data': content.get('data') or {}, 'metadata': content.get('metadata') or {}}
        return None

    async def _reply(self, msg_id):
        while True:
            try: message = await self.kc.get_shell_msg(timeout=10)
            except (queue.Empty, asyncio.TimeoutError): return None
            if (message.get('parent_header') or {}).get('msg_id') == msg_id: return message

    async def complete(self, code, pos):
        if not self.alive: return [], int(pos)
        async with self._shell_lock:
            msg_id = self.kc.complete(str(code), int(pos))
            while True:
                message = await self.kc.get_shell_msg(timeout=10)
                if (message.get('parent_header') or {}).get('msg_id') == msg_id:
                    content = message.get('content') or {}
                    return content.get('matches') or [], int(content.get('cursor_start', pos))

    async def interrupt(self):
        if self.km: await self.km.interrupt_kernel()

    async def shutdown(self, timeout=5):
        if self.kc:
            try: self.kc.stop_channels()
            except Exception: pass
        if self.km and self.km.has_kernel:
            # a dhrishti kernel may never agree to `now=False`, so the ask has a deadline
            try: await asyncio.wait_for(self.km.shutdown_kernel(now=False), timeout)
            except Exception:
                try: await self.km.shutdown_kernel(now=True)
                except Exception: pass
        self.km = self.kc = self.base = None
        if self._ipc_dir:
            shutil.rmtree(self._ipc_dir, ignore_errors=True)
            self._ipc_dir = None

# %% ../nbs/11_pyrepl.ipynb #pyr0013
def _api(base, path, params=None, timeout=60):
    query = urllib.parse.urlencode(params or {})
    url = base.rstrip('/') + path + (('?' + query) if query else '')
    with urllib.request.urlopen(url, timeout=timeout) as response:
        return json.loads(response.read())

class DhrishtiHost(LocalHost):
    "A project host whose Python tools use a protected Dhrishti overlay."
    def __init__(self, roots, base, **kwargs):
        super().__init__(roots, **kwargs)
        self.base = base
        try: info = _api(base, '/agent/api/info')
        except Exception: info = {}
        log = (info or {}).get('log')
        self.agent_log = Path(log) if log else None   # None, not `Path('')`, which is truthy

    def run_python(self, code):
        return self.inspect_python(code, 'overlay')   # always the overlay; scope is model-settable

    def inspect_python(self, code, scope='isolated'):
        if scope not in self.scopes: return f'this host only honours {self.scopes}'
        try: result = _api(self.base, '/agent/api/exec', {'code': str(code), 'scope': scope})
        except Exception as exc: return agent_err(exc)
        if result.get('error'): return str(result['error'])
        out = result.get('stdout') or ''
        value = result.get('result')
        if isinstance(value, dict): value = value.get('value')
        if value is not None: out += ('\n' if out else '') + str(value)
        return out or '(ok)'

    @property
    def scopes(self): return ('isolated', 'overlay')

    @property
    def kernel_kind(self): return 'ipykernel'

    def list_vars(self):
        try: result = _api(self.base, '/agent/api/rows', {'profile': 'minimal', 'sort': 'name'})
        except Exception as exc: return agent_err(exc)
        return '\n'.join(f"{node.get('name')}: {node.get('type')} = {node.get('value')}"
                         for group in result.get('groups', []) for node in group.get('nodes', []))

    def log_cell(self, source, outputs=None, cell_type='code'):
        "Append a human Python or model markdown turn to Dhrishti's session notebook."
        # read/append/write per cell: the owner's kernel writes this file too
        if self.agent_log is None: return
        from fastcore.nbio import read_nb, write_nb, new_nb, mk_cell
        self.agent_log.parent.mkdir(parents=True, exist_ok=True)
        nb = read_nb(self.agent_log) if self.agent_log.exists() else new_nb([])
        cell = mk_cell(str(source), cell_type)
        if cell_type == 'code':
            cell['outputs'], cell['execution_count'] = list(outputs or []), None
        nb.cells.append(cell)
        write_nb(nb, self.agent_log)

    def describe(self):
        "name -> 'type [shape]' for everything the session is holding. Never raises."
        try: result = _api(self.base, '/agent/api/rows', {'profile': 'minimal', 'sort': 'name'}, timeout=2)
        except Exception: return {}
        out = {}
        for group in result.get('groups', []):
            for node in group.get('nodes', []):
                if name := node.get('name'):
                    value = node.get('value')   # falsy is still a value; only a missing key is not
                    out[name] = str(value if value is not None else (node.get('type') or ''))
        return out

# %% ../nbs/11_pyrepl.ipynb #619771e3
def annotate(matches, described):
    "Candidate names with their type and shape where the session knows one."
    # exact names only: `df.copy` is a method on a binding, not a binding
    return [f'{m} → {described[m]}' if m in described else m for m in matches]

# %% ../nbs/11_pyrepl.ipynb #pyr0017
def mk_pyagent(roots, base, model=None, approve='ask', web=True, read_outside=False, cfg=None):
    "Build an agent whose Python tools target the Dhrishti session at `base`."
    approvals = None if approve == 'none' else Approvals(tools=WRITE_TOOLS, mode=approve)
    host = DhrishtiHost(roots, base, approvals=approvals, web=web, read_outside=read_outside)
    if approvals is not None: approvals.host = host   # the gate previews `create_file` via the host
    agent = Agent(host, model=model, approvals=approvals, cfg=cfg)
    return agent, host

# %% ../nbs/11_pyrepl.ipynb #pyr0901
def _ambiguous(attach, cands):
    "Error text for a name that matches more than one live session -- list them, do not pick."
    rows = '; '.join(f"{e.get('name')} (cwd={e.get('cwd')}, port={e.get('port')})" for e in cands)
    return f'{attach!r} matches more than one live dhrishti session, refusing to guess which: {rows}'

def find_session(attach):
    "The base URL of a live Dhrishti session named `attach`, or `attach` itself if it is a URL."
    attach = str(attach).strip()
    if '://' in attach: return attach
    from dhrishti.serving import active   # the registry, not `serve_in_kernel`, which would re-serve
    entries = active()
    exact = [e for e in entries if e.get('name') == attach]
    if len(exact) > 1: raise RuntimeError(_ambiguous(attach, exact))
    hit = exact[0] if exact else None
    # a name that is not an exact match is tried as a project prefix, anchored at '-pyrepl-'
    if hit is None and attach:
        prefixed = [e for e in entries if str(e.get('name') or '').startswith(attach + '-pyrepl-')]
        if len(prefixed) > 1: raise RuntimeError(_ambiguous(attach, prefixed))
        hit = prefixed[0] if prefixed else None
    if hit is None and attach:
        # The whole basename, not a substring, so 'leela' does not also match 'old-leela-backup'.
        by_cwd = [e for e in entries if Path(str(e.get('cwd') or '')).name == attach]
        if len(by_cwd) > 1: raise RuntimeError(_ambiguous(attach, by_cwd))
        hit = by_cwd[0] if by_cwd else None
    if hit is None: raise RuntimeError(
        f'no live dhrishti session matching {attach!r}; running: '
        f'{", ".join(str(e.get("name")) for e in entries) or "none"}')
    return hit.get('base') or f'http://127.0.0.1:{hit["port"]}'

# %% ../nbs/11_pyrepl.ipynb #pyr0018
async def amain(roots=('.',), model=None, approve='ask', web=True, read_outside=False,
                 cfg=None, resume='', attach=''):
    "Run the combined Ramabana Python and agent session, or attach to a session someone else owns."
    from teleprint.compositor import Compositor
    from teleprint.tty import RealTty
    tty = RealTty(); tty.write('\x1b[?2004h')   # bracketed paste on, mouse off, as in `cli.amain`
    done = asyncio.Event()
    kernel = agent = None
    try:
        kernel = None if attach else await Kernel(roots[0]).start()   # attaching starts nothing
        base = find_session(attach) if attach else kernel.base
        agent, host = mk_pyagent(roots, base, model, approve, web, read_outside, cfg)
        if resume: agent.resume_session(resume)
        comp = await Compositor(tty).start()
        ui = PyreplUi(comp, agent, kernel, asyncio.get_running_loop()) if kernel else Ui(comp, agent, asyncio.get_running_loop())
        if kernel:
            ui.hint = f"{', '.join(host.roots)} · /agent asks · /python executes · /help"
        else:
            ui.hint = f"{', '.join(host.roots)} · attached to {base} · /help"
        comp.on_task_error = lambda exc, task: ui.say(Text(f'{task.get_name()} failed: {exc!r}'), 'error')
        comp.spawn(ui.animate(), name='spinner')
        def on_key(key):
            out = ui.on_key(key)
            if out == 'quit': return done.set()
            if out is not None:
                ui.turn = comp.spawn(out, name='pyrepl')
                ui.paint()
        comp.on_key, comp.on_paste = on_key, ui.paste
        comp.on_resize = lambda: (comp.resize(), ui.paint())
        comp.on_mouse = ui.transcript.on_mouse
        if kernel:
            subtitle = "Python owns the kernel; agent Python uses Dhrishti's protected overlay."
        else:
            subtitle = f"Attached to {base}; the human's Python prompt belongs to whoever started it."
        ui.say(Text('RAMABANA PYREPL', style=f"bold {GRUVBOX['fg0']}") +
               Text(f"\n\n{subtitle}", style=GRUVBOX['gray']),
               'note', fold=None)
        ui.paint()
        loop = asyncio.get_running_loop(); loop.add_reader(tty.fd, lambda: comp.on_bytes(tty.read(timeout=0)))
        try:
            while not done.is_set():
                try: await asyncio.wait_for(done.wait(), .2)
                except asyncio.TimeoutError: comp.flush_input()
        finally:
            loop.remove_reader(tty.fd); comp.stop()
    finally:
        tty.write('\x1b[?2004l\x1b[?1000;1006l\r\n'); tty.restore()
        if agent is not None: agent.close()
        if kernel is not None: await kernel.shutdown()

# %% ../nbs/11_pyrepl.ipynb #pyr0019
def main(root:str='.',                     # folders the agent may touch, comma separated
         model:str=None,                   # the turn model; the routing default when omitted
         approve:str='ask',                # ask | auto | off | none
         web:bool=True,                    # let the web tools reach the network
         read_outside:bool=False,          # let reads name any path; writes stay inside
         cfg:str='~/.config/ramabana',     # config dir for skills, extensions and history
         resume:str='',                    # saved session id/prefix, or 'latest'
         attach:str=''):                   # a live dhrishti session by name or base URL
    "Start `ramabana pyrepl` with the normal Ramabana model and project options."
    roots = [item.strip() for item in str(root).split(',') if item.strip()]
    config = Path(cfg).expanduser() if cfg else None
    try: return asyncio.run(amain(roots, model, approve, web, read_outside, config, resume, attach))
    except KeyboardInterrupt: return None
    except RuntimeError as exc:   # `find_session` refuses in a sentence written for a human
        print(exc, file=sys.stderr)
        return 2

# %% ../nbs/11_pyrepl.ipynb #ab902e2b
def hl(src):
    "`src` as highlighted `Text` with `.plain == src`, or plain `Text` if pygments cannot lex it."
    src = str(src)
    if not src: return Text('')
    try:
        from rich.syntax import Syntax
        # `highlight` appends a newline; it is built for whole files
        out = Syntax(src, 'python', theme='gruvbox-dark').highlight(src)
        while out.plain.endswith('\n'): out.right_crop(1)
        return out if out.plain == src else Text(src)
    except Exception: return Text(src)

# %% ../nbs/11_pyrepl.ipynb #6491d734
PY_HELP = """pyrepl  /agent ask Ramabana · /python run Python · tab complete · ctrl-c interrupt/stop
/vars what the session holds · /promote <name> adopt an agent variable · /guide how this works
""" + HELP

async def run_code(ui, code):
    "Run one user-owned Python cell, streaming outputs into Teleprint blocks."
    result = None
    try:
        result = await ui.kernel.execute(code, on_output=ui.on_output)
        if not result.ok and not result.outputs: ui.say(Text(result.error or 'execution failed'), 'error')
    finally:
        ui.turn = None
        ui.paint()
    # after the cleanup, not inside it: a log that raises must not wedge the prompt
    if result is not None: ui.agent.host.log_cell(code, result.outputs)

async def run_agent(ui, prompt):
    "One `cli.run_turn`, with both halves of it written into Dhrishti's session notebook."
    ui.agent.host.log_cell('**user**\n\n' + prompt, cell_type='markdown')
    blk = await run_turn(ui, prompt)
    if ui._reply: ui.agent.host.log_cell('**assistant**\n\n' + ui._reply, cell_type='markdown')
    return blk


class PyreplUi(Ui):
    "The ordinary Ramabana terminal with an additional user-owned Python mode."
    CONT = '...      '   # nine cells, like both mode labels, so indentation reads at its real depth

    def __init__(self, comp, agent, kernel, loop=None):
        self.kernel, self.mode, self.matches = kernel, 'python', None
        super().__init__(comp, agent, loop)

    def guide(self): return PY_GUIDE + super().guide()

    def status(self):
        out = super().status()
        out.append(f'  · {self.mode}', style=GRUVBOX['aqua'] if self.mode == 'python' else GRUVBOX['blue'])
        return out

    def _label(self):
        "The label ahead of the buffer's first line."
        return 'python › ' if self.mode == 'python' else 'agent  › '

    def _prefixed(self, text):
        "`text` with the mode label on its first line and `CONT` on every line after it."
        if self.ask is not None: return self.ASKING + text
        return self._label() + text.replace('\n', '\n' + self.CONT)

    def prompt(self):
        if self.ask is not None: return super().prompt()
        color = GRUVBOX['aqua'] if self.mode == 'python' else GRUVBOX['blue']
        label = self._label()
        # `allow_blank=True` keeps the trailing empty row of a buffer awaiting its blank line
        if self.mode == 'python':
            body = Text('\n' + self.CONT, style=GRUVBOX['fg0']).join(
                hl(self.buf.text).split('\n', allow_blank=True))
        else:
            body = Text(self.buf.text.replace('\n', '\n' + self.CONT), style=GRUVBOX['fg0'])
        return Text(label, style=f'bold {color}') + body

    def tail(self):
        rows, (row, line_no, col) = super().tail()
        if self.matches:
            rows.insert(-1, Text('  '.join(self.matches[:8]), style=GRUVBOX['gray']))
            row += 1
        return rows, (row, line_no, col)

    async def complete_python(self):
        "Kernel completion for the buffer, with the displayed list annotated from the namespace."
        # typing is not gated during the awaits, so the candidates are rechecked after each
        identity = (self.buf.text, self.buf.cursor)
        def stale(): return (self.buf.text, self.buf.cursor) != identity
        try:
            matches, start = await self.kernel.complete(self.buf.text, self.buf.cursor)
            if not matches or stale(): return
            common = os.path.commonprefix(matches)
            if len(matches) == 1 or len(common) > self.buf.cursor - start:
                self.buf.text = self.buf.text[:start] + common + self.buf.text[self.buf.cursor:]
                self.buf.cursor = start + len(common)
                identity = (self.buf.text, self.buf.cursor)   # our own edit, not the user moving on
            if len(matches) <= 1:
                self.matches = None
                return
            # bare names paint first: `describe` is synchronous HTTP
            self.matches = list(matches)
            self.paint()
            described = await asyncio.to_thread(self.agent.host.describe)
            if stale(): return
            self.matches = annotate(matches, described)
        finally:
            self.turn = None
            self.paint()

    def submit(self):
        "The mode switches, `/help` and `/promote` are ours; every other line goes to the base `Ui`."
        src, line = self.buf.text, self.buf.text.strip()
        self.complete = self.matches = None
        self.remember(line)
        if not line:
            self.buf.clear()
            return None
        if line in ('/agent', '/a', '/python', '/py'):
            self.buf.clear()
            self.mode = 'agent' if line in ('/agent', '/a') else 'python'
            return self.note(f'{self.mode} mode')
        if line in ('/help', '/?'):
            self.buf.clear()
            return self.say(key_card(PY_HELP), 'note', fold=None, source=PY_HELP)
        if line in ('/vars', '/v'):
            self.buf.clear()
            return self.note(self.agent.host.list_vars() or '(nothing bound yet)')
        if (parts := line.split())[0] in ('/promote', '/adopt'):
            self.buf.clear()
            if len(parts) != 2: return self.note('usage: /promote NAME')
            return self._promote(parts[1])
        if line.startswith('/'): return super().submit()
        if self.mode == 'python':
            # the raw buffer, not the stripped line, so an indented paste keeps its first row
            self.buf.clear()
            self.say(hl(src), 'user', source=src)
            return run_code(self, src)
        # `@path` attaches in an agent prompt only, which keeps `@` Python's own operator
        self.buf.clear()
        got = [self.attach(p) for p in attach_refs(line)]
        if got: self.note('\n'.join(got))
        self.say(Text(line), 'user')
        return run_agent(self, line)

    async def _promote(self, name):
        "Adopt one agent variable, off the loop thread: the owner-token call can take a minute."
        base = self.kernel.base if self.kernel else ''
        self.say(Text(await asyncio.to_thread(promote, base, name)), 'note', fold=None)
        self.turn = None
        self.paint()

    def on_output(self, output):
        kind = output.get('output_type')
        if kind == 'stream':
            text = _text(output.get('text')).rstrip('\n')
            if text: self.say(Text(text), 'note')
        elif kind in ('execute_result', 'display_data'):
            data = output.get('data') or {}
            if 'text/plain' in data: self.say(Text(_text(data['text/plain'])), 'reply')
            elif 'text/markdown' in data: self.say(Text(_text(data['text/markdown'])), 'reply')
            elif data: self.say(Text('display: ' + ', '.join(data)), 'note')
        elif kind == 'error':
            body = '\n'.join(output.get('traceback') or [])
            self.say(Text.from_ansi(body or f"{output.get('ename')}: {output.get('evalue')}"), 'error')

    def on_key(self, key):
        # a slash line is a command, not code, so neither branch below claims it
        pycode = (self.mode == 'python' and self.ask is None
                  and not self.buf.text.lstrip().startswith('/'))
        if key.name == 'tab' and pycode and self.turn is None and self.buf.text:
            return self.complete_python()
        # a typed suite grows the buffer instead of submitting it; `codeop` asks, not the kernel
        if key.name == 'enter' and pycode and self.menu is None and not self.transcript.active:
            src = self.buf.text
            # a blank line submits what is pending, as at any Python prompt
            if src.strip() and not src.endswith('\n\n'):
                state = code_state(src)
                if state == 'incomplete':
                    self.buf.insert('\n'); return self.paint()
                if state == 'invalid':
                    # Answered here rather than by the kernel: a syntax error costs no execution.
                    self.say(Text(f'incomplete or invalid: {_syntax_note(src)}'), 'error', fold=None)
                    return self.paint()
        # ctrl-c means "stop what is running", and in python mode that is a cell.
        if key.name == 'ctrl+c' and self.turn is not None and self.mode == 'python':
            self.comp.spawn(self.kernel.interrupt(), name='interrupt')
            self.buf.clear(); return self.paint()
        self.matches = None
        return super().on_key(key)


# %% ../nbs/11_pyrepl.ipynb #pyguide01
PY_GUIDE = """## Two prompts, one line

The line is Python by default. `/agent` hands it to Ramabana, `/python` hands it back, and the
label and its colour say which is live. Agent mode is the whole terminal described below, nothing
removed: the same blocks, folding, attachments, approvals and slash commands.

In python mode the code runs in a kernel that is yours. Enter submits a statement that compiles;
an unfinished one grows the buffer and shows a `...` continuation, so a `for` loop is typed the way
you would type it anywhere, and a blank line closes the suite. Something that will never compile is
said at the prompt rather than costing a round trip. tab completes through the kernel, which is
IPython's completer, and names the session is holding come back with their type and shape. ctrl+c
interrupts the running cell rather than the model. `/vars` lists what the session is holding, which is
the same view the agent gets when it calls `list_vars` -- that name is a tool it has and not a
builtin in your kernel, so ask for it with `/vars` rather than calling it.

## What the agent may do to your namespace

It reads freely and writes into a layer of its own. It cannot rebind or delete a name you made, and
that is enforced by Dhrishti, which serves the kernel, rather than by asking the model nicely. So
`df` stays yours; the agent's work shows up alongside it. `/promote NAME` adopts one of its
variables into your namespace, and it is a command rather than a tool because that decision is
yours.

Your cells and its turns are logged to one notebook as they happen, so a session is a single
artifact you can reopen.

## Attaching to a session you did not start

`ramabana pyrepl --attach NAME` joins a kernel that is already serving, which is what running
inside leela looks like. It starts nothing, offers no python mode, and never reads the owner token:
that surface belongs to whoever started the kernel. A name is `<project>-pyrepl-<pid>`, and the
project on its own is enough when only one such session is live. A base URL works too. When more
than one session could match it refuses and lists them rather than guessing.

"""

# %% ../nbs/11_pyrepl.ipynb #51d25204
def _compile_state(src, symbol):
    "`compile_command` as a (state, message) pair rather than three shapes of answer."
    try:
        code = codeop.compile_command(str(src), '<pyrepl>', symbol)
        return ('complete' if code is not None else 'incomplete'), ''
    except SyntaxError as e: return 'invalid', f'{e.msg} (line {e.lineno})'
    except Exception as e: return 'complete', agent_err(e)   # not ours to judge; let the kernel say

def _judge(src):
    "The prompt's verdict on `src`, and what objected when it was rejected."
    state, note = _compile_state(src, 'single')   # `'single'` is the question a REPL asks
    if state != 'invalid': return state, note
    return _compile_state(src, 'exec')            # ...but it also rejects two valid statements

def code_state(src):
    "Whether `src` is a finished statement, an unfinished one, or one that cannot compile."
    return _judge(src)[0]

def _syntax_note(src):
    "What the compile that rejected `src` objected to, in one line."
    return _judge(src)[1]

# %% ../nbs/11_pyrepl.ipynb #pyr0952
def promote(base, name):
    "Adopt an agent-layer variable into the owner namespace; own-kernel mode only."
    if not base: return 'no kernel of our own; promote from the surface that started the session'
    from dhrishti.serving import owner_token
    port = int(str(base).rsplit(':', 1)[-1])
    if (tok := owner_token(port)) is None: return f'no owner token for {base}; this session is not ours to change'
    try: result = _api(base, '/api/promote', {'accessor': json.dumps([str(name)]), 'token': tok})
    except Exception as exc: return agent_err(exc)
    return str(result.get('error') or f'promoted {name}')
