"""The first run: ramabana starts inside its own tmux server, offers to install tmux when it is missing, and `ramabana --doctor` says what it found.

Docs: https://vedicreader.github.io/ramabana/setup.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/19_setup.ipynb.

# %% ../nbs/19_setup.ipynb #6c9acc6f
from __future__ import annotations

import json, os, platform, re, shlex, shutil, subprocess, sys, uuid

from fastcore.all import Path, ifnone, patch, store_attr

from . import core

# %% auto #0
__all__ = ['SOCKET', 'WRAP_MIN', 'SPLIT_MIN', 'KEYS_MIN', 'TMUX_CONF', 'VERSIONED', 'HOLD', 'WHY', 'tmux_version', 'tmux_conf',
           'Setup']

# %% ../nbs/19_setup.ipynb #c674b32c
SOCKET, WRAP_MIN, SPLIT_MIN, KEYS_MIN = 'ramabana', (3, 0), (3, 1), (3, 2)
TMUX_CONF = r'''# ramabana writes this file and rewrites it when its own copy changes
if-shell 'infocmp tmux-256color' 'set -g default-terminal tmux-256color' 'set -g default-terminal screen-256color'
if-shell '[ "$COLORTERM" = truecolor ] || [ "$COLORTERM" = 24bit ]' "set -as terminal-overrides ',*:RGB'"
set -s escape-time 10
set -g mouse on
set -g status off
set -g remain-on-exit off
'''
VERSIONED = {KEYS_MIN: "set -s extended-keys on\nset -as terminal-features ',*:extkeys'",
             (3, 5): 'set -s extended-keys-format csi-u'}

def tmux_version(s):
    "The `(major, minor)` in `tmux -V` output such as `tmux 3.5a`, or None."
    return tuple(map(int, m.groups())) if (m := re.search(r'(\d+)\.(\d+)', s or '')) else None

def tmux_conf(version):
    "`TMUX_CONF` with the lines tmux `version` understands."
    return TMUX_CONF + ''.join(f'{l}\n' for v, l in VERSIONED.items() if version >= v)

# %% ../nbs/19_setup.ipynb #579428a9
HOLD = r'"$@" || { s=$?; printf "\nramabana exited with status %s · enter closes this\n" $s; read _; exit $s; }'
WHY = {'none': 'no tmux, and no brew, apt-get or dnf to install it', 'no': 'no tmux', 'yes': 'tmux did not install'}

class Setup:
    "The tmux ramabana runs in: its config, the relaunch into it, the install offer, and `--doctor`."
    def __init__(self,
        cfg='~/.config/ramabana', # holds `tmux.conf` and `setup.json`
        environ=None,             # default `os.environ`
        argv=None,                # the command line to rerun; default `sys.argv`
        cwd=None,                 # where the session starts; default the current folder
        which=shutil.which, system=platform.system, run=subprocess.run, execvpe=os.execvpe, ask=input,
        isatty=None,              # whether stdin and stdout are terminals
    ):
        store_attr('which,system,run,execvpe,ask')
        self.cfg, self.environ, self.argv = Path(cfg or '~/.config/ramabana').expanduser(), ifnone(environ, os.environ), ifnone(argv, sys.argv)
        self.cwd, self.isatty = cwd or os.getcwd(), isatty or (lambda: sys.stdin.isatty() and sys.stdout.isatty())

    def _env(self, name): return self.environ.get(core.ENV_PREFIX+name) or self.environ.get(core.ENV_FALLBACK+name)
    @property
    def tmux(self): return self.which('tmux')

    def about(self):
        "`tmux -V`, or '' without tmux."
        return self.run([t, '-V'], capture_output=True, text=True).stdout.strip() if (t := self.tmux) else ''

    def version(self):
        "The `(major, minor)` of tmux, `(99, 0)` for an unnumbered build, or None without tmux."
        return (tmux_version(a) or (99, 0)) if (a := self.about()) else None

    def conf(self):
        "Write `tmux_conf` for this tmux to `<cfg>/tmux.conf` when it differs, and return the path."
        p, text = self.cfg/'tmux.conf', tmux_conf(self.version() or (0, 0))
        if not p.exists() or p.read_text() != text: p.mk_write(text)
        return p

    def command(self):
        "The argv that reruns this command line: its script, else this Python."
        exe, *args = self.argv
        me = [exe] if os.path.isfile(exe) and os.access(exe, os.X_OK) else [sys.executable, '-c', 'import sys; from ramabana.cli import main; sys.exit(main())']
        return [*me, *args]

    def wrap(self):
        "The `execvpe` arguments that rerun `command` in a new session on ramabana's tmux server."
        env = {**self.environ, core.ENV_PREFIX+'WRAPPED': '1'}
        return self.tmux, ['tmux', '-L', SOCKET, '-f', str(self.conf()), 'set', '-g', 'update-environment', ' '.join(env), ';',
                           'new-session', '-s', f'ramabana-{uuid.uuid4().hex[:8]}', '-c', self.cwd,
                           'sh', '-c', HOLD, 'ramabana', *self.command()], env

    def launch(self,
        prompt='',     # a one-shot question stays in this terminal
        as_json=False, # so does `--json`
        tmux='auto',   # `--tmux`; `off` stays out of tmux
    ):
        "Before an interactive session: ready tmux, and rerun inside ramabana's own server when outside tmux."
        if prompt or as_json or not self.isatty() or 'off' in (tmux, self._env('TMUX')): return
        if self.environ.get('TMUX'): return self.ext_keys()
        if self._env('WRAPPED') or not (self.tmux or self.offer_install()) or (self.version() or (0,)) < WRAP_MIN: return
        self.execvpe(*self.wrap())

# %% ../nbs/19_setup.ipynb #235e735b
@patch
def installer(self:Setup):
    "The command that installs tmux here, or None."
    if self.system() == 'Darwin': return ['brew', 'install', 'tmux'] if self.which('brew') else None
    pm = next((p for p in ('apt-get', 'dnf') if self.which(p)), None) if self.system() == 'Linux' else None
    return pm and [*(['sudo'] if self.which('sudo') else []), pm, 'install', '-y', 'tmux']

@patch
def _seen(self:Setup):
    try: return (self.cfg/'setup.json').read_json()
    except (OSError, ValueError): return {}

@patch
def _yes(self:Setup, cmd):
    try: return self.ask(f'ramabana opens its now pane in tmux, which is missing. Run `{shlex.join(cmd)}`? [y/N] ').strip().lower() in ('y', 'yes')
    except (EOFError, KeyboardInterrupt): return False

@patch
def _installed(self:Setup, cmd):
    try: return self.run(cmd).returncode == 0 and bool(self.tmux)
    except OSError: return False

@patch
def offer_install(self:Setup, force=False):
    "Ask once, or again when `force`, to install tmux: True when tmux is there now."
    if not force and 'install_tmux' in self._seen(): return False
    ans = 'none' if (cmd := self.installer()) is None else 'yes' if self._yes(cmd) else 'no'
    (self.cfg/'setup.json').mk_write(json.dumps(self._seen() | {'install_tmux': ans}))
    if ans == 'yes' and self._installed(cmd): return True
    print(f'{WHY[ans]}; continuing without tmux · ramabana --doctor shows how to get the now pane', file=sys.stderr)
    return False

# %% ../nbs/19_setup.ipynb #3dd69e47
@patch
def _show_ext(self:Setup):
    "This tmux server's `extended-keys`, or '' when tmux cannot say."
    if not (t := self.tmux): return ''
    r = self.run([t, 'show', '-sv', 'extended-keys'], capture_output=True, text=True)
    return '' if r.returncode else r.stdout.strip()

@patch
def ext_keys(self:Setup):
    "Turn on `extended-keys` in the tmux server we run inside when it is off: True if turned on."
    if self._show_ext() != 'off': return False
    self.run([self.tmux, 'set', '-s', 'extended-keys', 'on'], capture_output=True)
    print('turned on extended-keys in this tmux server so shift+enter reaches ramabana; ~/.tmux.conf is unchanged', file=sys.stderr)
    return True

# %% ../nbs/19_setup.ipynb #883f4a12
@patch
def doctor(self:Setup):
    "Print one line per check, offer to install tmux when it is missing, and return 0."
    v, about, conf, pane = self.version(), self.about(), self.cfg/'tmux.conf', self.which('ramabana-pane')
    keys = f'{self._show_ext() or "unknown"} in this tmux' if self.environ.get('TMUX') else \
           f"{'on' if v and v >= KEYS_MIN else 'needs tmux 3.2+'} in ramabana's own tmux server"
    split = f'ok on {about}' if v and v >= SPLIT_MIN else 'needs tmux 3.1+' + (f', this is {about}; /pane prints a command to run instead' if v else '')
    print(f'tmux: {about} at {self.tmux}' if v else 'tmux: not found', f'split: {split}', f'extended-keys: {keys}',
          f'config: {conf}' + ('' if conf.exists() else ', written by the first session'),
          f'ramabana-pane: {pane}' if pane else 'ramabana-pane: not on PATH; the pane runs python -m ramabana.pane', sep='\n')
    if not v: self.offer_install(force=True)
    return 0
