"""The doubles: a host with no disk, backends with no model, and a script that behaves like a bad local engine.

## Specs

Two specs, and the window sizes are the whole point. `SPEC` is small because compaction
arithmetic is easier to check against 1000 tokens than against 200,000; `SCRIPTED` is big
because a screenshot must not have compaction firing across it.

## A host in memory

`MemHost` puts the open folders in a dict, so every file and search tool can be driven
without touching disk. It inherits `NullHost`, which means everything it does *not* define
is still absent -- and the tool list shrinks accordingly, which is the behaviour worth
testing.

## A host with everything

`LocalHost` is honest about what a terminal cannot do -- no research memory, no IDE
terminal, no overlay scope -- so `tools_for` drops those tools, which makes it a poor place
to test the tools it drops. `FullHost` fills each gap with a small real implementation over
in-process state: a remembered-pages index that genuinely searches, and a web that genuinely
returns the pages it was handed. Nothing reaches the network, and the folder is a fresh
temporary one, so a test or a docs page can write freely.

## A backend with no model

`FakeBackend` answers from a list. It is a real `Backend` subclass, so the lock, the usage
accounting, the problem list and the history replacement are the production ones -- only
the generation is fiction.

`fake_agent` wires one of these into a real `Agent`, with every job routed to it -- the
fastest way to drive a turn end to end.

## Compaction, end to end

With a fake backend and its 1000-token window, the whole compaction path runs: the threshold
is crossed, a summary is produced by the summary model, and the conversation is replaced by
that checkpoint plus the recent tail.

## A backend that mutters

The failure this harness exists for: a local engine that prints its complaint to a file
descriptor, returns an empty string, and raises nothing. `GEMMA` is real output, kept
verbatim, because the point is recognising the shape of the real thing rather than a tidied
version of it.

## A backend that performs

`ScriptedBackend` plays a list of `Step`s and streams its words one at a time. `token_delay`
is what makes a screenshot possible: at zero the turn finishes before the first repaint, and
every capture shows a completed answer -- the one thing a streaming screenshot must not
show. Its tool steps go through the agent's *real* tool list, so the activity feed, the
approval gate and the file snapshots all run for real.

## A real model with every tool

The doubles above prove control flow. This final check proves the assembled product: an
actual MLX model loaded through rishi, a `FullHost` with every capability, and every tool
installed in the model conversation. It runs from the recordings, so CI needs neither Apple
silicon nor a multi-gigabyte cache -- and because it *runs*, a tool added to the surface since
the last recording is caught here rather than going unnoticed in a stored output.

Docs: https://vedicreader.github.io/ramabana/testing.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_testing.ipynb.

# %% auto #0
__all__ = ['SPEC', 'SCRIPTED', 'CHATS', 'GEMMA', 'MemHost', 'FullHost', 'FakeBackend', 'fake_agent', 'recorded',
           'MutteringBackend', 'Step', 'ScriptedBackend']

# %% ../nbs/04_testing.ipynb #9b48cc52
import time, ramabana
from contextlib import contextmanager
from functools import partial
from pathlib import Path
from .core import AgentError, ModelSpec, agent_err, register_model
from .runtime import Backend, Usage
from .tools import AttrDict, Hit, LocalHost, NullHost
from .agent import Agent

# %% ../nbs/04_testing.ipynb #cbdc4d5f
SPEC = ModelSpec('fake', 'fake', 'fake/model', ctx=1000)

#: `ScriptedBackend`'s own spec, kept distinct because it is used for screenshots rather
#: than for tests -- a capture of the IDE should not have "fake" written across the status
#: bar, and its window has to be big enough that compaction does not fire mid-screenshot.
SCRIPTED = ModelSpec('scripted', 'scripted', 'scripted/model', ctx=8000)

# %% ../nbs/04_testing.ipynb #2ce479ad
class MemHost(NullHost):
    "A host whose folders live in a dict, so the file tools can be driven without touching disk."

    def __init__(self, files=None, root='/proj', commands=None):
        super().__init__([root])
        self.files, self.root = dict(files or {}), root
        self.ran, self.cmds = [], []
        # What a command is scripted to return: `{command: (exit_code, output)}`. Anything
        # not scripted exits 0 with no output, so a test that only cares *that* a command
        # ran does not have to describe one.
        self.commands = dict(commands or {})

    def run_cmd(self, command, cwd=None, timeout=120):
        if not str(command or '').strip(): return 0, ''      # the capability probe
        self.cmds.append((command, cwd, timeout))
        return self.commands.get(command, (0, ''))

    @property
    def shell_note(self): return 'scripted'

    def check(self, path, must_exist=False):
        p = Path(path)
        return p if p.is_absolute() else Path(self.root)/p

    def walk(self): return list(self.files)
    def read(self, path): return self.files.get(str(path))
    def text_at(self, path): return self.files.get(str(path), '')

    def write(self, path, text):
        self.files[str(path)] = text
        return str(path)

    def search(self, query, limit=20):
        return [Hit(p, 1, '', t.splitlines()[0]) for p, t in self.files.items() if query in t][:limit]

    @property
    def search_note(self): return 'memory'

    def run_python(self, code):
        self.ran.append(code)
        return 'ok'

# %% ../nbs/04_testing.ipynb #d107b5da
class FullHost(LocalHost):
    """A host with *every* capability present, over a throwaway folder.

    `LocalHost` is honest about what a terminal cannot do: it has no research memory, no
    IDE terminal and no overlay scope, so `tools_for` drops those tools. That makes it a
    poor place to test the tools it drops. `FullHost` fills each gap with a small real
    implementation over in-process state -- a remembered-pages index that genuinely
    searches, a web that genuinely returns the pages it was given -- so the whole tool
    surface can be driven, and every group's contract has somewhere to be checked.

    Nothing here reaches the network, and the folder is a fresh temporary one unless a root
    is given, so a test can write freely.
    """

    def __init__(self, files=None, pages=None, root=None, terminal='', **kw):
        import tempfile
        root = Path(root) if root else Path(tempfile.mkdtemp())/'proj'
        root.mkdir(parents=True, exist_ok=True)
        super().__init__([root], web=False, index=False, **kw)
        self.root = self.check('.')
        for path, text in (files or {}).items(): self.write(path, text)
        #: url -> markdown, the entire web this host knows about
        self.pages = dict(pages or {})
        self.transcript = [x for x in str(terminal).splitlines() if x]
        self.remembered = {}      # doc_id -> (title, url, markdown)
        self.notes = []           # everything `note` was told, for a test to assert on

    # -- the web, without a network -----------------------------------------
    def web_search(self, query, n=20):
        q = str(query).lower()
        hits = [(url, text) for url, text in self.pages.items()
                if q in url.lower() or q in text.lower()]
        return [AttrDict(title=text.strip().splitlines()[0].lstrip('# ').strip(), url=url)
                for url, text in hits[:int(n)]]

    def read_url(self, url, remember=True):
        text = self.pages.get(str(url))
        if text is None: return None
        if remember: self._remember_page(str(url), text)
        return AttrDict(text=text, url=str(url))

    def research(self, query):
        "Read every page that matches, into one cited digest -- what a real research pass returns."
        hits = self.web_search(query)
        if not hits: return ''
        parts = []
        for h in hits:
            page = self.read_url(h.url)
            parts.append(f'## {h.title}\n\n{page.text.strip()}\n\n[source: {h.url}]')
        return f'# {query}\n\n' + '\n\n'.join(parts)

    @property
    def research_note(self): return f'{len(self.pages)} page(s) in this host'

    # -- research memory, as a real tree ------------------------------------
    def _sections(self, text):
        "A markdown document split at its headings, which is the unit memory recalls."
        out, head, body = [], '', []
        for line in str(text).splitlines():
            if line.startswith('#'):
                if head or body: out.append((head, '\n'.join(body).strip()))
                head, body = line.lstrip('# ').strip(), []
            else: body.append(line)
        if head or body: out.append((head, '\n'.join(body).strip()))
        return [(h, b) for h, b in out if h or b]

    def _remember_page(self, url, text):
        doc_id = f'doc_{len(self.remembered) + 1}'
        title = self._sections(text)[0][0] if self._sections(text) else url
        self.remembered[doc_id] = (title or url, url, str(text))
        return doc_id

    def memory_search(self, query, limit=8):
        q = str(query).lower()
        rows = []
        for doc_id, (title, url, text) in self.remembered.items():
            for i, (head, body) in enumerate(self._sections(text)):
                if q not in f'{head}\n{body}'.lower(): continue
                crumb = title if (not head or head == title) else f'{title} › {head}'
                rows.append({'node_id': f'{doc_id}#{i}', 'document': title, 'url': url,
                             'breadcrumb': crumb, 'text': body})
        return rows[:int(limit)]

    def memory_tree(self, document=''):
        d = str(document).lower()
        return [{'doc_id': doc_id, 'title': title, 'url': url,
                 'headings': [{'node_id': f'{doc_id}#{i}', 'heading': head}
                              for i, (head, _) in enumerate(self._sections(text))]}
                for doc_id, (title, url, text) in self.remembered.items()
                if not d or d in title.lower() or d == doc_id]

    def memory_read(self, node_id):
        doc_id, _, idx = str(node_id).partition('#')
        if doc_id not in self.remembered: raise AgentError(f'no remembered node {node_id!r}')
        title, url, text = self.remembered[doc_id]
        head, body = self._sections(text)[int(idx or 0)]
        return {'node_id': node_id, 'document': title, 'url': url, 'heading': head, 'text': body}

    def memory_topics(self, limit=12):
        "One cluster per remembered document, which is the honest clustering of a handful of pages."
        return [{'topic': title, 'members': [url], 'n': len(self._sections(text))}
                for title, url, text in list(self.remembered.values())[:int(limit)]]

    def memory_forget(self, doc_id):
        return self.remembered.pop(str(doc_id), None) is not None

    # -- the parts a terminal cannot have ------------------------------------
    @property
    def scopes(self):
        "Both, so the overlay branch of `inspect_python` has somewhere to be tested."
        return ('isolated', 'overlay')

    def inspect_python(self, code, scope='isolated'):
        """Isolated runs on a copy; overlay runs against the real namespace but refuses to move
        anything already in it -- the same guarantee an IDE's AST policy gives, enforced by
        restoring every pre-existing binding afterwards.
        """
        if scope != 'overlay': return super().inspect_python(code, scope)
        before = dict(self.ns)
        try: return self._exec(code, self.ns)
        except Exception as e: return f'{agent_err(e)}'
        finally:
            for k, v in before.items(): self.ns[k] = v
            for k in [k for k in self.ns if k not in before]: pass   # the agent's own names persist

    @property
    def kernel_kind(self): return 'ipymini'

    def note(self, text):
        self.notes.append(str(text))
        super().note(text)

# %% ../nbs/04_testing.ipynb #83abeaab
class FakeBackend(Backend):
    "A backend over a scripted list of replies, so a turn can be driven with no model at all."

    kind = 'fake'

    def __init__(self, spec=SPEC, replies=(), **kw):
        super().__init__(spec, **kw)
        self.replies, self.sent, self.hist_ = list(replies), [], []
        self.spawned = []

    def _start(self): return self
    def _close(self): pass

    def _send(self, msg, **kw):
        self.sent.append(msg)
        self.hist_.append({'role': 'user', 'content': str(msg)})
        out = self.replies.pop(0) if self.replies else '(done)'
        self.hist_.append({'role': 'assistant', 'content': out})
        return out

    def _stream(self, msg, **kw):
        for w in self._send(msg, **kw).split(' '): yield w + ' '

    def _oneshot(self, prompt, sp, max_tokens): return f'ONESHOT:{prompt[:40]}'
    def _usage(self):
        # Cumulative, the way a real chat's counters are: `Backend.send` assigns rather than
        # adds, so a double keeps its own running total or it cannot catch double-counting.
        n = max(1, len(self.sent))
        return Usage(model=self.spec.model_id, input=10*n, output=5*n, total=15*n, turns=n)

    @property
    def hist(self): return self.hist_

    def _replace_hist(self, summary, keep):
        self.hist_ = [{'role': 'user', 'content': summary}] + list(keep)

    def spawn(self, sp='', tools=(), **kw):
        s = FakeBackend(self.spec, replies=['sub answer'], sp=sp, tools=tools, shared=True)
        self.spawned.append(s)
        return s

# %% ../nbs/04_testing.ipynb #10360a7c
def fake_agent(host=None, replies=(), **kw):
    """An `Agent` whose every job routes to one `FakeBackend`. Returns `(agent, backend)`.

    The routing table is pointed at `SPEC` as well, not only the backends. `Agent.compose`
    asks what runtime the turn is on -- a text-only LiteRT engine cannot be handed an image
    content part -- so a double that left routing on the real default local model composed a
    different message depending on whether the machine running the tests had LiteRT installed.
    """
    a = Agent(host or MemHost({'/proj/a.py': 'def a(): pass\n'}), extensions=False, **kw)
    be = FakeBackend(SPEC, replies=replies)
    if 'model' not in kw and 'routing' not in kw:
        a.routing.turn, a.routing.policy = SPEC.name, {}   # every job, not only `turn`
        a.routing._cache[SPEC.name] = SPEC
    a._be = lambda job='turn': be
    a._be_or_none = lambda job='turn': be
    return a, be

#: What a local Gemma says when it refuses a turn. Real output, kept verbatim, because the
#: whole point of `native` is recognising the shape of this rather than a tidied version.

# %% ../nbs/04_testing.ipynb #recorded01
#: Where the recorded answers live: one diskcache beside the installed package, so a notebook
#: finds the same recordings whichever folder it happens to be run from. Located through the
#: package rather than `__file__`, which a notebook cell does not have.
CHATS = Path(ramabana.__file__).parent.parent/'chatcache'


@contextmanager
def recorded(path=None, record=None):
    """Replay recorded model answers for the duration, instead of calling a model.

    `record=True` -- or `$RISHI_RECORD_CHAT` -- lets a miss reach a real model, which is how a
    recording gets made. Without it a miss *raises*, which is the point: a page that has drifted
    away from what was recorded fails, rather than quietly loading weights or spending money on
    somebody's API in the middle of a test run.

    Replay covers the asks that have an answer to keep: a blocking turn, a one-shot, a
    classification. A streamed turn is a generator, so nothing records it and `stream` still
    reaches whatever was built.
    """
    from rishi.litert import CachedChat
    from ramabana.runtime import use_chat
    p = Path(path or CHATS)
    with use_chat(partial(CachedChat, path=str(p), record=record)): yield p

# %% ../nbs/04_testing.ipynb #b4780df7
GEMMA = ('E0000 00:00:1234.567 llm_engine.cc:412] input token IDs exceed the maximum '
         'number of tokens 4096, got 5092\n')


class MutteringBackend(Backend):
    "A backend that fails the way litert does: it prints, returns nothing, and raises nothing."

    kind = 'muttering'

    def __init__(self, spec=None, mode='empty', **kw):
        super().__init__(spec or ModelSpec('gemma-e2b', 'muttering', 'gemma/e2b', ctx=4096), **kw)
        self.mode = mode

    def _start(self): return self
    def _close(self): pass
    def _usage(self): return Usage(model=self.spec.model_id)

    def _mutter(self):
        "What `RishiBackend._native` does for real: keep what the engine said, and report it."
        self.last_native = GEMMA.strip()
        self.problem(f'{self.spec.name}: {GEMMA.strip()}')

    def _send(self, msg, **kw):
        self._mutter()
        return ''

    def _stream(self, msg, **kw):
        self._mutter()
        return iter(())

    def _oneshot(self, prompt, sp, max_tokens):
        self._mutter()
        raise RuntimeError('input too long')

# %% ../nbs/04_testing.ipynb #51f402c1
class Step:
    """One thing a scripted model does: call a tool, or say something.

    `tool` is a `(name, kwargs)` pair and is called through the agent's real tool list, so
    the activity feed, the approval gate and the file snapshots all run for real -- the only
    fiction is which tool the model decided to call.
    """

    def __init__(self, text='', tool=None, pause=0.0):
        self.text, self.tool, self.pause = text, tool, pause


class ScriptedBackend(Backend):
    """Plays a list of `Step`s, streaming its words one at a time.

    `token_delay` is what makes a screenshot possible: at zero the turn finishes before the
    first repaint and every capture shows a completed answer, which is the one thing a
    streaming screenshot must not show.
    """

    kind = 'scripted'

    #: What a spawned sub-agent answers, keyed by a substring of the question. A fan-out
    #: whose three sub-agents all say the same thing would look like one call in a wig.
    SUB_ANSWERS = {'import': 'three files: backend.py, models.py, fastllm_hitl.py',
                   'compaction': 'chat.py:compact(), fired from _prepare() at the threshold',
                   'shape': 'df is (200, 2); `keep` is an int'}

    def __init__(self, spec=SCRIPTED, steps=(), token_delay=0.02, **kw):
        super().__init__(spec, **kw)
        self.steps, self.token_delay = list(steps), token_delay
        self.hist_, self.sent = [], []

    def _start(self): return self
    def _close(self): pass
    def _oneshot(self, prompt, sp, max_tokens): return 'a one-shot answer'
    def _usage(self): return Usage(model=self.spec.model_id, input=1840, output=96, total=1936,
                                   cached=1200, cost=0.0031, turns=1)

    @property
    def hist(self): return self.hist_

    def _replace_hist(self, summary, keep):
        self.hist_ = [{'role': 'user', 'content': summary}] + list(keep)

    def spawn(self, sp='', tools=(), **kw):
        answers = self.SUB_ANSWERS
        class Sub(ScriptedBackend):
            def _run(self, msg):
                q = str(msg).lower()
                hit = next((v for k, v in answers.items() if k in q), 'nothing found')
                for w in hit.split(' '): yield w + ' '
        return Sub(self.spec, token_delay=0, shared=True)

    def _tool(self, name):
        return next((t for t in self.tools if getattr(t, '__name__', '') == name), None)

    def _run(self, msg):
        "Walk the script, calling tools for real and yielding the words of every text step."
        self.sent.append(msg)
        self.hist_.append({'role': 'user', 'content': str(msg)})
        for s in self.steps:
            if s.pause: time.sleep(s.pause)
            if s.tool:
                name, kw = s.tool
                if (f := self._tool(name)) is not None:
                    self.hist_.append({'role': 'assistant', 'content': f'[{name}]'})
                    self.hist_.append({'role': 'tool', 'content': str(f(**kw))[:400]})
            for w in s.text.split(' '):
                if not w: continue
                if self.token_delay: time.sleep(self.token_delay)
                yield w + ' '

    def _send(self, msg, **kw):
        out = ''.join(self._run(msg))
        self.hist_.append({'role': 'assistant', 'content': out})
        return out

    def _stream(self, msg, **kw):
        out = []
        for w in self._run(msg):
            out.append(w)
            yield w
        self.hist_.append({'role': 'assistant', 'content': ''.join(out)})
