"""The toolset is `shalya`. This module is what Ramabana adds to it, and the names it keeps resolving.

Docs: https://vedicreader.github.io/ramabana/tools.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tools.ipynb.

# %% auto #0
__all__ = ['WRITE_TOOLS', 'SUB_MAX_STEPS', 'SUB_SP', 'SUB_WRITE_SP', 'NO_SUB', 'NullHost', 'draws_itself', 'image_tools',
           'tools_for', 'sub_briefing', 'read_only', 'sub_sp', 'bad_json', 'delegate', 'delegate_many', 'named_skills',
           'subagent_tools', 'frontmatter', 'API_VENDORS', 'Capability', 'DENY', 'ERR', 'EVENTS', 'EXTRA_MODULES',
           'GIT_READ_TOOLS', 'GIT_TOOLS', 'GIT_WRITE_TOOLS', 'GROUP', 'GROUPS', 'Hit', 'Host', 'HostError', 'IMAGE_API',
           'IMAGE_MODEL', 'IMAGE_SIZES', 'LD_CHARS', 'LocalHost', 'MAX_API', 'MAX_FILE', 'MAX_GREP_HITS', 'MAX_HITS',
           'MAX_SKILL_CHARS', 'MAX_TOOL_CHARS', 'MAX_VARS', 'NO_ROOTS', 'RESPONSES_API', 'Registry', 'SANDBOX',
           'SECRET', 'SKILL_DESC_MAX', 'SKIP_DIRS', 'SKIP_SUFFIXES', 'Skill', '_apply_edits', '_cmds', '_diff',
           '_edits', 'api_model', 'api_tools', 'ask_tools', 'apply_edits', 'clip', 'clip_lines', 'cmds', 'code_tools',
           'denied', 'diff_text', 'discover', 'edits', 'err', 'ext_dirs', 'failed', 'file_tools', 'find', 'git_tools',
           'image_available', 'implemented', 'is_write', 'ld_json', '_fuse', 'CodeHost', 'WebHost', 'NotebookHost',
           'MemoryHost', 'WatchHost', 'SessionHost', 'ShellHost', 'ApiHost', 'GitHost', 'load', 'media_dir',
           'memory_tools', 'mime_for', 'notebook_tools', 'readable', 'save_media', 'session_tools', 'shell_tools',
           'skill_dirs', 'skill_index', 'skill_tools', 'watch_tools', 'web_tools', 'writes']

# %% ../nbs/02_tools.ipynb #b0911d39
import concurrent.futures, functools, json, re, threading, time, uuid
from fastcore.basics import AttrDict, ifnone
from fastcore.foundation import L
from fastcore.parallel import parallel
from shalya.core import (ERR, GIT_READ_TOOLS, GIT_TOOLS, GIT_WRITE_TOOLS, Hit, MAX_API, MAX_FILE,
                         MAX_GREP_HITS, MAX_HITS, MAX_TOOL_CHARS, apply_edits, clip,
                         clip_lines, cmds, diff_text, edits, err, failed, is_write, writes)
from shalya.host import (Capability, DENY, Host, HostError, LD_CHARS, LocalHost, MAX_VARS, NO_ROOTS,
                         SANDBOX, SECRET, SKIP_DIRS, SKIP_SUFFIXES, denied, implemented, ld_json, _fuse,
                         CodeHost, WebHost, NotebookHost, MemoryHost, WatchHost, SessionHost,
                         ShellHost, ApiHost, GitHost)
from shalya.skills import (EVENTS, EXTRA_MODULES, GROUP, MAX_SKILL_CHARS, Registry, SKILL_DESC_MAX,
                           Skill, discover, ext_dirs, find, load, skill_dirs, skill_index)
from shalya.tools import (API_VENDORS, GROUPS, IMAGE_API, IMAGE_MODEL, IMAGE_SIZES, RESPONSES_API,
                          _post_responses, api_model, api_tools, ask_tools, code_tools, file_tools,
                          image_available, media_dir, memory_tools, mime_for, notebook_tools,
                          readable, save_media, session_tools, shell_tools, skill_tools, watch_tools,
                          web_tools, git_tools)
from shalya.tools import image_tools as _image_tools
from shalya.tools import read_only as _read_only
from shalya.tools import tools_for as _tools_for
from .core import AgentError, agent_err, spec_caps
from .runtime import Run, current_run, run_context

# %% ../nbs/02_tools.ipynb #e0ca9981
from fastcore.docments import frontmatter
from shalya.core import WRITE_TOOLS as _TOOL_WRITES

#: Names Leela imports from `ramabana.tools`. They are shalya's now, under the spellings Leela knows.
_cmds, _edits, _apply_edits, _diff = cmds, edits, apply_edits, diff_text

#: `cart_tools` is an extension rather than a host group, so its two spenders are added by name here.
WRITE_TOOLS = _TOOL_WRITES | {'cart_add', 'cart_remove'}

# %% ../nbs/02_tools.ipynb #694f6d5d
#: shalya's names, re-exported so `from ramabana.tools import *` still finds them.
_all_ = ['frontmatter', 'API_VENDORS', 'Capability', 'DENY', 'ERR', 'EVENTS', 'EXTRA_MODULES', 'GIT_READ_TOOLS', 'GIT_TOOLS', 'GIT_WRITE_TOOLS', 'GROUP', 'GROUPS', 'Hit', 'Host', 'HostError', 'IMAGE_API', 'IMAGE_MODEL', 'IMAGE_SIZES', 'LD_CHARS', 'LocalHost', 'MAX_API', 'MAX_FILE', 'MAX_GREP_HITS', 'MAX_HITS', 'MAX_SKILL_CHARS', 'MAX_TOOL_CHARS', 'MAX_VARS', 'NO_ROOTS', 'RESPONSES_API', 'Registry', 'SANDBOX', 'SECRET', 'SKILL_DESC_MAX', 'SKIP_DIRS', 'SKIP_SUFFIXES', 'Skill', '_apply_edits', '_cmds', '_diff', '_edits', 'api_model', 'api_tools', 'ask_tools', 'apply_edits', 'clip', 'clip_lines', 'cmds', 'code_tools', 'denied', 'diff_text', 'discover', 'edits', 'err', 'ext_dirs', 'failed', 'file_tools', 'find', 'git_tools', 'image_available', 'implemented', 'is_write', 'ld_json', '_fuse', 'CodeHost', 'WebHost', 'NotebookHost', 'MemoryHost', 'WatchHost', 'SessionHost', 'ShellHost', 'ApiHost', 'GitHost', 'load', 'media_dir', 'memory_tools', 'mime_for', 'notebook_tools', 'readable', 'save_media', 'session_tools', 'shell_tools', 'skill_dirs', 'skill_index', 'skill_tools', 'watch_tools', 'web_tools', 'writes']

# %% ../nbs/02_tools.ipynb #1ec6c57a
@implemented
class NullHost(Host):
    "A host with nothing behind it. The reference implementation of 'this host cannot'."

    def __init__(self, roots=()): self._roots = [str(r) for r in roots]

    @property
    def roots(self): return self._roots
    def check(self, path, must_exist=False, reading=False): raise HostError(f'{NO_ROOTS}: {path}')
    def walk(self): return []
    def read(self, path): return None
    def write(self, path, text): raise HostError('this host cannot write')
    def text_at(self, path): return None

# %% ../nbs/02_tools.ipynb #55c1bbd5
def draws_itself(spec):
    "Can `spec`'s own model draw, given the image tool?"
    if spec is None: return False
    c = spec_caps(spec)
    return bool(c is not None and 'image' in getattr(c, 'tools', ()))

def _from_responses(raw):
    "Generated pictures out of a Responses reply, read by the same `rishi` code a turn uses."
    from rishi.remote import gen_media
    return gen_media(raw)

def image_tools(host, mx=MAX_TOOL_CHARS, session='', get_spec=None, on_media=None):
    "shalya's image group, told what this turn's model can do."
    spec = get_spec() if get_spec else None
    return _image_tools(host, mx, session, draws_itself=lambda: draws_itself(spec),
                        from_reply=_from_responses, model_id=getattr(spec, 'model_id', ''),
                        on_media=on_media)

# %% ../nbs/02_tools.ipynb #de2cd1e8
def tools_for(host, get_skills=None, extra=(), mx=MAX_TOOL_CHARS, drop=(), get_spec=None, on_media=None):
    """Every tool this host declares it can support, plus whatever extensions registered.

    Groups come from `Host.provides`. `drop` withholds a group the host does support, decided by
    `core.budget_for` and reported by `Agent.budget`.
    """
    # credentialled, never probed: a key is either there or it is not
    image = (image_tools(host, mx, get_spec=get_spec, on_media=on_media)
             if image_available() and 'image' not in set(drop or ()) else None)
    return _tools_for(host, get_skills=get_skills, extra=extra, mx=mx, drop=drop, image=image)

# %% ../nbs/02_tools.ipynb #e3b29ea1
SUB_MAX_STEPS = 12

SUB_SP = """You are a research sub-agent inside a Python IDE. Another agent has delegated one \
question to you because answering it takes many tool calls and the answer is short.

- Answer exactly the question asked. Nothing else.
- Use your tools as much as you need; nobody is paying attention to how many calls it takes.
- Report what you found, with file paths and line numbers, not what you infer or expect.
- If the answer is that there is nothing, say so plainly. A confident wrong answer is far \
worse than "no matches, and here is what I searched for".
- You cannot edit anything. If the answer implies a change, describe the change and stop.
- `inspect_python` answers questions about the user's live variables without changing them. \
Its default scope is a sandbox that refuses most library calls; pass `scope='overlay'` to \
get the real interpreter. Use it rather than guessing at what is in memory."""


#: Swapped in for the two read-only lines above when a session grants sub-agents writes.
SUB_WRITE_SP = """- You have the delegating agent's write tools as well as its read tools: create and \
edit files, run commands, run Python. Every call is recorded on the session and goes through the \
approval policy the main agent answers to. A refusal comes back with a reason. Read it and change \
the approach.
- Write only what the task asked for. You cannot see the conversation that sent you. Anything \
else you change is a change nobody reviewed.
- Verify with the tool that proves it. Run the test. Read the file back. Report the evidence.
- `run_python` shares the user's kernel namespace. Bind results to NEW names. You cannot rebind or \
delete what the user made."""


def sub_briefing(writes=False):
    "The sub-agent standing instructions, with the read-only sentences swapped out when writes are on."
    if not writes: return SUB_SP
    keep = [ln for ln in SUB_SP.splitlines()
            if not ln.startswith('- You cannot edit anything') and not ln.startswith('- `inspect_python`')]
    return '\n'.join(keep).rstrip() + '\n' + SUB_WRITE_SP


# A sub-agent does not spawn sub-agents: recursion here is a fan-out tree whose width nobody chose.
# Nor does it open standing work: a folder watch outlives the task that opened it, and nobody
# asked for the reviews it would keep producing after the delegation is forgotten.
NO_SUB = frozenset({'delegate_search', 'delegate_parallel',
                    'watch_folder', 'cancel_folder_watch', 'check_folders'})

# %% ../nbs/02_tools.ipynb #8ca3589d
def read_only(tools, max_calls=None, writes=False):
    "The tools a sub-agent may have, optionally behind a hard per-task call budget."
    blocked = NO_SUB if writes else (WRITE_TOOLS | NO_SUB)
    allowed = [t for t in tools if getattr(t, '__name__', '') not in blocked]
    if max_calls is None: return allowed
    state, lock = {'n': 0}, threading.Lock()

    def guarded(f):
        @functools.wraps(f)
        def call(*args, **kw):
            with lock:
                state['n'] += 1
                over = state['n'] > max_calls
            if over:
                return ('Sub-agent tool budget exhausted. Stop calling tools and return the '
                        'best evidence-backed answer now.')
            return f(*args, **kw)
        return call
    return [guarded(t) for t in allowed]

# %% ../nbs/02_tools.ipynb #0818dbdb
def sub_sp(sp=SUB_SP, skills=()):
    "A sub-agent's briefing: its standing instructions, then the bodies of the skills its task named."
    if not skills: return sp
    return sp + '\n\n' + '\n\n'.join(f'## {s.name}\n\n{s.text()}' for s in skills)


def _stopped(run):
    "A stopped delegation answers in text: a dict would reach the model as its own repr."
    return f'The delegated question was stopped ({run.state}) before it answered.'


def bad_json(e, span=120):
    "The fragment a JSON error is about."
    doc, pos = getattr(e, 'doc', None), getattr(e, 'pos', None)
    if not isinstance(doc, str) or not isinstance(pos, int): return ''
    lead = '…' if pos > span else ''
    tail = '…' if pos + span < len(doc) else ''
    return f'\nit stopped here: {lead}{doc[max(0, pos - span):pos + span]}{tail}'


def _model_refused(sub, reply):
    "Whether what came back is the sub-agent's backend reporting its own failure, not an answer."
    problems = getattr(sub, 'problems', None) or []
    return bool(problems) and str(reply or '').strip() == str(problems[-1]).strip()


def delegate(backend, question, tools=(), sp=None, max_steps=SUB_MAX_STEPS, skills=(),
             writes=False,      # hand over WRITE_TOOLS as well
             approve=None,      # the gate those writes answer to, which `spawn` inherits none of
             run=None):         # a pre-registered child run
    "Ask `question` in a throwaway conversation on `backend`'s engine. Returns the answer text."
    sub = None
    run = run or Run(f'run_{uuid.uuid4().hex[:12]}', 'child', str(question), backend.spec.name, current_run())
    if not run.start(): return _stopped(run)
    try:
        # the tool wrappers are the hard stop: native engines own their own tool loop
        kw = {'approve': approve} if approve is not None else {}
        sub = backend.spawn(sp=sub_sp(ifnone(sp, sub_briefing(writes)), skills),
                            tools=read_only(tools, max_calls=max_steps * 4, writes=writes), **kw)
        if hasattr(sub, 'max_steps'): sub.max_steps = max_steps
        if not run.attach(sub): return _stopped(run)
        with run_context(run): reply = sub.send(question, run=run)
        if run.cancelled: return _stopped(run.finish())
        if _model_refused(sub, reply):
            run.finish('failed')
            return err(f'delegation failed after the sub-agent was asked: {reply}')
        run.finish()
        return _delegate_result(reply)
    except Exception as e:
        run.finish('failed')
        return err('delegation failed after the sub-agent was asked' if sub is not None else
                   'delegation failed before the sub-agent was asked, so nothing was sent', e) + bad_json(e)
    finally:
        if sub is not None:
            try: sub.close()
            except Exception: pass

# %% ../nbs/02_tools.ipynb #fe517832
def delegate_many(backend, questions, tools=(), sp=None, max_steps=SUB_MAX_STEPS, n_workers=4,
                  skills=(), writes=False, approve=None, parent=None):
    "Ask several questions. Register every child before starting serial or parallel workers."
    qs = L(questions)
    if not qs: return L()
    parent = parent or current_run()
    runs = [Run(f'run_{uuid.uuid4().hex[:12]}', 'child', str(q), backend.spec.name, parent,
                getattr(parent, 'grace', .25)) for q in qs]
    def run(item):
        q, child = item
        if child.cancelled:return _stopped(child)
        return delegate(backend, q, tools, sp, max_steps, skills, writes, approve, child)
    items = list(zip(qs, runs))
    # writing sub-agents stay serial. `Approvals` holds one pending ask, and nobody can review
    # concurrent edits to one workspace
    workers = 1 if writes or getattr(backend.spec, 'local', False) else min(n_workers, len(qs))
    ex = concurrent.futures.ThreadPoolExecutor(max_workers=max(1, workers))
    futures = [ex.submit(run, item) for item in items]
    try:
        while True:
            if all(f.done() for f in futures):break
            if parent is not None and parent.cancelled:
                concurrent.futures.wait(futures, timeout=getattr(parent, 'grace', .25))
                break
            time.sleep(.005)
        out = []
        for child, future in zip(runs, futures):
            if future.done():
                try:out.append(future.result())
                except Exception as e:out.append(err('delegation failed', e) + bad_json(e))
            else:
                child.detach(); out.append(_stopped(child))
        return L(out)
    finally:ex.shutdown(wait=False, cancel_futures=True)

# %% ../nbs/02_tools.ipynb #906e7f69
def named_skills(get_skills, names):
    "The skills a delegated task named, and a note about any name that matched nothing."
    if not names or get_skills is None: return [], ''
    every = list(get_skills() or [])
    got, missing = [], []
    for n in [x for x in str(names).replace(',', ' ').split() if x]:
        s = find(every, n)
        got.append(s) if s is not None else missing.append(n)
    if not missing: return got, ''
    return got, (f"\n\n[no skill named {', '.join(missing)}; this repository has "
                 f"{', '.join(s.name for s in every) or 'none'}]")


def subagent_tools(get_backend, get_tools, get_skills=None, get_cloud_backend=None,
                   get_writes=None,     # the session's sub-agent write toggle, read per call
                   get_approve=None):   # the gate those writes answer to
    """The `delegate` tool, bound to whatever backend routing says sub-agents run on.

    Every argument is a callable. A model switch mid-session is picked up. `get_tools` is the
    sub-agent model's tool list, not the turn model's.
    """

    def _writes(): return bool(get_writes()) if get_writes is not None else False
    def _approve(): return get_approve() if (get_approve is not None and _writes()) else None

    def delegate_search(question: str, skills: str = '') -> str:
        """Hand a broad search question to a sub-agent and get back only its conclusion.

        Use this when answering would take many `search_code` / `view_file` / `read_url` /
        `inspect_python` calls whose results you do not need to keep. "where else do we
        do X", "which files import Y", "what shape is everything in this namespace". Its
        working is discarded. The cost to your context is one question and one answer.

        The sub-agent has your read-only tools. Whether it also has your write tools is the
        session's setting rather than yours. With sub-agent writes on it can edit, run commands
        and run Python under the approval policy you answer to. The task you send may then ask
        for a change. With them off it can only report.

        `skills` names skills from your skill index, comma separated, whose text the sub-agent
        should start with: name the one or two its task actually needs. You hold the index and
        it does not. This is the only way it gets a skill without spending a step reading
        one. Leave it empty when the task needs no particular skill.

        Ask one self-contained question. The sub-agent cannot see this conversation.
        """
        b = get_backend()
        if b is None: return 'no model is available to delegate to'
        sk, note = named_skills(get_skills, skills)
        return clip(delegate(b, question, get_tools(), skills=sk, writes=_writes(),
                             approve=_approve()), MAX_TOOL_CHARS) + note

    def delegate_parallel(questions: str, skills: str = '', cloud_model: str = '') -> str:
        """Hand several independent questions to sub-agents at once, and get back every answer.

        `questions` is a JSON array of strings, e.g.
          ["which files import fastllm?", "where is compaction triggered?", "what is df's shape?"]

        Use it when you have two or more questions that do not depend on each other. They
        run concurrently, each in its own throwaway conversation with your read-only tools. Three questions cost you three short answers rather than the sixty tool results
        it would take to answer them yourself. With sub-agent writes on they run one after
        another instead, because their approvals share one queue.

        `skills` names skills from your skill index, comma separated, given to every one of
        them. Use it when the questions share a subject. When they do not, ask them in separate
        `delegate_search` calls so each gets only what its own task needs.

        `cloud_model` optionally selects one configured remote model for this fan-out. It does not
        change the session's turn or default sub-agent model. Every question must be self-contained:
        a sub-agent cannot see this conversation or the other questions.
        """
        b = get_cloud_backend(cloud_model) if cloud_model and get_cloud_backend is not None else get_backend()
        if b is None: return f"no model is available to delegate to{f' ({cloud_model})' if cloud_model else ''}"
        try:
            qs = json.loads(questions) if isinstance(questions, str) else list(questions)
            if not isinstance(qs, list) or not all(isinstance(q, str) for q in qs):
                raise ValueError('expected a JSON array of strings')
        except Exception as e:
            return err('could not parse questions', e)
        if not qs: return 'no questions given'
        sk, note = named_skills(get_skills, skills)
        answers = delegate_many(b, qs, get_tools(), skills=sk, writes=_writes(), approve=_approve())
        return clip('\n\n'.join(f'### {q}\n{a}' for q, a in zip(qs, answers)), MAX_TOOL_CHARS * 2) + note

    return [delegate_search, delegate_parallel]

# %% ../nbs/02_tools.ipynb #9424aadf
def _delegate_result(text):
    "Reject degenerate delegated prose before it can be presented as research."
    text = str(text or '').strip()
    words = re.findall(r"[A-Za-z0-9_+.-]+", text.lower())
    if not text: return 'Delegated inspection failed: the sub-agent returned no answer.'
    if len(words) >= 12 and max(words.count(w) for w in set(words)) > max(8, len(words) // 4):
        return 'Delegated inspection failed: repetitive output was discarded as unreliable.'
    return text
