"""Memory that outlives the process: one vishalakshi vault behind `Host`, and the standing
watches that put things back on the agent's desk.

## Why a vault

`LocalHost` can already read the web and index the repo, and neither survives the process. A
page read in one session is gone by the next, and the code index and the reading are two
unrelated stores that never see each other's results.

A [vishalakshi](https://vedicreader.github.io/vishalakshi/) `Vault` is one SQLite file holding
both. Putting it behind `Host` buys three things the harness cannot get any other way:

- **`memory_search` actually has something to search.** `LocalHost` raises
  `NotImplementedError` for the whole memory group, so `tools_for` drops it. With a vault the
  five memory tools appear, and they answer from everything ever read.
- **One ranking instead of three.** `search_code` fuses the vault's prose, kosha's identifiers
  and ripgrep's literals through `federate`. The legs share no vector space, so they are merged
  by rank rather than by distance.
- **Standing interests.** A vault has watches, so `watch_tools` appears too: the agent can
  arrange to re-read a page next week, or be reminded of something it worked out today.

## The host

`VaultHost` is `LocalHost` plus a vishalakshi vault. Construction opens the vault in a
background thread for the same reason the kosha sync does: the first touch must not block
`tools_for` while an embedding model loads. Capabilities advertise memory and watches by
construction rather than by probing.

## Memory

The five memory tools appear once a vault is present. Search returns whole sections plus
graph neighbours; read, tree, topics and forget are thin wrappers over the vault.

## Federated search

`search` asks the vault for prose, kosha for identifiers and ripgrep for literals, then
fuses the legs with `litesearch.rrf_all` through `Vault.federate`. A vault that will not open
falls back to `LocalHost.search`.

## Watches and reminders

Standing interests live in the vault. `poll` fires what is due without rebuilding the entity
graph on the turn; `connect` does that rebuild in the background.

## Using it

Docs: https://vedicreader.github.io/ramabana/vault.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_vault.ipynb.

# %% auto #0
__all__ = ['DFLT_VAULT', 'MEM_SECTIONS', 'TOC_DEPTH', 'VaultHost']

# %% ../nbs/07_vault.ipynb #bcb01f4f
import json, threading, time
from pathlib import Path
from fastcore.basics import AttrDict
from fastcore.meta import delegates
from fastcore.parallel import startthread
from .core import AgentError, agent_err
from .tools import Hit, LocalHost, clip


# %% ../nbs/07_vault.ipynb #8d87918f
DFLT_VAULT = None         # Vault(None) -> ~/.vishalakshi/vault.db, same as the CLI
MEM_SECTIONS = 6          # operative sections a memory search returns
TOC_DEPTH = 2             # heading levels of a document's tree worth showing at once


# %% ../nbs/07_vault.ipynb #d2ba7a3a
def _trim(node, depth=TOC_DEPTH):
    "One heading tree, cut to `depth` levels: a whole tree is a document, not an index entry."
    if not isinstance(node, dict): return node
    out = {k: node.get(k) for k in ('id', 'title', 'pages') if node.get(k) is not None}
    kids = node.get('children') or []
    if depth > 0 and kids: out['children'] = [_trim(k, depth - 1) for k in kids]
    elif kids: out['children'] = f'{len(kids)} more'
    return out


def _sect(s):
    "One retrieved section, cut to what a model needs: what it says, where it is, how to read it."
    return {k: s[k] for k in ('node_id', 'doc_id', 'title', 'breadcrumb', 'text') if k in s}


def _fed_hit(h):
    """One federated row as a `Hit`, keeping the handle that reopens it.

    The legs return different things -- a repo hit is a file and a line, a prose hit is a
    section of something read months ago -- so `symbol` carries whichever identifier the
    follow-up tool needs: a `mod_name` for `symbols`, a `node_id` for `memory_read`.
    """
    where = str(h.get('where') or h.get('ref') or '')
    path, _, num = where.rpartition(':')
    if h.get('source') == 'prose': return Hit(where, 1, str(h.get('ref') or ''), str(h.get('text') or '')[:200])
    return Hit(path if num.isdigit() else where, int(num) if num.isdigit() else 1,
               str(h.get('ref') or h.get('title') or ''), str(h.get('text') or '')[:200])

# %% ../nbs/07_vault.ipynb #bc5c6436
class VaultHost(LocalHost):
    """`LocalHost` with a vishalakshi vault: durable memory, federated search, watches.

    Reading is filed rather than throwaway; `search` fuses vault prose, kosha and ripgrep
    through `Vault.federate`. The vault opens in a background thread so `tools_for` never
    blocks on an embedding model load -- advertise via `capabilities`, never probe.
    """

    @property
    def capabilities(self):
        "Memory and watches, by construction: a `VaultHost` is the host that has a vault."
        return {**super().capabilities, 'memory': True, 'watch': True}

    @delegates(LocalHost.__init__)
    def __init__(self,
                 roots=('.',),          # the folders the agent is confined to
                 vault=DFLT_VAULT,      # a `Vault`, a path to one, or None for ~/.vishalakshi/vault.db
                 federate=True,         # fuse vault prose into `search_code` alongside kosha and ripgrep
                 remember_reads=True,   # file what `read_url` fetches, so the next session has it
                 warm=True,             # open the vault in the background at construction
                 mk_chat=None,          # build the vault's chats with this; None -> vishalakshi's own
                 **kwargs):             # forwarded to `LocalHost`
        super().__init__(roots, **kwargs)
        self.mk_chat = mk_chat
        import threading
        self._vault, self._vlock, self._vthread = vault, threading.Lock(), None
        self.federate, self.remember_reads = federate, remember_reads
        self._legs, self._cthread = None, None
        if warm: self.open_vault()

    # -- the vault itself ----------------------------------------------------
    def open_vault(self, wait=False):
        "Open the vault in a daemon thread, once. `wait=True` for a caller that needs it now."
        if self._vthread is None or not self._vthread.is_alive():
            self._vthread = startthread(lambda: self._open(), daemon=True)
            self._vthread.name = 'ramabana-vault'
        if wait: self._vthread.join()
        return self

    def _open(self):
        with self._vlock:
            v = self._vault
            if v is None or isinstance(v, (str, Path)):
                from vishalakshi import Vault
                self._vault = v = Vault(str(v)) if v is not None else Vault()
            return v

    @property
    def vault(self):
        "The `Vault`, opened on first use."
        return self._open()

    def connect(self, wait=False):
        "Rebuild the entity graph `related` walks, off the turn, once at a time."
        if self._cthread is None or not self._cthread.is_alive():
            def run():
                try: self.vault.connect()
                except Exception as e: self.note(f'could not rebuild the memory graph: {agent_err(e)}')
            self._cthread = startthread(run, daemon=True)
            self._cthread.name = 'ramabana-vault-connect'
        if wait: self._cthread.join()
        return self

    # -- durable research memory --------------------------------------------
    def memory_search(self, query, limit=MEM_SECTIONS):
        """Whole sections, plus what they connect to.

        `related` is the part worth having: sections reached along the entity graph or by
        embedding similarity rather than by matching the query. It is how a search finds the
        note you forgot you wrote.
        """
        c = self.vault.context(str(query), sections=int(limit), related=max(2, int(limit) // 2))
        return dict(query=c.query, encoder=c.encoder,
                    results=[_sect(s) for s in c.results],
                    related=[dict(_sect(s), via=s.get('via')) for s in c.related])

    def memory_tree(self, document=''):
        "The heading tree of everything remembered; `document` narrows to one title or doc id."
        toc, d = self.vault.toc(), str(document).strip().lower()
        if d: toc = [t for t in toc if d in str(t.get('title', '')).lower() or d == t.get('doc_id')]
        return [dict(doc_id=t.get('doc_id'), title=t.get('title'), source=t.get('source'),
                     pages=t.get('pages'), tree=_trim(t.get('tree'))) for t in toc]

    def memory_read(self, node_id): return self.vault.read(str(node_id))

    def memory_topics(self, limit=12):
        m = self.vault.map()
        return dict(method=m.get('method'), note=m.get('note'),
                    clusters=list(m.get('clusters') or [])[:int(limit)])

    def memory_forget(self, doc_id):
        self.vault.forget(str(doc_id))
        return True

    # -- seeing the code -----------------------------------------------------
    def search(self, query, limit=20):
        """Prose, kosha and ripgrep in one ranking via `Vault.federate` (`litesearch.rrf_all`).

        A vault that will not open degrades to `LocalHost.search`.
        """
        if not self.federate: return super().search(query, limit)
        try:
            r = self.vault.federate(str(query), limit=int(limit), prose=True, repo=True,
                                    grep=True, dir=self.roots[0])
        except Exception as e:
            self._legs = {'federate_error': agent_err(e)}
            return super().search(query, limit)
        self._legs = dict(r.legs)
        return [_fed_hit(h) for h in r.hits] or super().search(query, limit)

    @property
    def search_note(self):
        if not self.federate: return super().search_note
        if not self._legs: return 'federated: vault prose, kosha index, ripgrep'
        return 'federated: ' + ', '.join(f'{k}={v}' for k, v in self._legs.items())

    # -- reading the web -----------------------------------------------------
    def read_url(self, url, remember=True):
        """Read a page, and keep it unless asked not to.

        `remember=False` is honoured literally -- the page is fetched and returned and never
        touches the vault, which is what it is for. Filing failing is not a read failing, so
        the text is returned either way.
        """
        d = super().read_url(url, remember=remember)
        if d is not None and remember and self.remember_reads:
            try:
                from vishalakshi.acquire import md_title
                self.vault.add(str(d.text), md_title(str(d.text)) or str(url), source=str(url),
                               kind='web', meta=dict(url=str(url), fetched_at=time.time()))
            except Exception as e: self.note(f'could not file {url}: {agent_err(e)}')
        return d

    def research(self, query):
        """Search, read every source into the vault, then answer out of the vault.

        One network pass rather than two: `Vault.web` *is* fossick's `research` with the sources
        kept, so the digest is assembled by asking the vault the same question immediately
        afterwards. What the model reads and what a later session can recall are then the same
        text, instead of a summary of pages nobody kept.
        """
        v, q = self.vault, str(query)
        r = v.web(q, n=5)
        self.connect()            # the graph is what `related` walks; rebuild after the batch, off the turn
        c = v.context(q, sections=MEM_SECTIONS, related=4)
        head = f'searched the web for {q!r}; filed {len(r.added)} of {r.n_found} sources in the vault'
        return '\n\n'.join([head] + [f"## {s['breadcrumb']}\n\n{s['text']}" for s in c.results])

    def ask(self, question, ref=None, instruction='', **kw):
        """Have the vault answer `question` with citations, on this session's model.

        `mk_chat` lends the session's chat factory so the vault does not load a second engine
        from `$VISHALAKSHI_MODEL`. `pii` is stripped: a tool argument must not be able to send
        retrieved private sections to a hosted API.
        """
        kw.pop('pii', None)
        if self.mk_chat is not None: kw.setdefault('mk_chat', self.mk_chat)
        if instruction:
            base = kw.get('sp') or ''
            kw['sp'] = (base + '\n\n' if base else '') + str(instruction)
        return self.vault.ask(question, ref=ref, **kw)

    @property
    def research_note(self): return f'fossick, filed in {Path(self.vault.path).name}'

    # -- standing interests --------------------------------------------------
    def remember(self, text, title=None, tags=()):
        return self.vault.note(str(text), title=title, tags=list(tags or []))

    def watch(self, target, action='remind', every='1d', note=None, **params):
        return self.vault.watch(str(target), action=action, every=every, note=note, **params)

    def watches(self, due_only=False):
        return [dict(w) for w in self.vault.watches(due_only=bool(due_only))]

    def unwatch(self, watch_id): return self.vault.unwatch(str(watch_id))

    def poll(self):
        """Fire everything due. `connect=False`: the graph rebuild is the expensive part.

        `Vault.poll` rebuilds the entity graph when anything succeeded, which reads the whole
        store -- right for a nightly cron, wrong for a tool call the user is waiting on. So
        the tick returns as soon as the watches have run, and the rebuild it earned goes to
        `connect`, which is a background thread and coalesces with `research`'s.
        """
        r = self.vault.poll(connect=False)
        if r.get('ran'): self.connect()
        return r

    @property
    def watch_actions(self):
        from vishalakshi.acquire import ACTIONS
        return ACTIONS

