"""Memory that outlives the process: one vishalakshi vault behind `Host`, and the standing
watches that put things back on the agent's desk.

Docs: https://vedicreader.github.io/ramabana/vault.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_vault.ipynb.

# %% auto #0
__all__ = ['DFLT_VAULT', 'MEM_SECTIONS', 'TOC_DEPTH', 'safe_shelf', 'VaultHost']

# %% ../nbs/07_vault.ipynb #bcb01f4f
import json, re, threading, time
from pathlib import Path
from fastcore.basics import AttrDict
from fastcore.meta import delegates
from fastcore.parallel import startthread
from .core import AgentError, agent_err
from .tools import Hit, LocalHost, clip

# %% ../nbs/07_vault.ipynb #8d87918f
DFLT_VAULT = None         # Vault(None) -> ~/.vishalakshi/vault.db, same as the CLI
MEM_SECTIONS = 6          # operative sections a memory search returns
TOC_DEPTH = 2             # heading levels of a document's tree worth showing at once


def safe_shelf(name=None, dflt='store'):
    "Return a valid SQL table-prefix identifier for a shelf name."
    return re.sub(r'[^a-z0-9_]+', '_', str(name or dflt).lower()).strip('_') or dflt

# %% ../nbs/07_vault.ipynb #d2ba7a3a
def _trim(node, depth=TOC_DEPTH):
    "One heading tree, cut to `depth` levels: a whole tree is a document, not an index entry."
    if not isinstance(node, dict): return node
    out = {k: node.get(k) for k in ('id', 'title', 'pages') if node.get(k) is not None}
    kids = node.get('children') or []
    if depth > 0 and kids: out['children'] = [_trim(k, depth - 1) for k in kids]
    elif kids: out['children'] = f'{len(kids)} more'
    return out


def _sect(s):
    "One retrieved section, cut to what a model needs: what it says, where it is, how to read it."
    return {k: s[k] for k in ('node_id', 'doc_id', 'title', 'breadcrumb', 'text', 'pii') if k in s}


def _fed_hit(h):
    "A federated row as a `Hit`, with a handle for reopening. The handle's `symbol` identifies relevant info: `mod_name` for symbols, `node_id` for `memory_read`. It varies by hit type."
    where = str(h.get('where') or h.get('ref') or '')
    path, _, num = where.rpartition(':')
    if h.get('source') == 'prose': return Hit(where, 1, str(h.get('ref') or ''), str(h.get('text') or '')[:200])
    return Hit(path if num.isdigit() else where, int(num) if num.isdigit() else 1, str(h.get('ref') or h.get('title') or ''), str(h.get('text') or '')[:200])

# %% ../nbs/07_vault.ipynb #bc5c6436
class VaultHost(LocalHost):
    "A `LocalHost` with durable memory, federated search and watches."

    @delegates(LocalHost.__init__)
    def __init__(self,
                 roots=('.',),          # the folders the agent is confined to
                 vault=DFLT_VAULT,      # a `Vault`, a path to one, or None for ~/.vishalakshi/vault.db
                 shelf=None,            # the shelf writes land on. None -> the vault's main store
                 federate=True,         # fuse vault prose into `search_code` alongside kosha and ripgrep
                 remember_reads=True,   # file what `read_url` fetches. The next session has it
                 warm=True,             # open the vault in the background at construction
                 mk_chat=None,          # build the vault's chats with this. None -> vishalakshi's own
                 pii=None,              # `off|redact|refuse` for what retrieval returns, or a callable for one
                 pii_ner=None,          # gate on titled names too. A callable, like `pii`, is read per call
                 **kwargs):             # forwarded to `LocalHost`
        super().__init__(roots, **kwargs)
        self.mk_chat, self.pii, self.pii_ner = mk_chat, pii, pii_ner
        import threading
        self.shelf = safe_shelf(shelf) if shelf else None
        self._vault, self._vlock, self._vthread = vault, threading.Lock(), None
        self.federate, self.remember_reads = federate, remember_reads
        self._legs, self._cthread = None, None
        self.without = self.without - {'memory', 'ask', 'watch'}
        if warm: self.open_vault()


    def open_vault(self, wait=False):
        "Open the vault once in a daemon thread; join it when `wait=True`."
        if self._vthread is None or not self._vthread.is_alive():
            self._vthread = startthread(lambda: self._open(), daemon=True)
            self._vthread.name = 'ramabana-vault'
        if wait: self._vthread.join()
        return self

    def _open(self):
        "Open the write shelf once under a lock."
        with self._vlock:
            v = self._vault
            if v is None or isinstance(v, (str, Path)):
                from vishalakshi import Vault
                v = Vault(str(v)) if v is not None else Vault()
                if self.shelf and self.shelf != v.name: v = v.shelf(self.shelf)
                self._vault = v
            return v

    @property
    def vault(self):
        "Return the `Vault`, opening it on first use."
        return self._open()

    def _policy(self):
        """`(pii, pii_ner)` for this call. The host asks a function now rather than at construction,
        because the policy changes while a session runs. `off` is the default, and a function that
        raises falls back to it."""
        def val(x):
            try: return x() if callable(x) else x
            except Exception: return None
        return (val(self.pii) or 'off'), bool(val(self.pii_ner))

    def _worker_vault(self):
        'Open this vault on a new connection for one background operation.'
        root = self.vault
        if not root.db.conn.filename: return root
        from vishalakshi import Vault
        v = Vault(root.path, encoder=root.enc, store=root.name)
        v.db.conn.set_busy_timeout(30_000)
        return v

    def connect(self, wait=False):
        "Rebuild the entity graph in a background thread."
        if self._cthread is None or not self._cthread.is_alive():
            def run():
                root = self.vault
                v = self._worker_vault()
                try: v.connect()
                except Exception as e: self.note(f'could not rebuild the memory graph: {agent_err(e)}')
                finally:
                    if v is not root: v.db.conn.close()
            self._cthread = startthread(run, daemon=True)
            self._cthread.name = 'ramabana-vault-connect'
        if wait: self._cthread.join()
        return self


    def memory_search(self, query, limit=MEM_SECTIONS):
        "Return matching sections and related sections."
        pii, ner = self._policy()
        c = self.vault.context(str(query), sections=int(limit), related=max(2, int(limit) // 2),
                               pii=pii, pii_ner=ner)
        return dict(query=c.query, encoder=c.encoder,
                    results=[_sect(s) for s in c.results],
                    related=[dict(_sect(s), via=s.get('via')) for s in c.related])

    def memory_tree(self, document=''):
        "Return the memory heading tree, optionally narrowed by title or document id."
        # every node is titled by the opening of its section, so the tree carries section text
        pii, ner = self._policy()
        toc, d = self.vault.toc(pii=pii, pii_ner=ner), str(document).strip().lower()
        if d: toc = [t for t in toc if d in str(t.get('title', '')).lower() or d == t.get('doc_id')]
        return [dict(doc_id=t.get('doc_id'), title=t.get('title'), source=t.get('source'),
                     pages=t.get('pages'), tree=_trim(t.get('tree'))) for t in toc]

    def memory_read(self, node_id):
        pii, ner = self._policy()
        return self.vault.read(str(node_id), pii=pii, pii_ner=ner)

    def memory_topics(self, limit=12):
        m = self.vault.map()
        return dict(method=m.get('method'), note=m.get('note'),
                    clusters=list(m.get('clusters') or [])[:int(limit)])

    def memory_forget(self, doc_id):
        self.vault.forget(str(doc_id))
        return True

    def search(self, query, limit=20):
        "Ranks prose, kosha, and ripgrep via `Vault.federate` (`litesearch.rrf_all`). If the vault can't open, it defaults to `LocalHost.search`."
        if not self.federate: return super().search(query, limit)
        pii, ner = self._policy()
        try:
            r = self.vault.federate(str(query), limit=int(limit), prose=True, repo=True,
                                    grep=True, dir=self.roots[0], pii=pii, pii_ner=ner)
        except Exception as e:
            self._legs = {'federate_error': agent_err(e)}
            return super().search(query, limit)
        self._legs = dict(r.legs)
        return [_fed_hit(h) for h in r.hits] or super().search(query, limit)

    @property
    def search_note(self):
        if not self.federate: return super().search_note
        if not self._legs: return 'federated: vault prose, kosha index, ripgrep'
        return 'federated: ' + ', '.join(f'{k}={v}' for k, v in self._legs.items())


    def read_url(self, url, remember=True):
        "Fetches a page and returns it without storing, unless `remember=False` is set, in which case it still fetches and returns the text."
        d = super().read_url(url, remember=remember)
        if d is not None and remember and self.remember_reads:
            try:
                from vishalakshi.acquire import md_title
                self.vault.add(str(d.text), md_title(str(d.text)) or str(url), source=str(url),
                               kind='web', meta=dict(url=str(url), fetched_at=time.time()))
            except Exception as e: self.note(f'could not file {url}: {agent_err(e)}')
        return d

    def research(self, query):
        "Searches and reads sources into the vault, then answers from it. This consolidates web research into the vault, making recall accurate and consistent."
        v, q = self.vault, str(query)
        pii, ner = self._policy()
        r = v.web(q, n=5)
        self.connect()            # the graph is what `related` walks. Rebuild after the batch, off the turn
        c = v.context(q, sections=MEM_SECTIONS, related=4, pii=pii, pii_ner=ner)
        head = f'searched the web for {q!r}; filed {len(r.added)} of {r.n_found} sources in the vault'
        return '\n\n'.join([head] + [f"## {s['breadcrumb']}\n\n{s['text']}" for s in c.results])

    def ask(self, question, ref=None, instruction='', **kw):
        "Asks the vault to answer `question` with citations using the session's model, avoiding duplicate engine loads and stripping PII; `instruction` follows the turn directly."
        kw.pop('pii', None)
        if self.mk_chat is not None: kw.setdefault('mk_chat', self.mk_chat)
        return self.vault.ask(question, ref=ref, instruction=str(instruction or ''), **kw)

    @property
    def research_note(self): return f'fossick, filed in {Path(self.vault.path).name}'
    def remember(self, text, title=None, tags=()): return self.vault.note(str(text), title=title, tags=list(tags or []))
    def watch(self, target, action='remind', every='1d', note=None, **params): return self.vault.watch(str(target), action=action, every=every, note=note, **params)

    def watches(self, due_only=False): return [dict(w) for w in self.vault.watches(due_only=bool(due_only))]
    def unwatch(self, watch_id): return self.vault.unwatch(str(watch_id))

    def poll(self):
        'Fire due watches on a separate connection, then rebuild the graph in the background.'
        root = self.vault
        v = self._worker_vault()
        try: r = v.poll(connect=False)
        finally: 
            if v is not root: v.db.conn.close()
        if r.get('ran'): self.connect()
        return r

    @property
    def watch_actions(self):
        from vishalakshi.acquire import ACTIONS
        return ACTIONS
